### ISSUE TITLE
prevent oauth csrf via 'state' field

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#1]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Tuesday Nov 11, 2014 at 01:15 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/19_

----

**Comment by ericchiang** [comment]
We support the state field, so it's up to the client to do this.
