### ISSUE TITLE
Okta login bad redirection

### ISSUE THREAD

**Issue by pollosp** [coreos/dex#1023]
We are following this documentation https://github.com/coreos/dex/blob/master/Documentation/dev-integration-tests.md in order to setup Okta connector. We are expecting an unexpected behavior, when we use Okta to log into tectonic cluster console application. By default Okta redirect us to https://xx.yy.zz/identity/callback giving us a bad request error. After that if we go to https://xx.yy.zz/ and click into login with okta or we or the session is still valid, it work without problems. Looks like we should redirect to https://xx.yy.zz/ instead https://xx.yy.zz/identity/callback. 
We are using DEX with tectonic console with in tectonic cluster 1.6.2 and it is using this image `quay.io/coreos/dex:v2.4.1`, any idea?
Thanks :)
 
![tectonic](https://user-images.githubusercontent.com/1783343/29259988-17e133e8-80c7-11e7-8ac7-f31f78795f6b.gif)

**Comment by rithujohn191** [comment]
Please note that the `ssoURL:` you configure in the Dex ConfigMap is not the same as the `redirectURI:`. The `ssoURL:` is that which is provided by Okta which allows you to access the Login Page from an external app.

**Comment by ericchiang** [comment]
Based on the emoji responses I'm going to assume that was the issue. Please comment if you feel that there's a bug in dex.

**Comment by tmxak** [comment]
I'm having exactly the same issue setting up the ArgoCD with Dex.. Trying to authenticate the same way (via okta app icon) and it gives "Bad Request". If I go to the application main page and then do the "Login with Okta" - i'm authenticated

**Comment by tmxak** [comment]
So I found that Dex doesn't support Provider-initated login flows. Thats why it fails to login from the okta application icon.
