### ISSUE TITLE
Cors configuration

### ISSUE THREAD

**Issue by ekarlso** [coreos/dex#1024]
Hi, I want to deploy dex as a addition to get auth to my app that uses cors to reach dex for discovery:
web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/tls/tls.crt
  tlsKey: /etc/dex/tls/tls.key
  allowedOrigins:
    - "http://gatekeeper.minikube"

but the browser then says it's not allowed since the rights headers arent coming back when doing discovery?

**Comment by ericchiang** [comment]
Under the web you can specify `allowedOrigins` to white list certain domains for the /token and /auth endpoints

```
web:
  allowedOrigins: ['*']
```

Looks like an issue has been opened to document this https://github.com/coreos/dex/issues/1025, so I'm gonna close this one.
