### ISSUE TITLE
TestLoginTimeout takes 20 seconds to run

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#1030]
The rest take 3. We should really fix that.

**Comment by ericchiang** [comment]
Some thoughts:

* The test shouldn't be tied to a literal value `10*time.Second` embedded in the server.
* We should probably just reject bcrypt values that are too high. If we compute something with a cost of 20, it'll still eat up CPU in the other goroutine even if we exit early to a user.
* We should generally timeout for long HTTP requests. There might be a more general solution like some server middleware.

cc @estroz

**Comment by estroz** [comment]
@ericchiang closing (fixed by #1040) and creating an issue specifically addressing generic request timeouts.
