### ISSUE TITLE
SAML: rootElementSigned should be false by default

### ISSUE THREAD

**Issue by easeway** [coreos/dex#1043]
https://github.com/coreos/dex/blob/master/connector/saml/saml.go#L287

`rootElementSigned` should be false, otherwise with InsecureSkipSignatureValidation is true in configure, the following code doesn't work properly.

**Comment by ericchiang** [comment]
What doesn't work about the code? `rootElementSigned` is more for us to note when the root element isn't signed because it's not worth verifying unsigned parts of the response. When skipping signature validation, we still want to verify that the top level elements match what we expect.

**Comment by easeway** [comment]
@ericchiang you are right. It was caused by other issues.
