### ISSUE TITLE
LDAP bindPW with dollar character causes Invalid credentials

### ISSUE THREAD

**Issue by kiich** [coreos/dex#1051]
When using the ldap connector with bindPW with dollar sign (I haven't tried any other special characters) with example-app, the initial bind does not seem to get authenticated and throws:

```
{"level":"error","msg":"Failed to login user: ldap: initial bind for user \"cn=...\" failed: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1\u0000","time":"2017-08-25T10:19:24Z"}
```

After digging into it, it seems the $ sign was not being passed correctly.
e.g. using in config-ldap.yaml
```
    bindPW: 123$$$$45
```
When I dump out what got used as bindPW, I see:
`"bindPW":"12345"`

I haven't dug into to much so could be missing some escaping sequence in the yaml. I tried using double quote, single quote and `\` to escape but no avail.

**Comment by kiich** [comment]
Seems after the os.ExpandEnv line in `cmd/dex/config.go` causes the removal of '$', presumably as it is trying to expand environment variable.

```
data := []byte(os.ExpandEnv(string(conn.Config)))
``` 

`data` directly after seems to have stripped the '$' from my bindPW password.

**Comment by kiich** [comment]
My current workaround, after finding it is calling ExpandEnv is to set an environment variable that has `$` as value and reference the environment variable in config.yaml and start dex server
i.e.
```
export D='$$$$'
```

in config.yaml
```
bindPW: "123${D}45"
```

Messy, but worked!

**Comment by ericchiang** [comment]
This is really unfortunate but I don't know if we can fix without breaking backward compatibility. We're already considering redoing dex's config format and removing the env expansions https://github.com/coreos/dex/issues/968

Going to close this out for that issue.

**Comment by kiich** [comment]
Thanks @ericchiang for the feedback - good to know there are plans ahead for redoing config format to potentially fix this.

For now, I have a work around using env.variable so ok for this to be closed. Will keep an eye out on #968

**Comment by rodrigoGA** [comment]
This drove me crazy for hours -.-!
