### ISSUE TITLE
add dex to list of libraries on OIDC site

### ISSUE THREAD

**Issue by sym3tri** [coreos/dex#107]
After we push the button... we should get added to this list.

http://openid.net/developers/libraries/

**Comment by rohe** [comment]
You should also verify your implementation using the tools provided by the OpenID Foundation http://openid.net/certification/ .
If you have any questions about this talk to me - I'm the maintainer of the tools.

**Comment by bobbyrullo** [comment]
Thanks @rohe, that's definitely [on our radar](https://github.com/coreos/dex/issues/42).

**Comment by ericchiang** [comment]
This has been done :tada:
