### ISSUE TITLE
Cross clients improvement - requesting client ID always added to the audience claim

### ISSUE THREAD

**Issue by dpacierpnik** [coreos/dex#1087]
# Context

If you want to fetch ID token for trusted peer, you have to specify predefined scope: *audience:server:client_id:{peerID}* . But if you specify this scope only for the peer, and you do not specify explicitly this scope with requesting client id (*audience:server:client_id:{clientID}*), the audience claim does not contain requesting client.
In such case the ID token is invalid for the client: the client should always validate fetched ID token, and should meet following rules of ID token validation: http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation (point 3). 
I wonder is there any real scenario, where you want to have an ID token without the requesting client ID in the audience claim ? If not, in my opinion, it would be better to ensure that requesting client is always added to the audience claim (even if you do not request explicitly *audience:server:client_id:{clientID}* scope). It is a little bit confusing that you have to specify this scope also for the requesting client. Additionally it is not even mentioned in DEX documentation (*Cross-client trust and authorized party* section), that ID token from the example is invalid for the client (web-app).

# How to reproduce

You can use DEX example app to fetch ID tokens, and specify only peer ID in *Authenticate for* input. Issued ID token is invalid for the example app (*Failed to verify ID token: oidc: expected audience "example-app" got ["example-peer"]*).

# Solution proposal

Client, which requests ID token (azp) should be always set in the audience claim. Scope *audience:server:client_id:{peerID}* should only add additional client to the audience claim.

# Pull-request

Provided: https://github.com/coreos/dex/pull/1088

**Comment by ericchiang** [comment]
This was actually asked before https://github.com/coreos/dex/issues/984#issuecomment-314281694

> So I think the question is "should aud always contain the azp"? We don't automatically do that today, e.g. if you login to a web app and ask for a id token issued for a client it's possible to get claims like.
> 
>  ```
> "aud": "cli-app",
> "azp": "web-app"
> ```
> Automatically including the azp seems like reasonable behavior, but the current behavior also seems valid. Take a look at google docs for a similar feature https://developers.google.com/identity/protocols/CrossClientAuth#accessTokens
>
> For what it's worth, when specifying cross client scopes, you can request your own client to have it included in the audience.

I think this might be better solved with documentation. This is a nice convince, but makes it impossible to request an id_token without your own client-id as an audience, something that might be desirable.

**Comment by dpacierpnik** [comment]
"might be desirable" ? Do you know any real use case, when client wants to fetch ID token which can not be validated correctly ? OIDC specification states clearly: 

> The Client MUST validate the Token Response as follows:
>
>   Follow the validation rules in RFC 6749, especially those in Sections 5.1 and 10.12.
>   Follow the ID Token validation rules in Section 3.1.3.7.
>   Follow the Access Token validation rules in Section 3.1.3.8.

and Section 3.1.3.7 http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation:

> ...
> The Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer identified by the iss (issuer) Claim as an audience. The aud (audience) Claim MAY contain an array with more than one element. The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience, or if it contains additional audiences not  trusted by the Client. 
> ...

In my opinion such ID tokens are useless and should not be issued. But please fix at least documentation.

**Comment by ericchiang** [comment]
>  Do you know any real use case, when client wants to fetch ID token which can not be validated correctly ?

Sure, Google highlights a pretty compelling use case in the linked reference: https://developers.google.com/identity/protocols/CrossClientAuth#androidIdTokens

Either way, since this has been surprising so often I think it's reasonable to always include the original client_id as part of the audience.
