### ISSUE TITLE
add required required response types to provider config

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#11]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Thursday Dec 04, 2014 at 23:25 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/127_

----

Spec says:

`response_types_supported`
REQUIRED. JSON array containing a list of the OAuth 2.0 response_type values that this OP supports. Dynamic OpenID Providers MUST support the `code`, `id_token`, and the `token id_token` Response Type values.

http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by ericchiang** [comment]
dex correctly provides this field during discovery
