### ISSUE TITLE
Use a service account for minting kubeconfigs [Question]

### ISSUE THREAD

**Issue by jimmythedog** [coreos/dex#1111]
@ericchiang mentioned on #973 that:

> As for kubernetes, you can use a service account for minting kubeconfigs that can be used on multiple machines

Can I first explain what we're trying to do? (in case that is flawed):

- Dex deployed to k8s (LDAP connector)
- Spin up the example-app on a host
- `User1` browses to the example-app URL e.g. http://example-app.host:5555
- Logs into LDAP and gets `id_token` & `refresh_token`
- Configures `kubeconfig`
- `User2` performs the same steps

The problem arises when `User1` `id_token` expires, as an error is returned:

> Refresh token is invalid or has already been claimed by another client.

So, I suppose I have a few questions:

1. Would it be ok to use the `example-app` internally, to return tokens for multiple users?
1. Would @ericchiang comment fix our problem?
1. If so, how *exactly* do we achieve that? (Assume my ignorance, but I just didn't understand the comment about a "service account minting kubeconfigs for multiple machines")

Many thanks in advance
Kevin

**Comment by ericchiang** [comment]
I meant "use a kubernetes service account" https://kubernetes.io/docs/admin/authentication/#service-account-tokens

Here's an example script to do that:

https://gist.github.com/ericchiang/d2a838ddad3f44436ae001a342e1001e

Closing since this isn't related to dex.
