### ISSUE TITLE
"go back to selection" for password template

### ISSUE THREAD

**Issue by srenatus** [coreos/dex#1115]
When using Dex with multiple connectors, and one of them being the _local passwords_ connector, clicking on "Login with Email" here,

<img width="515" alt="screen shot 2017-11-07 at 10 22 45" src="https://user-images.githubusercontent.com/870638/32486043-be0bf3a4-c3a5-11e7-94cf-2856d943012f.png">

leads me to its login dialogue,

<img width="511" alt="screen shot 2017-11-07 at 10 22 51" src="https://user-images.githubusercontent.com/870638/32486031-b1747b48-c3a5-11e7-83c0-4173aac2d831.png">

But, if I mistakenly clicked that, or I've made up my mind, there's no way to go back to the selection.

It's easy to add a ` window.history.back();` link to our template, but in situations where there's only one -- the local users -- connector, that doesn't make any sense, as there's no selection go back to.

Any ideas how to handle this best? I think we'd might have to add another field to the template [here](https://github.com/coreos/dex/blob/ccf85a726922a2fd6e4f0742d99f311dbf1fdb66/server/templates.go#L193-L197)?

**Comment by ericchiang** [comment]
Quick question, does the browser's back button work? I think adding a back link would be fine.

**Comment by srenatus** [comment]
> Quick question, does the browser's back button work? I think adding a back link would be fine.

The browser's back button works -- it takes you back to the selection.

The issue I have is that simply adding a back button to the password template won't work: it needs to know whether there are other connectors. If there's _only one password connector_, the user will never see the selection, and the back button has nowhere to point to.
