### ISSUE TITLE
Dex can't compile

### ISSUE THREAD

**Issue by ibazulic** [coreos/dex#1118]
Hi, I'm running into a strange issue when compiling Dex.  When compiling, the following error occurs:

```
/cut
# github.com/coreos/dex/vendor/github.com/coreos/etcd/pkg/transport
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: cfg.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: undefined: tls.CertificateRequestInfo
vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:178: undefined: net.DefaultResolver in net.DefaultResolver.LookupAddr
/cut
Makefile:23: recipe for target 'bin/dex' failed
make: *** [bin/dex] Error 2
```

Not sure if this is a problem with my environment or what. Make was run with no options, this is the environment:

```
root@node01:~/dex_test/src/github.com/coreos/dex# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@node01:~/dex_test/src/github.com/coreos/dex#

root@node01:~/dex_test/src/github.com/coreos/dex# go version
go version go1.7.4 linux/amd64
root@node01:~/dex_test/src/github.com/coreos/dex#

root@node01:~/dex_test/src/github.com/coreos/dex# export | grep GOPATH
declare -x GOPATH="/root/dex_test"
root@node01:~/dex_test/src/github.com/coreos/dex#

```

Any idea as to what I'm doing wrong? Thanks!

**Comment by ericchiang** [comment]
GetClientCertificate was added in Go 1.8, so Go1.7 will be too old to build dex with https://golang.org/doc/go1.8#crypto_tls

I'll update our build scripts to catch this.

**Comment by ibazulic** [comment]
Hi Eric,

Thanks for the prompt response. I'll update go on my test machine and start again.

**Comment by arkachat** [comment]
Makefile:23: recipe for target 'bin/dex' failed
make: *** [bin/dex] Error 2
root@1ff736cd2b38:~/work/src/github.com/coreos/dex# go version
go version go1.9 linux/amd64
root@1ff736cd2b38:~/work/src/github.com/coreos/dex# cat /etc/issue
Debian GNU/Linux 9 \n \l

It seems the problem persists.
