### ISSUE TITLE
meta: "getting help" section and release roadmap

### ISSUE THREAD

**Issue by srenatus** [coreos/dex#1122]
In the README, [it says](https://github.com/coreos/dex#getting-help)

> - For more details on dex development plans, check out the GitHub milestones.

But they [milestones](https://github.com/coreos/dex/milestones) seem out of date -- there's 2.5.0 and 2.2.0, and [releases](https://github.com/coreos/dex/releases) already has 2.8.0.

I suppose killing that bullet point from the README is the simplest way to consistency? 😉 

(Of course, I would also appreciate a public roadmap...)

**Comment by ericchiang** [comment]
> I suppose killing that bullet point from the README is the simplest way to consistency? :wink:

Yes sgtm.

Development has been relatively adhoc for a while. That's been the primary reason for a lack of a public roadmap.
