### ISSUE TITLE
Can we cut a v2.8.1 release, please? (Also: GPG key expired)

### ISSUE THREAD

**Issue by srenatus** [coreos/dex#1127]
[The 10 commits to master since v2.8.0 look OK to me.](https://github.com/coreos/dex/compare/v2.8.0...master) I'm obviously interested in #1116 and #1123, but cherry-picking those doesn't seem to make too much sense given that the commits since 2.8.0 are mostly these.

Also, GitHub shows the key used to sign the v2.8.0 tag, `A05E509132EF40C5`, has expired:

<img width="295" alt="screen shot 2017-11-14 at 08 22 18" src="https://user-images.githubusercontent.com/870638/32767821-6477e832-c915-11e7-8424-f158f87f7ed1.png">

@ericchiang I think this is you 😉 

Thanks! 😃

**Comment by ericchiang** [comment]
Thanks. I've modified the expiry of my public key. Green checkboxes should be back.

I'll cherry pick #1116 and #1123 and do a v2.8.1.

**Comment by ericchiang** [comment]
v2.8.1 is live https://github.com/coreos/dex/releases/tag/v2.8.1

**Comment by srenatus** [comment]
@ericchiang thanks a lot!
