### ISSUE TITLE
support login with username/password

### ISSUE THREAD

**Issue by philhug** [coreos/dex#113]
Some prefer to use username/password for authentication instead of email/password.

**Comment by albertoleal** [comment]
That's ok if there is just one authentication provider, because the same username could be different people using Twitter and Github, for example. 

We had used username before we changed to email on a project I work on, just because we decided to add many providers.

**Comment by bobbyrullo** [comment]
We went back and forth on this internally, before we decided to open source, and finally ended up with email, mainly for the reason that we wanted to make registering as frictionless as possible. But there are many good reasons for doing username.

However....making it configurable seems like it might be a PITA - we'd always be worrying about two code paths whenever we deal with registration, changing username, changing email (eg - "Is the username flag on? If so, make sure the username is present, and unique") 

I'm not saying no here...just that it has a cost.

@philhug Is there some workaround you can do? Like, people login through email, but your app maintains a username for them?

@albertoleal The username in this case wouldn't be one they get from Twitter or Github, it would be one they'd choose for their dex account, so it could be guaranteed to be unique (to the dex issuer)

**Comment by philhug** [comment]
preferred way would be to have it centralized and collect both email (email validation) + username.

@bobbyrullo I could live with the limitation that email needs to be present and unique as well, which should reduce the complexity
I currently don't need the option to change the username.

**Comment by bcwaldon** [comment]
Sticking with email/pw for now.
