### ISSUE TITLE
Does DEX support customizing the LDAP group search based on the client_id or selecting connector based on client_id?

### ISSUE THREAD

**Issue by primeroz** [coreos/dex#1137]
## My Scenario 

* 2 Static Clients configured on DEX corresponding to 2 different Kubernetes clusters
* An LDAP Group OU looking like 
```
ou=Groups,o=Org
  -> ou=Cluster1,ou=Groups,o=Org
    -> ou=Sysadmin,ou=Cluster1,ou=Groups,o=Org
      -> member: user1
      -> member: user2
  -> ou=Cluster2,ou=Groups,o=Org
    -> ou=Sysadmin,ou=Cluster2,ou=Groups,o=Org
      -> member: user3
      -> member: user4
```

Ideally I would like to be able to have different groups searches based on the client (cluster) for which the user is authenticating for: 

Se if i select Cluster1 as client_id when authenticating then in the token i will have groups from the right OU ou=Cluster1,ou=Groups,o=Org , and when connecting to kubernetes it should be able based on client_id to make sure is a valid token for this cluster.

Is this , or anthing similar , possible with Dex ?

The only alternative i see is a dedicated Dex per Cluster , which i could do but feels like a burden.

Thanks

**Comment by ericchiang** [comment]
No, this isn't possible today. client_ids are public so I don't know the implications of this.

**Comment by ericchiang** [comment]
Going to close out since the question's been answered. If there's a specific feature request to propose please feel free to open another issue.

**Comment by whereisaaron** [comment]
@primeroz you can use the LDAP connector twice with different `id`, `name`, and `baseDN`. Users can click on the named button for the cluster they want.

```
- type: ldap
  id: ldapCluster1
  name: "Cluster 1"
  ...
  groupSearch:
    ...
    basedDN: "ou=Cluster1,ou=Groups,o=Org"
    ...
- type: ldap
  id: ldapCluster2
  name: "Cluster 2"
  ...
  groupSearch:
    ...
    basedDN: "ou=Cluster2,ou=Groups,o=Org"
    ...
```
