### ISSUE TITLE
Can we get a new minor release, please?

### ISSUE THREAD

**Issue by srenatus** [coreos/dex#1139]
Hiya!

[Since v2.8.1](https://github.com/coreos/dex/compare/v2.8.1...master) we've had

* [the java package option on the grpc definitions](https://github.com/coreos/dex/commit/19cb2a5ffbd1bc452d7b99f13ffe3c392be2ef43)
* [the microsoft connector](https://github.com/coreos/dex/pull/1131)

(The "compare" links also shows the small UX improvements, but these have been cherry-picked in 2.8.1 and thus wouldn't be new in 2.9.0.)

Does that warrant a release? I'd be fine with a 2.8.2; but it is new functionality 🤔 

Thanks

**Comment by ericchiang** [comment]
Yes. I will try to get 2.9.0 out when I get a chance.

**Comment by srenatus** [comment]
@ericchiang thank you! 🎉

**Comment by ericchiang** [comment]
v2.9.0 is now live https://github.com/coreos/dex/releases/tag/v2.9.0

Thanks for opening this issue. I'd like to automate more of this process to we don't require such a manual release in the future.

**Comment by srenatus** [comment]
⏩ Bumping [`core/dex`](https://github.com/habitat-sh/core-plans/pull/1048) (We're using habitat to operate Dex)
