### ISSUE TITLE
Failed to parse authorization request: Unregistered redirect_uri (\"http://192.168.16.15:5555/callback\"

### ISSUE THREAD

**Issue by grailsweb** [coreos/dex#1145]
Hi,
I am trying to test the dex with openldap authentication, running dex on 192.168.16.15 Linux machine. From windows when I try to access the example app page. Getting this error message. What it’s the correct way to register the call back url?

server log.

# ./bin/dex serve examples/openldap-config.yaml
time="2017-12-10T01:57:38Z" level=info msg="config issuer: http://192.168.16.15:5556/dex"
time="2017-12-10T01:57:38Z" level=info msg="config storage: sqlite3"
time="2017-12-10T01:57:38Z" level=info msg="config static client: example-app"
time="2017-12-10T01:57:38Z" level=info msg="config connector: ldap"
time="2017-12-10T01:57:38Z" level=info msg="listening (http) on 192.168.16.15:5556"
time="2017-12-10T01:57:43Z" level=error msg="Failed to parse authorization request: Unregistered redirect_uri (\"http://192.168.16.15:5555/callback\")."

example app:

 ./bin/example-app --listen http://192.168.16.15:5555 --redirect-uri  http://192.168.16.15:5555/callback --issuer http://192.168.16.15:5556/dex
2017/12/09 21:22:17 listening on http://192.168.16.15:5555

**Open LDAP config file**

issuer: http://192.168.16.15:5556/dex
storage:
  type: sqlite3
  config:
    file: examples/dex.db
web:
  http: 192.168.16.15:5556
connectors:
- type: ldap
  name: OpenLDAP
  id: ldap

staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  - '"http://192.168.16.15:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

**Comment by srenatus** [comment]
The formatting doesn't make it easy to read, but isn't there a stray `"` in your second redirectURIs item:
```
- '"http://192.168.16.15:5555/callback'
```
try changing that to `http://192.168.16.15:5555/callback` (you shouldn't need any quotes).

**Comment by grailsweb** [comment]
srenatus, thanks for pointing out the typo. I removed the double quto its working now.
