### ISSUE TITLE
SAML: IdP-initated login

### ISSUE THREAD

**Issue by srenatus** [coreos/dex#1149]
Hey there.

When setting up Dex as a SAML SP in Okta, when you don't specify that it should _not be there_<sup>(a)</sup>, you end up with an icon in the user's home screen:

<img width="839" alt="screen shot 2017-12-15 at 08 32 15" src="https://user-images.githubusercontent.com/870638/34031650-a3e2862e-e172-11e7-8d45-0dc1b40a34a5.png">

To me at least, it's always tempting to click that, and hope that it would just sign me in. 😄 

Technically, it works by just sending an assertion to the configured endpoint; and depending on how this endpoint reacts, it will work or not work. Specifically, Okta allows you to define the _Default RelayState_:

<img width="692" alt="screen shot 2017-12-15 at 08 35 40" src="https://user-images.githubusercontent.com/870638/34031767-2c350fc4-e173-11e7-9edc-e3ce7f7b81f8.png">

### Proposal: Let's make this work!

Currently, the `RelayState` is used in the same way `state` is used for OAuth2 callbacks: to carry around the `authID` ([see here](https://github.com/coreos/dex/blob/ec5e2cc3c6229193d421d247f9c039be82ccfbac/server/handlers.go#L328-L338)).
This ID references the [AuthRequest](https://github.com/coreos/dex/blob/ec5e2cc3c6229193d421d247f9c039be82ccfbac/storage/storage.go#L148-L185); whose details will be initialized when the authentication-through-dex process starts, typically by a call to `/auth`.

Now, in the IdP-initiated setting, we don't have any of these. However, if we're able to specify the default RelayState, we could use that to provide those settings, say, as a `url.Values`-encoded string (and properly documentated).

Of course, some care has to be taken about not compromising our security by this in any unacceptable way, but I don't think that this would block this completely.

**What do you think?**

##### Notes

<details><summary>(a) this would be done by checking the first box here</summary>

<img width="739" alt="screen shot 2017-12-15 at 08 35 29" src="https://user-images.githubusercontent.com/870638/34031743-163e3cae-e173-11e7-8fa6-04acd8a1d235.png">

</details>

**Comment by ericchiang** [comment]
> What do you think?

This scares me. It'd require a pretty intrusive change to dex and prevents us from hardening features like using the `state` to prevent CCRF attacks.

https://security.stackexchange.com/questions/20187/oauth2-cross-site-request-forgery-and-state-parameter

**Comment by srenatus** [comment]
@ericchiang thanks for the feedback. I think another way to improve UX could be to redirect the user to some useful page when they come around with a SAML assertion not carrying any `RelayState`. Since _useful page_ depends on the deployment, and _can be dealt with from templates_, I'm closing this.

**Comment by wanghong230** [comment]
@srenatus Your idea is quite interesting. For IdP-initiated SSO, the call back should be handled and redirect back to go through the SP-initated SSO route to login in. To have two handlers in the web server is trival work.

**Comment by heidemn-faro** [comment]
@srenatus Can you give an example how this "can be dealt with from templates"?
Are you saying that an admin can configure this fallback page already in the current Dex version?
Thanks :-)

> I think another way to improve UX could be to redirect the user to some useful page when they come around with a SAML assertion not carrying any RelayState. Since useful page depends on the deployment, and can be dealt with from templates, ...
