### ISSUE TITLE
Integrate example-app into dex server

### ISSUE THREAD

**Issue by mpashka** [coreos/dex#1154]
Usually dex is used as OpenID Connect provider for kubernetes. But in order to setup user authentication dex server itself is not enough. That is because kubectl which is supposed to be OIDC client doesn't provide appropriate functionality. Kubectl doesn't allow you to login to OIDC web page, choose authentication method, provide your credentials, e.t.c.
While DEX server provides example-app that can be used as a client and can initiate client identity verification that is not convenient. Additional application with separate port must be installed. It is not clear what should be used in example app input fields, e.t.c.
So my proposal is to add some internal application into dex server and provide some default configuration for kubernetes that will make it possible using DEX server as is to configure kubectl  without any additional installations or additional client applications creation.
I can provide PR for that if someone supposes that can be useful.

**Comment by ericchiang** [comment]
Dex itself is just the server implementation. Adding a client conflates its role and as such we're not going to add this.

If you developer a more fully featured OIDC client (perhaps a kubernetes specific one?) or example ingress manifests for hosting both apps under the same domain we're happy to link to it.
