### ISSUE TITLE
Warnings while building

### ISSUE THREAD

**Issue by ajanthan** [coreos/dex#116]
While executing ./build i am getting following warnings

➜  dex git:(master) ./build
Could not find go-bindata in path, will not generate migrations
\# github.com/coreos/dex/cmd/dex-worker
link: warning: option -X main.version b340660d6d7ec8064d65a67180b1b4f4b346d581 may not work in future releases; use -X main.version=b340660d6d7ec8064d65a67180b1b4f4b346d581
\# github.com/coreos/dex/cmd/dex-overlord
link: warning: option -X main.version b340660d6d7ec8064d65a67180b1b4f4b346d581 may not work in future releases; use -X main.version=b340660d6d7ec8064d65a67180b1b4f4b346d581

My go version 
➜  dex git:(master) go  version
go version go1.5 linux/amd64

**Comment by bcwaldon** [comment]
Fixed via #141
