### ISSUE TITLE
Running DEX with unknown IP address and relative URLs

### ISSUE THREAD

**Issue by snowzach** [coreos/dex#1162]
I have a question about Dex and want to make sure my assumptions are correct. I love the functionality that Dex provides but I have situations where my server might be hard to get to.

For example, I may need to reach my server via an unknown IP address as well as as over say, a port forwarded SSH tunnel and DNS names might resolve and IP addresses could change.

Is there some mechanism to configure dex such that it's a single endpoint (dex+app) and all auth redirection is relative paths on an unknown IP/Port combination?

Example, I have port forwarding setup so localhost:1234 is forwarded to my server.
I go to my app: `https://localhost:1234/app`
I click login and am redirected to dex: `https://localhost:1234/dex/`
I login with my credentials against a dex back-end successfully and get redirected back to my app: `https://localhost:1234/app`

Is that auth flow a thing or does that break down the security model in some way that I haven't grasped yet?

I tried setting this up but I end up with problems with the issuer not matching or some other errors with it not liking the proxying/port forwarding I have to setup.

It's clear that this could never work using a public Oauth like Google or Facebook but if all my auth methods were local, could this scenario work?

**Comment by srenatus** [comment]
Adding some info from the way I commonly use it, maybe it helps:

Dex's `issuer` setting is independent of the `web.http` setting, so if you had some kind of load-balancer in front of dex (and app!), where everything below `/dex` goes to the dex instance's `web.http` endpoint, you should be good to go.

Also note that it's fine for redirectURIs to be relative. So, it's ok to have a (OAuth2) client with a redirectURI of `/app`. This doesn't help terribly much, but it relieves some of the configuration requirements "behind" the LB.

I'm aware that this doesn't solve your SSH tunnel case. Maybe if your local and remote ports match (say "443"), and you'll add an entry to your workstation's `/etc/hosts` pointing LB-FQDN to 127.0.0.1, you'd be able to make this work? (E.g. forward 443:127.0.0.1:443, and use `https://localhost/dex` for issuer).

**Comment by snowzach** [comment]
I spent some time with dex over the holiday and managed to work out something... I don't love it but it works. Essentially I have my issuer set to a relative address /dex
I then create my own remote oidc verifier keyset based on knowing where DEX is to verify JWT tokens. 
My application will always be colocated with DEX so I don't feel like there's any risk in someone being able to provide their own JWT signing keys to bypass dex. Is there any other caveats anyone can think of to this being a problem?

**Comment by srenatus** [comment]
> Essentially I have my issuer set to a relative address /dex [...] I then create my own remote oidc verifier keyset based on knowing where DEX is to verify JWT tokens

Oh that's interesting. So you ensure by some other means than the hostname (or FQDN) that the you're retrieving the right keyset. Sounds fine to me, although it's probably quite a stretch when comparing with the OIDC spec?

(I just had a quick look, and [it says](http://openid.net/specs/openid-connect-core-1_0.html#IssuerIdentifier)

> **Issuer Identifier**
>    Verifiable Identifier for an Issuer. An Issuer Identifier is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components. 

I wonder what "verifiable" is supposed to mean there, though. It's probably "retrieve discovery doc, compare issuer setting"...)

**Comment by snowzach** [comment]
It currently works although the spec says it must be a URI using https which it technically does not. I'm not sure I like this as a solution but it functions for the time being. Pretty much expecting it to break long term.
