### ISSUE TITLE
Disable "grant access" page

### ISSUE THREAD

**Issue by se0wtf** [coreos/dex#1172]
Hello,
Is there a way to automatically grant access ? (skip the page).
I tried with the query param prompt=none but i still have to grant access.

Thanks,

**Comment by srenatus** [comment]
Could you try adding this to your config file?
```
oauth2:
  skipApprovalScreen: true
```

**Comment by se0wtf** [comment]
It's working !
Thanks ;)

**Comment by srenatus** [comment]
Cool. Can we close this? 😃
