### ISSUE TITLE
Are UPNs supported?

### ISSUE THREAD

**Issue by jacopofar** [coreos/dex#1178]
I have credentials which work with `ldapsearch` but cause a binding error when used with the LDAP connector.

This command gives me the directory data:

`ldapsearch -w $LDAP_SYSTEM_USER_PASSWORD -H ldap://srvndc01.companyname.local:389 -b DC=companyname,DC=local -D serviceldap@companyname.local`

and in `config.yaml` I put:

```
bindDN: serviceldap@companyname.local
bindPW: LDAP_SYSTEM_USER_PASSWORD
```
where LDAP_SYSTEM_USER_PASSWORD is an environment variable containing the password.

When I try to login using LDAP in the example app I get in Dex log the error:
`time="2018-01-26T10:55:50Z" level=error msg="Failed to login user: ldap: initial bind for user \"serviceldap@companyname.local\" failed: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C0903A8, comment: AcceptSecurityContext error, data 52e, v1db1"`

The only difference I see with the example case is that I'm using UPN instead of a string in the form `cn=users,dc=example,dc=com` as in the example config. Is there some special syntax to use in this case? I also tried with the legacy `companyname.local\serviceldap` syntax and got the same error.

**Comment by ericchiang** [comment]
Internally, our code performs a basic Bind when attempting to connect to the LDAP service

https://github.com/coreos/dex/blob/1dbecefadff98e338e697370625e3e3f3fbf749b/connector/ldap/ldap.go#L284

Do we need anything more than that to support UPN? Sorry, just not super familiar with how that interacts with the BIND command.

**Comment by jacopofar** [comment]
Thanks, eventually we found that the problem happens with the `python-ldap` library as well and changed approach
