### ISSUE TITLE
No issuer specified in config file

### ISSUE THREAD

**Issue by eroji** [coreos/dex#1196]
I am trying to follow the documentation on: https://github.com/coreos/dex/blob/master/Documentation/connectors/ldap.md. When I created a custom LDAP config and try to start Dex to serve requests using it, it returns the following error

`invalid config: no issuer specified in config file`

I don't see an issuer value anywhere in the example config.

**Comment by ericchiang** [comment]
The LDAP document you pointed at doesn't have all of the fields required by a full config. Try this instead https://github.com/coreos/dex/blob/master/examples/config-ldap.yaml
