### ISSUE TITLE
implicit grants

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#12]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Thursday Dec 04, 2014 at 23:46 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/128_

----

The spec requires us to support it. We need to do so or document that we intentionally diverge from the spec.

> `grant_types_supported`
> OPTIONAL. JSON array containing a list of the OAuth 2.0 Grant Type values that this OP supports. Dynamic OpenID Providers MUST support the authorization_code and implicit Grant Type values and MAY support other Grant Types. If omitted, the default value is ["authorization_code", "implicit"].

http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by ericchiang** [comment]
Moved to #256
