### ISSUE TITLE
Cannot connect to a dex-worker

### ISSUE THREAD

**Issue by neumino** [coreos/dex#120]
Hello ladies and gentlemen. I have a few issue setting up a dex environment. I'm currently just trying to set up on my own machine. I'm using the container on quay.io/coreos/dex.

Postgres is running, and the overloard and worker seem to work fine. I can register my app without problem.

My problem is when running the app example. I get the following errors:
```
ERROR: Failed fetching provider config, trying again in 3s: Get http://127.0.0.1:5556/.well-known/openid-configuration: read tcp 127.0.0.1:41224->127.0.0.1:5556: read: connection reset by peer
```

If I try a `wget` on the url that can't be fetched, I get the following (from localhost)

```
michel@xone:~/projects/whitedraft/src/gitlab.com/neumino/whitedraft$ wget http://localhost:5556/.well-known/openid-configuration
--2015-09-12 16:45:05--  http://localhost:5556/.well-known/openid-configuration
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5556... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```

Starting a container and linking it against the dex worker and performing a wget just throw with a "connection refused" error.

The dex worker doesn't have any problem to start
```
docker run --name dexworker -it -p 5556:5556 quay.io/coreos/dex /opt/dex/bin/dex-worker --db-url=postgres://<USER>:<PASSWORD>@172.17.42.1:5432/dex_db?sslmode=disable --key-secrets=<SECRETKEY> \
	--email-cfg=/opt/dex/email/emailer.json --log-debug=true
INFO: Debug logging enabled.
DEBUG: Debug logging enabled.
WARN: Running with no limit on: database idle connections
WARN: Running with no limit on: database open connections
INFO: Loaded IdP connector: id=local type=local
INFO: Loaded IdP connector: id=google type=oidc
INFO: Binding to 127.0.0.1:5556...
```

I'm kind of running out of ideas. Why would the worker refuse connections?
I peeked into coreos/go-oicd, and I didn't see any reason why thing would fail. I also looked at cmd/dex-worker/main.go and don't really see why connection would be refused (especially since I'm using plain http for now).

Any hint on what I did wrong? Thanks!

**Comment by neumino** [comment]
Hum, seems to be related to the container itself. I can connect if I manually build it.
Closing as it's not related to dex.

**Comment by neumino** [comment]
Commenting just in case someone run into that.

I was just missing the parameter `--listen` for the dex worker.

**Comment by anthonator** [comment]
What did you specify for the `--listen` parameter?

**Comment by ericchiang** [comment]
You should be able to supply something like

```
--listen 'http://0.0.0.0:5556'
```

Does that not work?

**Comment by janekolszak** [comment]
Please add this info to the tutorial
