### ISSUE TITLE
LDAP connector ignores port in the host string

### ISSUE THREAD

**Issue by ptzianos** [coreos/dex#1204]
In my configuration the host of the ldap service is configured like this:
`host: **.****.de:1636`

The result is that the service is throwing away the port and it's trying to use port 636 instead. Now don't ask why we are using a non-standard port, that's a sad story for another day. What I would like the service to do is to use the supplied port, 1636 in my case.

Looking a little bit at the code I think the error is located here:
`if host, _, err = net.SplitHostPort(c.Host); err != nil {` from connector/ldap/ldap.go:204
this will throw away the port whether or not it's there.

I think it is important if a user sets the port in the host string, to use that port, and not try to guess it. If it's missing from the host then use one of standard ports.

**Comment by ericchiang** [comment]
I'm fairly certain this is working. It's not the prettiest code, but the "host" field is for our LDAP TLS validation, not the dial later on. Our test servers listen on non-standard ports and that works just fine.

https://github.com/coreos/dex/blob/f2eac0e7238e93106d6cceb60c7dd0a89f9a1099/connector/ldap/ldap_test.go#L595-L609
