### ISSUE TITLE
ERROR: Unable to migrate database, retrying in 1m0s: user: Current not implemented on linux/386

### ISSUE THREAD

**Issue by zyren88** [coreos/dex#122]
why i run  standup-db.sh by "DEX_GOOGLE_CLIENT_ID=<<your_client_id>> DEX_GOOGLE_CLIENT_SECRET=<<your_client_secret>> && source  contrib/standup-db.s" failed?
it should happped when run command "./bin/dex-overlord &", error notice is:
ERROR: Unable to migrate database, retrying in 1m0s: user: Current not implemented on linux/386

i have installed and running postgress, and can operate db using psql tool normally.
linux system info is:
Linux ubuntu 3.16.0-49-generic #65~14.04.1-Ubuntu SMP Wed Sep 9 10:03:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zyren88** [comment]
I have solved this problem myself.
go env show
GOARCH="386"    (i don't know why)
GOHOSTARCH="amd64" 
 it should be 
GOARCH="amd64"
GOHOSTARCH="amd64"

**Comment by bobbyrullo** [comment]
Phew!
