### ISSUE TITLE
[question] Using Dex with an OIDC provider that does not implement discovery.

### ISSUE THREAD

**Issue by nirosys** [coreos/dex#1228]
Hey All,

I'm working on deploying Dex with an external OIDC provider that currently does not implement discovery.

Can Dex currently be used in this situation? It seems to me that Dex's use of go-oidc pretty much requires discovery to be available, but maybe I missed something.

If not, is there an interest in providing the option to manually configure the OIDC provider for Dex? I would be able to provide a PR if there was a preferred implementation.

Thank You.

**Comment by ericchiang** [comment]
Dex does implement discovery.

https://github.com/coreos/dex/blob/master/server/handlers.go#L93-L106

We even have tests with go-oidc

https://github.com/coreos/dex/blob/036e5d050dacdb3aa51029206e2bc26862abfbc3/server/server_test.go#L137
