### ISSUE TITLE
Linking User Accounts

### ISSUE THREAD

**Issue by pree** [coreos/dex#1236]
Hey,

is it possible with dex to link user accounts from different connectors ?
e.g. user logs in with GitHub or LinkedIn and results as the same User Account in the Web-App.

Auth0 does this and I think its pretty neat: https://auth0.com/docs/link-accounts

**Comment by ericchiang** [comment]
This requires more state and user management facilities then we're likely to add at this time. If you would like to do this consider doing the linking in whatever app is using dex to authenticate users.
