### ISSUE TITLE
Why the generated access_token does not save to the database

### ISSUE THREAD

**Issue by Victoryship** [coreos/dex#1237]
![image](https://user-images.githubusercontent.com/19524632/40107586-3a3c4f26-592b-11e8-802f-c981ea8d032e.png)
![image](https://user-images.githubusercontent.com/19524632/40107726-9ba1ed16-592b-11e8-9192-ecd52fc51691.png)

The newly generated access_token is only output at the end. It is not saved to the database. How to verify the third party's access_token is valid later?

**Comment by ericchiang** [comment]
Dex doesn't use the access token since it doesn't have an API for users. The ID Tokens is the field the client should care about anyway.

For now it's a random value to ensure no clients depend on the returned value and so we can use it in the future if a use case comes up.

**Comment by dpaks** [comment]
@ericchiang Is this the access token which can be used to authenticate APIs like the one for github?
