### ISSUE TITLE
How can I associate the key with the client_id？

### ISSUE THREAD

**Issue by Victoryship** [coreos/dex#1238]
How can I associate the key with the client_id. A client_id generates a fixed key. Return the public key to the client. However, I discovered that the public key will change periodically. Is it possible to store client_id and public and private keys together in the database?

**Comment by ericchiang** [comment]
Keys aren't associated with clients they're global to dex. Keys rotate occasionally in accordance with http://openid.net/specs/openid-connect-core-1_0.html#RotateSigKeys
