### ISSUE TITLE
consider storing optional client identity meta data 

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#13]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Thursday Dec 11, 2014 at 18:41 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/146_

----

There are many more OPTIONAL fields beyond just `id` and `secret`. For instance `name` and `contacts` seem like good ones for us to consider given that we'll provide a listing of all registered clients in the admin UI and client ids are not very user-friendly.

http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata

**Comment by ericchiang** [comment]
All fields in client metadata is stored in the DB.
