### ISSUE TITLE
when clicking the "looks like you've already registered link" invalid request

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#135]
from logs: 
ERROR: Invalid auth request: missing 'openid' in 'scope'

**Comment by stongo** [comment]
I'm going to try to fix this today. This function doesn't maintain the scope query params https://github.com/coreos/dex/blob/2a1d32e6e8e983cebdb50999ddd5c2cc73a945e8/server/register.go#L283

**Comment by bobbyrullo** [comment]
Awesome - thanks @stongo
