### ISSUE TITLE
Sync connector configs

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#14]
<a href="https://github.com/bcwaldon"><img src="https://avatars.githubusercontent.com/u/548759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcwaldon](https://github.com/bcwaldon)**
_Friday Dec 12, 2014 at 03:27 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/149_
---

authd-worker checks the database once at startup for connector configs, but does not watch for changes. The worker needs to watch the DB, responding to changes by reconfiguring the server.

**Comment by ericchiang** [comment]
Connector configs are now static config options. Closing.
