### ISSUE TITLE
Titles of Public facing dex pages are "Dex"

### ISSUE THREAD

**Issue by joeatwork** [coreos/dex#142]
When logging in, the title of the page the user sees is "dex". It would be cool if this was (maybe just slightly) configurable, like --issuer-logo-url, so we could see "Bananacorp Login"  or just "Bananacorp Authentication" or something in the browser's title bar and in bookmarks.

**Comment by bcwaldon** [comment]
We already provide configurability of the `--issuer-name`, so we should just use that value for the page titles.
