### ISSUE TITLE
/reset-password URL path may confuse users who have never set a password before

### ISSUE THREAD

**Issue by joeatwork** [coreos/dex#148]
Right now, when a user is invited for the first time they often hit a URL of the form `/reset-password?token=....` - it would be a bit more natural if that endpoint was spelled (in this case only) `/invite?token=...` or something similar.

**Comment by bobbyrullo** [comment]
Maybe we could have /reset-password and /invite both have the same handler?

**Comment by joeatwork** [comment]
That sounds really good to me!

**Comment by bobbyrullo** [comment]
just capturing what we talked about in person: /respond_to_invite (or whatever) will do two things: mark email_verified as true, and redirect to change password handler.

**Comment by ericchiang** [comment]
This endpoint no longer exists.
