### ISSUE TITLE
Share cache of OIDC data between workers

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#15]
<a href="https://github.com/bcwaldon"><img src="https://avatars.githubusercontent.com/u/548759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcwaldon](https://github.com/bcwaldon)**
_Monday Dec 15, 2014 at 18:12 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/153_

----

The authd-worker nodes individually sync the OIDC provider configs and verification keys. This has two problems:
1. having all workers make requests is wasteful compared to making a single request
2. the workers could get out of sync, which could result in unexpected behaviors during the auth flow

**Comment by ericchiang** [comment]
This would be nice to have but we'd like a more specific proposal for this issue. For now everything should go through a repo interface which could optionally implement peer caching.
