### ISSUE TITLE
offline_access binary data encoding bug

### ISSUE THREAD

**Issue by polvi** [coreos/dex#153]
When I use the offline_access scope, the returned oauth2.TokenResponse.RefreshToken is a literal string([]byte) data. It should be a base64 string of the binary data. 

I encountered this issue while using offline_access scope and doing `oac.RequestToken(oauth2.GrantTypeAuthCode, code)`

**Comment by yifan-gu** [comment]
@polvi Are you using `--no-db`? `--no-db` will use a in memory backend which is for testing, in that case the returned the token is binary for easy testing. This should not happen with postgres as backend. But I filed a fix for it.
