### ISSUE TITLE
don't format NumericDates as floating point in tokens

### ISSUE THREAD

**Issue by joeatwork** [coreos/dex#156]
I got a token with the following claims from dex

`{..."exp":1.444810947e+09, ... "iat":1.444767747e+09 ....}`

These dates happen not to lose any precision, but the scientific notation sure freaked me out for a minute! It might be better to spell these as decimal integers in longform (particularly since you don't save any bytes adding the extra decimal and exponent in this case.)

**Comment by bcwaldon** [comment]
FYI This is golang's default behavior. Is this causing you any parsing errors? Will this make it more difficult to consume dex JWTs in different languages? Does this conform to the OIDC/JOSE specs?

**Comment by joeatwork** [comment]
I suspect that parsers are going to want to store these as floating point, which will mean they'll lose precision. In these cases, we really want integer values. I read this as the difference between "27" and "27f".

The JSON RFC actually says this sort of thing is (probably?) ok:

> Since software that implements IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is generally available and widely used, good interoperability can be achieved by implementations that expect no more precision or range than these provide, in the sense that implementations will approximate JSON numbers within the expected precision....Note that when such software is used, numbers that are integers and are in the range `[-(2**53)+1, (2**53)-1]` are interoperable in the sense that implementations will agree exactly on their numeric values.

http://rfc7159.net/rfc7159#rfc.section.6

Still, there is enough wiggle in there that it seems like formatting the numbers in ways that are unambiguously intended to be integers (no decimal point, no exponent) seems like a good idea.
