### ISSUE TITLE
Confusing error message on user creation

### ISSUE THREAD

**Issue by bcwaldon** [coreos/dex#162]
I deployed dex using a fake emailer config, and when I tried to add a user I saw the following error message (verbatim): `ERROR: error sending password reset email No HTML or Text template found for template name.:`. I feel like there is some context missing from this after the colon.

**Comment by ecnahc515** [comment]
My guess is that an empty string was passed as the "name" of the template execute, rather than the context missing after the colon.

**Comment by bobbyrullo** [comment]
No guessing please. The issue was an incorrectly named environment variable.

**Comment by bcwaldon** [comment]
@bobbyrullo woo, thanks!

**Comment by bcwaldon** [comment]
For reference: https://github.com/coreos/dex/pull/164
