### ISSUE TITLE
register?

### ISSUE THREAD

**Issue by tony-kerz** [coreos/dex#169]
so, i followed the [getting started instructions](https://github.com/coreos/dex/blob/master/Documentation/getting-started.md).

i am looking to set up an internal oauth2-provider, so i commented out the google stuff from `$DEX_CONNECTORS_FILE` and am using `"type": "fake"` in the `emailer.json` file

so, when i clicked the `register` link, i am presented with this:
<img width="504" alt="screen shot 2015-10-31 at 10 13 39 am" src="https://cloud.githubusercontent.com/assets/1223231/10864084/713528c6-7fb8-11e5-8ba5-f382021b83fc.png">

i was expecting to be taken down a registration flow where i enter basic user info, and am maybe sent an email for confirmation, did i set something up wrong?

**Comment by polvi** [comment]
You need to add the flag `--enable-registration=true` to `dex-worker`.

**Comment by tony-kerz** [comment]
thanks alex, that worked. 

i guess maybe this issue could be converted to a suggestion to call that out in the documentation somewhere?
