### ISSUE TITLE
display warning messages for non-TLS redirects

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#18]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Wednesday Feb 11, 2015 at 22:36 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/197_

---

"If TLS is not available, the authorization server SHOULD warn the resource owner about the insecure endpoint prior to redirection (e.g., display a message during the authorization request)."

https://tools.ietf.org/html/rfc6749#section-3.1.2.1

**Comment by ericchiang** [comment]
I'm ambivalent about a warning page because users will probably just click through them. We should probably just enforce HTTPS only redirects and allow admins to turn this off through an `Insecure` config option.

Closing for now.
