### ISSUE TITLE
login screen renders double output

### ISSUE THREAD

**Issue by sym3tri** [coreos/dex#180]
Steps to reproduce:
- try to login with gmail
- dex says: try registering with gmail
- register with gmail
- get crazy double-rendered screen as output that displays 2 errors: "There was an error processing your request", and "That email is already in use; please choose another".

I think this may be b/c I have a local user already by that email, and somehow during the series of steps above a response is written to a responsewriter and the function doesn't return afterwards.

**Comment by ericchiang** [comment]
This is what I'm seeing.

* Register with email
* Attempt to login with gmail and get bounced back to the dex worker

![screenshot from 2015-12-21 17-22-35](https://cloud.githubusercontent.com/assets/2342749/11945711/9aad02ba-a807-11e5-83f9-e89311ca035a.png)

* Fill out my email

![screenshot from 2015-12-21 17-22-42](https://cloud.githubusercontent.com/assets/2342749/11945722/b213529c-a807-11e5-8d6e-0a6df72121fe.png)

* Fill out email again

![screenshot from 2015-12-21 17-22-57](https://cloud.githubusercontent.com/assets/2342749/11945730/c2a59796-a807-11e5-97f6-525c29422316.png)

**Comment by ericchiang** [comment]
I've not been able to reproduce this bug before or after merging #242. Closing for now. Please reopen if this hasn't been fixed.
