### ISSUE TITLE
api: can't resend an invite email

### ISSUE THREAD

**Issue by joeatwork** [coreos/dex#184]
For administrators and user management tooling - it would be useful for administration clients to be able to stimulate invitation, email verification, and password reset messages, for example when the original messages are spam filtered or dropped.

**Comment by ericchiang** [comment]
@joeatwork like a "resend invitation" endpoint?

**Comment by joeatwork** [comment]
YES. The use case is
- Administrator signs up Joe, doesn't tell Joe
- Invitation email goes to spam filter, is deleted
- Administrator contacts Joe, they work it out, Joe fixes his filter
- Process crash

**Comment by bobbyrullo** [comment]
+1 for resend invitation - the other ones actually exist already.

**Comment by ericchiang** [comment]
Does calling the API endpoint to send an email a second time not work? It seems like that would be a good behavior for the API.

Some of the work we're going to have to do for #201, specifically [bobby's comment](https://github.com/coreos/dex/issues/201#issuecomment-165921459), might help enable this workflow.

Ask for invite email to be sent
  * If a user with a remote connector exists, say "this user already exists"
  * If a user with no remote connector exists just resend the email
  * If there is no user, create it with no remote user and send the email

**Comment by joeatwork** [comment]
That could work! We might also want to pull the "send invite" email out from "create user", so that create user would never send an email. That might make the code simpler, and the behavior simpler for callers to predict.
