### ISSUE TITLE
Implement full OIDC dynamic client registration spec

### ISSUE THREAD

**Issue by chancez** [coreos/dex#186]
http://openid.net/specs/openid-connect-registration-1_0.html

Dex supports dynamic client registration but does not implement much of the oidc dynamic client registration spec specifically. It would be great if we ensured we actually conform to the spec, as well as provide some of the optional features in it, as they could be useful for us.

Things which we can benefit from by implementing this:

- Initial bearer tokens allow having open client registration, but restrict registration to those with a pre-shared bearer token (could host public Dex, have another system which provides these tokens to register against public Dex)
- Access Tokens allow clients to perform subsequent operations upon the Client registration (like modifying the registered callback URLs, or other settings)
- Provide logo URL and client name in registration (would solve https://github.com/coreos/dex/issues/110 using the existing spec)
- Support expiring client registrations (great for temporary clients, or more ephemeral clients)

Plus potentially more.

**Comment by ericchiang** [comment]
This has largely been finished with #267. We're still working on how to expose it to end users, but the logic is there.

**Comment by hutchisr** [comment]
Why on earth was this closed when it's still unimplemented 11 years later?

**Comment by nabokihms** [comment]
@hutchisr sounds like a rhetorical question. There are other issues for this topic, so we probably do not need one more. Dex, as of today, does not support [RFC7591](https://datatracker.ietf.org/doc/html/rfc7591) (which it could), but supports dynamic client registration with gRPC API https://dexidp.io/docs/configuration/api/
