### ISSUE TITLE
dexctl: force rotate keys

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#19]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Wednesday Apr 01, 2015 at 17:22 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/205_

----

After https://github.com/coreos-inc/auth/pull/204 keys are only rotated if needed by the overlord on startup. We need a panic button to force rotate keys immediately.

**Comment by ericchiang** [comment]
Since we set cache-control headers on public keys there's no way to force clients to update their keys so this seems like it wouldn't achieve the intended goal.
