### ISSUE TITLE
example-app: email link produces error

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#194]
Steps to reproduce

1. Start dex-worker and example-app
2. Register with email
3. Follow link produced
4. Page returns 400 with `{"error":"code query param must be set"}`

However I can now login just fine.

**Comment by joeatwork** [comment]
I suspect this is due to interface rot - when you followed the link, were you given the opportunity to change your password? Or did the link fail immediately?

**Comment by ericchiang** [comment]
Failed immediately

**Comment by bobbyrullo** [comment]
@ericchiang - was this with a --no-db setup?

**Comment by ericchiang** [comment]
@bobbyrullo this was. Will test with a database when I get a sec.

**Comment by ericchiang** [comment]
same thing with the database

**Comment by bobbyrullo** [comment]
uggh. Saw that you self-assigned - thanks for looking into it. Let me know if you get stuck or have any questions.

**Comment by ericchiang** [comment]
The redirect dex generates after verifying an email address is missing a `"code"` query parameter for the client (example-app) to exchange for a token. It's just the following:

```
Location:http://127.0.0.1:5555/callback
```

Here's the code associated with creating that callback URL in [`server/email_verification.go`](https://github.com/coreos/dex/blob/cec3cd44510a13b5d607c3028470960b69bfb15e/server/email_verification.go#L218-L245).

```go
ev, err := user.ParseAndVerifyEmailVerificationToken(token, issuer, keys)
if err != nil {
	...
}

cbURL, err := userManager.VerifyEmail(ev)
if err != nil {
	...
}
...
http.Redirect(w, r, cbURL.String(), http.StatusSeeOther)
```

So either `userManager.VerifyEmail` is not constructing the URL properly, or we need to generate a authorization code token before responding with a redirect.

**Comment by bobbyrullo** [comment]
closed in favor of https://github.com/coreos/dex/issues/229
