### ISSUE TITLE
connector: make underlying http.Transport swapable

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#196]

**Comment by bobbyrullo** [comment]
can you add a little more context here? Which http.Transport? And Why?

**Comment by ericchiang** [comment]
All the connectors use the default http.Transport (and default http.Client). Was brought up that if we ever need to configure custom TLS settings, proxy envs, timeout values, etc., in the future this would have to be configurable.

Might have opened this issue preemptively. Since this doesn't address a specific problem, going to close it.
