### ISSUE TITLE
Request for guidance - Authenticating a trusted native app

### ISSUE THREAD

**Issue by Brahmasmi** [coreos/dex#225]
Use case: Authenticate an end-user using a native client application, which is built by the same organization as that running the dex server, and is thus trusted. Additionally, the native application is a public client since it cannot securely store its client credentials. As an example, consider an android app built by coreos authenticating with coreos' dex in the local connector configuration.

Given this context, what would be the recommended way to accomplish authentication of an end-user using a trusted native app?

Thinking aloud:
One approach is to use the Resource Owner Password Credentials Grant flow in OAuth 2.0 (https://tools.ietf.org/html/rfc6749#section-4.3). Based on my very limited understanding, this would provide the end-user a native UI with a username and a password field and interact with dex's token endpoint directly. On the token endpoint side, instead of receiving an authorization code, the endpoint will get a username and a password. On success, the endpoint will return an id token, an access token and a refresh token. I am not sure, but I think this is referred to as two-legged OAuth.

**Comment by ericchiang** [comment]
This sounds like the OIDC [implicit flow](http://openid.net/specs/openid-connect-core-1_0.html#ImplicitFlowAuth) (though I admittedly have very little experience with native client apps):

> The Implicit Flow is mainly used by Clients implemented in a browser using a scripting language. The Access Token and ID Token are returned directly to the Client, which may expose them to the End-User and applications that have access to the End-User's User Agent. The Authorization Server does not perform Client Authentication.

I don't think dex currently supports this. It's not that its design prevents implicit flow support, but CoreOS doesn't use that flow internally so it's not been tested.

It's not on the immediate roadmap, though we'd love to see dex support this.

**Comment by Brahmasmi** [comment]
I am not an expert on this, so please bear with me. I may be wrong here, but I think that the implicit flow probably may not be the solution.

Based on my very limited understanding, the OIDC implicit flow seems to map to the OAuth 2.0 Implicit Grant type (https://tools.ietf.org/html/rfc6749#section-4.2). This flow is specifically for clients implemented in a browser.

This graphical overview (http://openid.net/specs/openid-connect-implicit-1_0.html#Overview) helps us understand the flow. For brevity, I am omitting the step descriptions, please refer to them via the previous URL. In the flow, the step (2) is an interaction between the End-User and the OP via a browser in which the OP first authenticates the end-user and then obtains authorization from the end-user to grant access to the RP (client). The steps (1) and (2) involve redirections - something that only a browser can accomplish.
```
+--------+                                   +--------+
|        |                                   |        |
|        |---------(1) AuthN Request-------->|        |
|        |                                   |        |
|        |  +--------+                       |        |
|        |  |        |                       |        |
|        |  |  End-  |<--(2) AuthN & AuthZ-->|        |
|        |  |  User  |                       |        |
|   RP   |  |        |                       |   OP   |
|        |  +--------+                       |        |
|        |                                   |        |
|        |<--------(3) AuthN Response--------|        |
|        |                                   |        |
|        |---------(4) UserInfo Request----->|        |
|        |                                   |        |
|        |<--------(5) UserInfo Response-----|        |
|        |                                   |        |
+--------+                                   +--------+
```
On the other hand, the Password flow via a native app would be like this (https://tools.ietf.org/html/rfc6749#section-4.3).
```
     +----------+
     | Resource |
     |  Owner   |
     |          |
     +----------+
          v
          |    Resource Owner
         (A) Password Credentials
          |
          v
     +---------+                                  +---------------+
     |         |>--(B)---- Resource Owner ------->|               |
     |         |         Password Credentials     | Authorization |
     | Client  |                                  |     Server    |
     |         |<--(C)---- Access Token ---------<|               |
     |         |    (w/ Optional Refresh Token)   |               |
     +---------+                                  +---------------+
```
The client is given the end-user credentials and as such has complete access to the end-user credentials. The client in turn presents these credentials to the OP, which responds with the relevant tokens.
This client-accessing-credentials part is important because I suppose the client not being able to access the credentials is probably a goal of the openid specification. However, in this case, I suppose it is ok because the client is trusted. Trusted because it is built by the same organization as the OP. However, it is also public, because it cannot securely store its client credentials.

**Comment by ericchiang** [comment]
We don't have plans to add resource owner password grants. Closing this for now.
