### ISSUE TITLE
Create swagger documentation for APIs

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#230]

**Comment by ericchiang** [comment]
closing in favor of #245

**Comment by ericchiang** [comment]
Reopening. As has been brought up in #73 we badly need documentation for dex's APIs. And using swagger seems much more straightforward than #245.

Goals:
* Use [swagger2markup](https://github.com/Swagger2Markup/swagger2markup) to generate HTML docs similar to what [k8s](https://github.com/kubernetes/kubernetes/tree/master/hack/gen-swagger-doc) does.
* Consider using [go-swagger](https://github.com/go-swagger/go-swagger) to generate server stubs for API.

**Comment by sym3tri** [comment]
may want to wait for swagger 3.0

**Comment by bobbyrullo** [comment]
gonna close this for now
