### ISSUE TITLE
proposal: adding support for pluggable backends

### ISSUE THREAD

**Issue by sercand** [coreos/dex#254]
This issue created as discussion thread of #253. Dex supports only postgres and different storage backends have been requested before on issues like #200 and #115. Therefore, I have created a basic pluggable driver system for dex. Since dex uses abstraction (for example RefreshTokenRepo and ClientIdentityRepo interfaces) to connect db backend, it is quite easy to add a new storage driver.

**Comment by ericchiang** [comment]
Thanks for opening this!

Couple of initial thoughts.

On the general idea of backends. It's already a huge amount of effort to ensure changes are compatible and backwards compatible with Postgres (migrations, [tricky corners](https://github.com/coreos/dex/issues/247), etc). Additional backends increases the overhead of adding features dramatically.

dex is in the middle of [heavy development](https://github.com/coreos/dex/blob/master/Documentation/roadmap.md), and it's a hard pitch ATM to bog down the roadmap writing and testing CRUD code for additional backends. These changes might be better suited once dex has settled down a little bit.

This being said I like the idea of defining a driver interface like in #253 (though I'm against change CLI flags to accommodate this). I think it's a good refactoring decision as it makes the DB's various sub repos much more obvious.

But again, if the ultimate goal is adding backends, are their storage options with enough demand that we're willing to do the work to support them?

**Comment by ericchiang** [comment]
p.s. - @sercand I think the etcd backend implementation is terrific! But I'm probably also the guy who's going to have to make sure it works with everything new feature for the foreseeable future :)

**Comment by sercand** [comment]
I think no need to add extra storage backend to master dex, because it is currently under development. But adding support to pluggable storage backend would be really nice and it will actually make things easy. So I think dex should support adding storage backends but it should't have extra backend on original repo for now.
I have started to implement mongodb and etcd storage backends but not with the purpose of merge with the original repo. Although mongodb is almost finished, it does not feel right and there are some many issues with it. Also, etcd backend is using v2 api and I have found out that there is a v3 grpc api after couple of hours. Therefore I quit to make an etcd backend.

**Comment by ericchiang** [comment]
Sounds good.

Yes I don't want to mess with something that fundamentally doesn't support transactions.

I do like the idea of having a central driver like you proposed in the pull request.

```go
//Driver is interface for backend storages
type Driver interface {
	//Name returns name of driver
	Name() string
	NewConnectorConfigRepo() connector.ConnectorConfigRepo
	NewClientIdentityRepo() client.ClientIdentityRepo
	NewSessionRepo() session.SessionRepo
	NewSessionKeyRepo() session.SessionKeyRepo
	// etc...
}
```

At the very least it's a good way of documenting all the places our database implements functionality. And might, for instance, help with the "use transactions everywhere" effort.

If we can distill this change down to that, then I might be on board.

What say you @bobbyrullo?

**Comment by bobbyrullo** [comment]
yes, that sounds like a good idea. As you're putting a new PR together: please don't change the flags (eg. don't remove --no-db) around more than strictly necessary, and please keep commits small (the smaller the better!) and targeted (the smaller the scope the better!) and follow the commit format in our Contributing file. 

Thanks @sercand

**Comment by ericchiang** [comment]
Documentation for the new storage can be found here[0]. Would be happy to add new storages for etcd and mongodb. Closing for now since I think the initial concerns have been properly addressed.

[0] https://github.com/coreos/dex/blob/master/Documentation/storage.md
