### ISSUE TITLE
Don't load PasswordInfos when using DB

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#26]
<a href="https://github.com/bobbyrullo"><img src="https://avatars.githubusercontent.com/u/9629?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bobbyrullo](https://github.com/bobbyrullo)**
_Friday Jun 12, 2015 at 16:46 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/253_

----

**Comment by ericchiang** [comment]
@bobbyrullo could you elaborate a little more on this one?

**Comment by ericchiang** [comment]
closing as dup of #286 (since it has more details)
