### ISSUE TITLE
feature: revoking refresh tokens

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#261]
Notes:

OAuth2.0 spec provides an example with basic auth.

> The client constructs the request by including the following parameters using the "application/x-www-form-urlencoded" format in the HTTP request entity-body:

```
POST /revoke HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

token=45ghiukldjahdnhzdauz&token_type_hint=refresh_token
```

Google provides [similar examples](https://developers.google.com/identity/protocols/OAuth2WebServer?hl=en#tokenrevoke):

>To programmatically revoke a token, your application makes a request to https://accounts.google.com/o/oauth2/revoke and includes the token as a parameter:

> curl https://accounts.google.com/o/oauth2/revoke?token={token}

> The token can be an access token or a refresh token. If the token is an access token and it has a corresponding refresh token, the refresh token will also be revoked.

> If the revocation is successfully processed, then the status code of the response is 200. For error conditions, a status code 400 is returned along with an error code.

Salesforce has a similar [endpoint](https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_revoke_token.htm&language=en).

The API driven revocations I've been able to find are for the OAuth client. End users generally revoke access through web forms like this:

![oauth2revoke](https://cloud.githubusercontent.com/assets/2342749/12213198/3de6c2e8-b629-11e5-89c3-44d199d92e6a.png)

Seems reasonable to add a revoke endpoint for clients like the one specified in the [OAuth2.0 token revocation spec](https://tools.ietf.org/html/rfc7009). Maybe we should consider different endpoints to cover other kinds of situations?

**Comment by ericchiang** [comment]
cc @bobbyrullo, @sym3tri 

# Proposal: revoking refresh tokens

## Motivation:

1. Need a way for users to revoke client's access to their identity.
2. Users never see the refresh token issued to clients. Can't just say "revoke this token."
3. Need a way for as user to "login to dex" and revoke a client.
4. Want to force as little UI as possible onto projects using dex (#255). Things should be API driven.

## Proposal:

* Add new API endpoints that allow any user to see what clients they're logged into and revoke access.
* Have this API require logging in through an "admin" client.
* Generate a client id and secret for dex to use to "login to itself" so it can access this API.

## Details:

### Overview of APIs

dex's APIs currently fall into some combination of client + user. For instance the existing *User API* requires admin user to be logged into an admin client.

Here are the existing APIs with a suggested addition for revokation tokens.

| | admin user | user | no user |
|:---|:---|:---|:---|
| admin client | user management (user API) | account management (revoke tokens) | |
| client | | user info (OIDC core) | client registration |
| no client | | | bootstrapping (admin API) |

Note: we need better names for these

### API for revoking refresh tokens

Any user logged into an admin client should be able to:

* Get a list of clients they're logged into.
* Be able to revoke any refresh token for an individual client.

This would also be a good API for allowing users to disable themselves (#228)

### dex as a client of itself

In the future, dex may want to be able to perform account management through its own UIs. To accomplish this, dex would create a well-known client id (probably "dex") and client secret for itself. This client would be an admin and allow it to access the proposed API endpoints.

This would be optional and allow projects to implement their own UIs and drive account management through a different client.

## Steps:

1. Merge #285 - need API documentation before adding more endpoints
2. Merge #267 - need updated client structs
3. Add refresh token APIs
4. (Maybe) Implement "dex as client of dex" and UI for token revocation

**Comment by bobbyrullo** [comment]
Sounds like a plan!

**Comment by rsoletob** [comment]
#35

**Comment by ericchiang** [comment]
This has been added to the API, so I'm modifying the milestone to 0.5

**Comment by chris-rock** [comment]
In addition to that we may think about access token revocation, too.  As defined in https://tools.ietf.org/html/rfc7009

```
POST /revoke HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

token=45ghiukldjahdnhzdauz&token_type_hint= access_token
```

For access token, we could just store the revoked access tokens in db until they are expired. dex-overlord could clean up the table regularly.

**Comment by ericchiang** [comment]
The API for this proposal is done. Going defer additional work for another issue.
