### ISSUE TITLE
tests: failed tests are too verbose

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#264]
Right now one failed test nukes your console with server logs. Much of this is irrelevant and it's really hard to figure out what's actually failing. Reduce verbosity when tests fail.?

Edit: see example [here](https://gist.githubusercontent.com/ericchiang/38bffbc7b389f52df543/raw/386f80c2ae8b8a2b8f6f93a147bba37a2258b0a5/dex_failed_test.txt)

**Comment by bobbyrullo** [comment]
When tests fail I want lots of verbosity - thats how I debug! you can try running one test at a time or something.

**Comment by joeatwork** [comment]
Right now, you get lots of verbosity from all of the tests - not just the ones that failed - so it's hard to find the verbosity that you want. Maybe it'd be nice to be able to toggle away the texts of emails or HTML pages when a test goes awry?

**Comment by ericchiang** [comment]
To add to @joeatwork. For a lot of tests it's impossible to know if a logging statement came from a case that was expected to fail or from the one case that wasn't supposed to.

**Comment by joeatwork** [comment]
One way to have our cake and eat it too here might be to run case-based tests one "test" at a time rather than in a loop - sometimes if the third of 20 test case failed you can't just run the failing case. Maybe super-verbose but per-case tests might be a win for all?

**Comment by bobbyrullo** [comment]
Ah you are all talking about *cases* of tests. If there were a clever way to do what @joeatwork suggested that would be brilliant.

Maybe something like

```
tests := { lots of tests}
for i, t := testutil.Cases(tests){
  test stuff
}
```

and inside of testutil.Cases:
```
if os.GetEnv("TEST_RUN_CASE"){
   return []string{ stringToInt(os.GetEnv("TEST_RUN_CASE"))}
} else {
   return range(tests)
}
```

**Comment by ericchiang** [comment]
> Maybe it'd be nice to be able to toggle away the texts of emails or HTML pages when a test goes awry?

I will note that a majority of the logs are HTML pages. For #282 I removed log statements that dumped HTML pages and went from something that ate up all of my terminal scrollback to [something reasonable](https://gist.github.com/ericchiang/a717cf85061e0fc6d772).

> ```
tests := { lots of tests}
for i, t := testutil.Cases(tests){
  test stuff
}
```

Each test has a unique type so`Cases` would have to return `[]interface{}` and use reflect. Or we'd do something like this.

```go
tests := [lots of tests]
for i, t := range tests {
  if testutil.SkipCase(i) {
    continue
  }
  // test stuff
}
```

**Comment by ericchiang** [comment]
Closing for now. This is still an issue, but can be addressed as individual cases arise.
