### ISSUE TITLE
base64 decoding error concealed

### ISSUE THREAD

**Issue by colhom** [coreos/dex#270]
https://github.com/coreos/dex/blob/master/db/client.go#L241

I would do a quick PR, but I don't know if it's better to return a compound error message from `Authenticate()`, or to just log in the base64 decode error as well and still return `false,nil`

**Comment by ericchiang** [comment]
I think that code is handling the error by logging it in the spirit of the [interface it's implementing](https://github.com/coreos/dex/blob/b5c7f1978e0718d9631e512c385eb0dea99b732d/client/client.go#L30-L34).

```go
type ClientIdentityRepo interface {
	...

	// Authenticate asserts that a client with the given ID exists and
	// that the provided secret matches. If either of these assertions
	// fail, (false, nil) will be returned. Only if the repo is unable
	// to make these assertions will a non-nil error be returned.
	Authenticate(creds oidc.ClientCredentials) (bool, error)

	...
}
```

Do you have a dex instance that's hitting an error with base64 decoding?

**Comment by colhom** [comment]
Yes, but it was my own fault and has since been rectified. It simply says `error Decoding client creds`.

I think I may be missing something with this. If [`base64.URLEncoding.DecodeString(creds.Secret)`](https://github.com/coreos/dex/blob/master/db/client.go#L241) returns an error, that error message is never printed/reported. If that's true, we should fix that.

**Comment by ericchiang** [comment]
To be fair `DecodeString` returns exactly [one type of error](https://golang.org/pkg/encoding/base64/#CorruptInputError), but yeah it probably should be printed.

**Comment by colhom** [comment]
The message includes what byte in the stream it encountered a problem at. Not widely useful, but definitely worth printing.
