### ISSUE TITLE
clean up server code

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#278]
This came up during code review of #267. Server code needs to be better organized and have more established idioms for responding to requests.

**Comment by ericchiang** [comment]
This is my initial proposal for providing a standard API response writer: https://gist.github.com/ericchiang/4928eb02991f9e4afaa5

TL;DR define a package with the following types and user them for handlers.

```go
pakcage api

// ...

// RegisterError associates an generic error with an api.Error.
//
// If RegisterError is called twice with the same error it panics.
func RegisterError(err error, apiErr api.Error) {
	// logic
}

type ResponseWriter interface {
	// Write is a convenience method for calling WriteResponse with a 200 status code.
	Write(v interface{})

	// Write JSON encodes an error an writes it to the response body.
	//
	// If err is of type api.Error, it is written. If the error has been registered
	// with api.RegisterError, the associated api.Error is written. If neither of
	// these conditions hold, the error is logged and an internal server error is
	// written.
	WriteError(err error)

	// WriteResponse JSON encodes the provided object and writes it to the response
	// with the provided status code.
	WriteResponse(v interface{}, status int)
}

type Handler func(ResponseWriter, *http.Request)

func (h Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h(&responseWriter{w}, r)
}
```

**Comment by ericchiang** [comment]
Note. Another addition will be to add a storage interface to abstract away the DbMap.

For example

```go
type Storage interface {
    GetClientRepo() client.ClientIdentityRepo
    ...
}
```

This would clean up anything that needed access to a repo.

```go
type AdminAPI struct {
    localConnectorID string
    storage          repo.Storage
}
```

**Comment by ericchiang** [comment]
Note that the `Storage` interface was brought up in #254 and will be a necessary step for that issue.

**Comment by bobbyrullo** [comment]
let's have these all be separete things, or else I am afraid it will never get dealt with.

**Comment by ericchiang** [comment]
Closing this one. The server package is still messy, but I don't think this proposal addresses it correctly. Will reopen if I think of a more direct plan of attack.
