### ISSUE TITLE
Make it easier to provide admin user passwords

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#28]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Friday Jun 12, 2015 at 18:56 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/256_
---

Creating users with the overlord API accepts password hashes only, but there is no utility provided to hash the password. We should make things easier on the user and allow them to post plaintext password and/or provide a utility to create a hash from a plaintext password.

**Comment by LEW21** [comment]
Bootstrapping API is unfortunately useless without this feature.

**Comment by ericchiang** [comment]
passwords can now be provided statically.
