### ISSUE TITLE
Allow preserving users across clean-slate reconfigurations

### ISSUE THREAD

**Issue by joeatwork** [coreos/dex#292]
I'm working with a fairly complex Dex integration (that is configured indirectly) and often we want to erase or re-initialize the initial configuration. This is pretty easy - just drop the underlying database and you're good to go. Unfortunately, this also deletes all of the user accounts and registrations associated with dex. It would be nice to be able to get a clean slate wrt. config and not lose the users. This could be a script, separating out the DBs, or just a bit of documentation.

@bobbyrullo and @ericchiang please review and close if this sounds wacky.

**Comment by ericchiang** [comment]
What are the actual things that you need to reset? Some user information is, for instance, tied to connectors so this might require us to re-associate user passwords and such later.

**Comment by joeatwork** [comment]
The example that motivated me posting this issue is a DNS change that broke client callbacks, etc. While this is something that admins could change directly in a simple dex install, in my case I'm installing dex and other software, and orchestrating shared secrets and such automatically in a distributed environment. I can just restart the other services in this environment and they take up new configuration, etc, but if I kick my dex process it'll come back with old/stale configs.

At a high level, it would be nice to be able to (for example) replace a configuration file and have most things done, and still not lose the non-configuration state of the system.

**Comment by ericchiang** [comment]
You can now statically define users, so I'll consider this requests filled.
