### ISSUE TITLE
add http cache headers for endpoints

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#3]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Friday Nov 14, 2014 at 20:13 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/52_

----

and update client to use them

**Comment by ericchiang** [comment]
We do provide "Cache-Control" headers for the discovery and keys endpoints.
