### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by ekarlso** [coreos/dex#303]
Hi, is there plans for CORS support so it's usable with SPAs ?

**Comment by philips** [comment]
@ekarlso We can certainly do that. Do you have a single page app example that uses OIDC so we can test against it once we add support?

**Comment by philips** [comment]
If someone wants to work on this I think we should consider using the gorilla CORs handler. We use it in other projects IIRC. https://github.com/gorilla/handlers

**Comment by ekarlso** [comment]
http://pastebin.com/wJ9fZed0 - it's not gonna work without at least :)

**Comment by janekolszak** [comment]
Yeah, +1

**Comment by philips** [comment]
WIP branch herehttps://github.com/philips/dex/commits/add-cors

**Comment by philips** [comment]
If someone sees what I am doing wrong there let me know

**Comment by bobbyrullo** [comment]
@philips we moved priority to p2; we can discuss offline if you think it should be otherwise.

**Comment by ekarlso** [comment]
Is there any news on this?

**Comment by ericchiang** [comment]
We're not working on this but would be happy to review an implementation. Would be very important for this to be turned off by default.

**Comment by ericchiang** [comment]
Since the API now uses gRPC instead of HTTP, I don't think CORS is appropriate. Closing.

**Comment by pborzenkov** [comment]
Any chance CORS support still can be added to dex?
Without CORS it's impossible to authenticate using dex from a javascript app.
For example, swagger-ui supports OAuth2 authorization, but it can't be used with dex directly.

**Comment by ericchiang** [comment]
I was under the impression that this PR was asking to hit the API, not perform OAuth2 flows. Plus the implicit flow (which can be turned on) allows you to perform auth without a code for token exchange. Shouldn't that be what frontend only apps should be using?

**Comment by pborzenkov** [comment]
@ericchiang We haven't yet moved from dex v1 to v2. We will definitely need to do this in the future, anyway. In this case, we will switch to implicit flow for JS app.
So, yeah, probably there is no point in adding CORS to dex v1 and it's not required for dex v2.

**Comment by xeonx** [comment]
@ericchiang In order to perform oauth2 with implicit flow, I agree that CORS is not required.
I think that for open-id connect discovery it could be usefull to allow CORS on GET request for .well-known/openid-configuration
If you agree on the need, I may try to make a PR (with off by default, configurable CORS support on this single path, using gorilla CORS handler ).

**Comment by ericchiang** [comment]
> I think that for open-id connect discovery it could be usefull to allow CORS on GET request for .well-known/openid-configuration

Yeah that sends totally reasonable. Feel free to send a PR.

**Comment by fabiohecht** [comment]
Lately, the implicit grant has been discouraged in favor of authorization code. Allowing CORS config for the token endpoint would make sense in my opinion.
