### ISSUE TITLE
LDAP connector: implement connection pooling

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#309]
The LDAP connector implemented in #178 creates a new LDAP session for every request, closing and discarding the connection after login.

Add connection reuse to the existing logic. After attempting to login, connections should be:
* "reset" by binding anonymously
* kept alive by occasionally pinging the LDAP server (or discarded if this fails)
* reused on future login attempts by other dex end-users

**Comment by philips** [comment]
@ericchiang @fnordahl can one of you flesh the description out further?

**Comment by fnordahl** [comment]
@philips I do not have access to edit the description of this issue, but I have fleshed out the description for the PR. Cc @ericchiang

**Comment by ericchiang** [comment]
:+1: updated here

**Comment by fnordahl** [comment]
thx!
