### ISSUE TITLE
idea: declarative token validation

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#31]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Tuesday Jun 30, 2015 at 19:45 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/281_
---

I've encountered jwt claim parsing/validation code very frequently. Just an idea, but maybe we create a generic way to declaratively "validate" tokens by ensuring a set of claims/values. I kinda want a function I can call like:

``` go
var (
  ErrorClaimMissing = ...
  ErrorClaimMatchFailure = ...
  ErrorClaimCheckInvalidType = ...
  ...
)

type ClaimCheck struct {
  name string
  value interface{} // must be a supported claim type
}

wantClaims := []ClaimCheck{
  // no value, just checks for existence
  ClaimCheck {
    name: "email",
  },
  // existence & equality check
  ClaimCheck {
    name: "aud",
    value: "some-clien-id",
  },
}

valid, err := jwt.HasExpected(wantClaims)
...
```

Thoughts?

**Comment by ericchiang** [comment]
Dex no longer does any ID Token validation. Would be better for go-oidc.
