### ISSUE TITLE
Allow to denormalize Users even further

### ISSUE THREAD

**Issue by thedrow** [coreos/dex#311]
Dex would integrate better with other systems if it only saved only the user's Id and interact with another REST API to fetch the information about the user.

**Comment by ericchiang** [comment]
Sorry this is a little vague so I'm having trouble following. Do you have an example you could provide?

**Comment by thedrow** [comment]
User data is often stored elsewere.
If I want to check if the user's email has been verified it is not the responsibility of Dex to provide that information. It's the users microservice's responsibility.
Instead, we need to provide a REST contract for fetching and updating user data and require the users to implement it. We can add HTTP caching support on our side to ensure we're not doing too much work.
The contract itself can be configurable so that the mapping between the User model and the REST API will always be in par with existing APIs.

**Comment by ericchiang** [comment]
You're using the word "user" in a couple different ways so I apologize if I'm misinterpreting.

> If I want to check if the user's email has been verified it is not the responsibility of Dex to provide that information. It's the users microservice's responsibility.

dex is an [OpenID Connect](https://openid.net/developers/specs/) identity provider. As per that spec, the authentication information returned by providers includes if an email has been verified, so this has to be dex's responsibility.

> Instead, we need to provide a REST contract for fetching and updating user data and require the users to implement it. We can add HTTP caching support on our side to ensure we're not doing too much work. The contract itself can be configurable so that the mapping between the User model and the REST API will always be in par with existing APIs.

dex's contract with clients is OpenID Connect.

I'd really suggest looking into OpenID Connect and other OAuth2 providers. If there are specific things you're concerned about like "it would be helpful to have an API endpoint to revoke clients"  or "dex should be able to use a different store for session data" we're happy to address those. But it's hard to understand exactly what your proposing here.

**Comment by thedrow** [comment]
I'm not familiar with OpenID. I am the maintainer of [OAuthlib](https://github.com/idan/oauthlib) though.
This issue is about where data about a system's users are stored.
Usually there is already a table of users that is stored in another database. I'll use a concreate example here.
Let's say we have a Django application. Django already provides a User model for us to extend and the email is stored there. If I need to know if the email was verified in order to display a message to the user should I ask Dex or my own users table?
Is there an API on Dex's side to do such a thing?

That also applies to disabling users or their creation date.

**Comment by thedrow** [comment]
What I'm saying is that you don't need to store the User's table at all. You just need to cache the information you need from the user's table that is defined externally.

**Comment by ericchiang** [comment]
> What I'm saying is that you don't need to store the User's table at all. You just need to cache the information you need from the user's table that is defined externally.

dex isn't just a oauth2 proxy, it's an identity provider. Supporting username and password logins, and many features in the future (such as groups and merging multiple identities) require this table.

**Comment by bobbyrullo** [comment]
Dex is it's own first class IDP, like @ericchiang said. As far as an API for knowing if the email is verified, when a client app (or Relying Party in Open ID Connect parlance) gets the ID token, there's an email verified claim in the JWT you can check.

**Comment by thedrow** [comment]
So we should store user credentials and some other data in dex instead of the app's own user model?

**Comment by ericchiang** [comment]
> So we should store user credentials and some other data in dex instead of the app's own user model?

Yes. Let dex handle authenticating your users (email, passwords, etc.), your app consumes the identity via oauth2 + OpenID Connect, then associates data with the ID retrieved through that process.
