### ISSUE TITLE
Optionally encrypt tokens and secrets at rest using pgcrypto

### ISSUE THREAD

**Issue by thedrow** [coreos/dex#312]
If pgcrypto is installed on the Postgres database we should allow to use it to encrypt all tokens and secrets. That way if a data breach occurs we won't need to refresh all the tokens and secrets unless the encryption key itself has leaked.

**Comment by ericchiang** [comment]
I'm not familiar with pgcrypto but it doesn't seem to provide anything we can't do already within Go. Is there advantage to using a database side implementation?

**Comment by thedrow** [comment]
Sometimes, yes. There are security advantages for offloading the encryption to the database server. See http://stackoverflow.com/questions/9326264/is-there-some-security-advantage-to-using-pgcrypto-instead-of-partition-level-en
Also there are practical use cases for pgcrypto which may or may never apply here.
If you need the unencrypted value in a stored procedure it's easier to just pass the encryption key as a parameter to the stored procedure instead of SELECTing the value, decrypting it and then passing it over the wire to the stored procedure.
pgcrypto can also help increasing resource utilization of the database server and offload encryption and decryption from the busy OAuth server. That means better that dex will scale better as long as your database is up for the task.
If we implement this feature, we probably want to have the database compare the token/secret to the value in the database so we'll need stored procedures. In that case see point number 1.

There are disadvantages though. Lookups on secrets cannot be indexed or constrained.
You can workaround this issue by storing the hash of the secret as well. See http://stackoverflow.com/questions/27997514/postgresql-primary-key-constraint-on-encrypted-data-using-pgcrypto-extension
Preferably using bcrypt which is supported by pgcrypto.
Since we're sending the encryption key to the database, TLS connections are a must which will slow down request throughput. However, since we're dealing with sensitive data here I argue that this must be required by dex anyway in order to avoid leakage of secrets over the wire in case someone is listening (To the NSA agent who is probably reading this: Yo! What's up man?). So in this very specific case, it's a no brainer.
If you don't seperate you're authorization tables from the rest if your data you may not want to use database-side encryption since it will reduce the database throughput. This is why pgcrypto is optional.
We should create a new issue about optional client side encryption for cases like this.

I recommend seperating the databases anyway for security reasons. In case of the aforementioned data breach, you'll only get a list of usernames and that's it.

We should probably edit the documentation to provide the recommendations above.

So, what say you?

**Comment by ericchiang** [comment]
dex already encrypt keys using AES-GCM and passwords using bcrypt before sending them to the backend storet. The Go code already does what you're describing, so it seems odd to move this logic to the database since that's what you're worried about being breached.

**Comment by thedrow** [comment]
Are there any specific architectural arguments you are concerned about?
I specified the advantages and disadvantages and it's up for the user to decide if he requires the functionality or not.

**Comment by thedrow** [comment]
Hmm now that I read http://dba.stackexchange.com/questions/24370/how-to-use-aes-encryption-in-postgresql#answer-24379 I'm not so sure anymore.

**Comment by ericchiang** [comment]
> Are there any specific architectural arguments you are concerned about?

Yes. Again, we already implement the encryption features you're asking for (we just do it in the Go code), and database side crypto doesn't seem like a good mechanism for securing against a database breach.

**Comment by thedrow** [comment]
Well, I think I'll close this issue unitl I find a better argument for using pgcrypto.
