### ISSUE TITLE
Provide binary releases

### ISSUE THREAD

**Issue by thedrow** [coreos/dex#313]
We can use dpl and Travis and Github Releases to provide binaries for Linux and OSX.
We can also set up AppVoyer and provide binary releases for windows if the need arises (but I don't think many people want to run dex on Windows).
In any case, it will be easier to create docker containers for dex if I don't have to have a build environment inside the docker container.

**Comment by bobbyrullo** [comment]
question re: templates: use gobindata, or tar it up? Or gobindata defaults

**Comment by thedrow** [comment]
I think that both are acceptable but most users will want to customise the templates.

**Comment by ericchiang** [comment]
We're not going to provide binary releases, container releases are enough for us. We'd be open to RPMs and DEBs but that should be a different issue.
