### ISSUE TITLE
LDAP: searchBeforeAuth, entryDN does not exist

### ISSUE THREAD

**Issue by cgilling** [coreos/dex#314]
I should preface this by saying that I have very little experience with LDAP, but have been playing around with dex and trying to authenticate users against my companies LDAP server.

As I was doing this I found that the entries that were being returned did not seem to have an `entryDN` (this [line](https://github.com/coreos/dex/blob/cd72a1f69fc02b1fec29b04d3a0a173e90b9f590/connector/connector_ldap.go#L307) is returning an empty string), but if I modified the code to use `sr.Entries[0].DN` instead it would work. Is there any reason not to use `sr.Entries[0].DN` if there is no `entryDN`?

tagging @fnordahl as he wrote the connector from what I can tell.

**Comment by fnordahl** [comment]
@cgilling Thank you for your interest in dex and the LDAP connector. Could you tell me a little bit about what kind of LDAP server you are connecting to?

**Comment by cgilling** [comment]
Its an ActiveDirectory setup. Don't really know much beyond that at the moment.

**Comment by fnordahl** [comment]
Thank you for finding and reporting the issue. You are quite right about just using ``sr.Entries[0].DN``. I belive it should be fixed in PR #315 .

**Comment by cgilling** [comment]
awesome, thanks for the quick reply and fix
