### ISSUE TITLE
Worker API calls return errors

### ISSUE THREAD

**Issue by boriska70** [coreos/dex#319]
Opened following this post https://groups.google.com/forum/#!topic/dex-dev/3t0yjEXlmTw 

I have the system comprising of overlord, one worker and dex-example-webapp.
There are 2 connectors configured: local and Google but I only used local users in this flow.

I'm trying to use worker API, for example I'd like to get a list of clients or create users. 
This is my reference: ttps://github.com/coreos/dex/tree/master/schema/workerschema#clientpage

**1**. Login with the existing user via demo application and obtain the token. The examples below are for admin user with non-verified email.
**2**. Run the following rest call to worker in order to list clients (using the token I just obtained):
`curl -ivL -X GET -H "Accept: application/json" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InZjeWVfOFZwbWJoZ214bTBxRXlXSkRWUDdvaVBJODMtSDFoSEJOc29ONXdjdWttcGVJd090YXI1R29Tcmc1MzZLQ0p3UHRhdTI0d1Vpd3NvZF93bVJKYkVDX0txV1FvZGVpWnhOVjZEd2tBYWVrUlNHaWdDMm53Rm1sSndhWDJSVlg4ODFYOUZ4VDVab0g2MmdQUW4ta2lwbDRscEswanI5aFFsd21mTWxWUkdwMlEtN253X0FydDVxZUtHLXdBV0xwejZFUE94UzRMUlVFVHVDY2pMQm9HLWJBM0V4VVNjUVdERVE3aTlZQWpmN19CajFrcHA4dVgyTFJpWlZVeGFDWjNDVmdQREUxS0doUVJ6VmNRRHFBeEQ3RFJTVnlNcjRqTmNsamxOVmIxX2o3T2FSYUtsU21VN0ItYno5c0ZWY1JXejFlb3VYLXBQVGhpckhGT01MUT09IiwidHlwIjoiSldUIn0.eyJhdWQiOiJpblpYX2x2VHpfS1ppMjl3Qmc5LV9jT3BrT0xtRW9kVTJPYncyM01KN2U0PUAxMjcuMC4wLjEiLCJlbWFpbCI6Im15QGFkbWluLmNvbSIsImV4cCI6MS40NTU3MzUzMzJlKzA5LCJpYXQiOjEuNDU1NjkyMTMyZSswOSwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo1NTU2IiwibmFtZSI6IiIsInN1YiI6ImQ2ZDgzMTk1LTMwYzgtNDliMy05YWUyLTMzNmIzN2JhYzIzNCJ9.qMiuHHXprRdzM05gxE8YvJ01hXuudVFlrPfuNpiPvra6yTKh3cez4ehL2NbH2Idvtj2AVa2sgCxdqcbvsPMzFUFTsuBKxdd1ynynQAszt4L5JhuoivIS2vNI1uRE5QARYwYkOMdXuNdHa_DCkxP8-9uWbfh-JM9rka7dQxwD9EWVB82tzkYA1wB3o8wFsOAx0MeAzxTYWRbPx3yATeYVq_eDgWX9vd4dHu9rDgrta302LXfCwaEVhMF6thEEuYnQDge4r1501izytnh6Wg4aGe1sE7TAHvqFr1n4AqB9u6pMwvjnAQS0frF-7vfGSe3j8ex0dNw_Sl4meuAWystxSQ" http://localhost:5556/api/v1/clients`
&nbsp;&nbsp;&nbsp;Response: `HTTP/1.1 401 Unauthorized, {"error":"access_denied","error_description":"missing or invalid token"}`
&nbsp;&nbsp;&nbsp;Server side error: `ERROR: Failed to verify JWT claims: invalid claims, 'aud' claim and 'sub' claim do not match, aud=inZX_lvTz_KZi29wBg9-_cOpkOLmEodU2Obw23MJ7e4=@127.0.0.1, sub=d6d83195-30c8-49b3-9ae2-336b37bac234
 INFO: 127.0.0.1 - - [17/Feb/2016:09:03:44 +0200] "GET /api/v1/clients HTTP/1.1" 401 72`
**3**. Run the following rest call to worker in order to list users: `curl -ivL -X GET -H "Accept: application/json" -H "Authorization: Bearer eyFoSEJOc29ONXdjdWttcGVJd090YXI1R29Tcmc1MzZLQ0p3UHRhdTI0d1Vpd3NvZF93bVJKYkVDX0txV1FvZGVpWnhOVjZEd2tBYWVrUlNHaWdDMm53Rm1sSndhWDJSVlg4ODFYOUZ4VDVab0g2MmdQUW4ta2lwbDRscEswanI5aFFsd21mTWxWUkdwMlEtN253X0FydDVxZUtHLXdBV0xwejZFUE94UzRMUlVFVHVDY2pMQm9HLWJBM0V4VVNjUVdERVE3aTlZQWpmN19CajFrcHA4dVgyTFJpWlZVeGFDWjNDVmdQREUxS0doUVJ6VmNRRHFBeEQ3RFJTVnlNcjRqTmNsamxOVmIxX2o3T2FSYUtsU21VN0ItYno5c0ZWY1JXejFlb3VYLXBQVGhpckhGT01MUT09IiwidHlwIjoiSldUIn0.eyJhdWQiOiJpblpYX2x2VHpfS1ppMjl3Qmc5LV9jT3BrT0xtRW9kVTJPYncyM01KN2U0PUAxMjcuMC4wLjEiLCJlbWFpbCI6Im15QGFkbWluLmNvbSIsImV4cCI6MS40NTU3MzUzMzJlKzA5LCJpYXQiOjEuNDU1NjkyMTMyZSswOSwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo1NTU2IiwibmFtZSI6IiIsInN1YiI6ImQ2ZDgzMTk1LTMwYzgtNDliMy05YWUyLTMzNmIzN2JhYzIzNCJ9.qMiuHHXprRdzM05gxE8YvJ01hXuudVFlrPfuNpiPvra6yTKh3cez4ehL2NbH2Idvtj2AVa2sgCxdqcbvsPMzFUFTsuBKxdd1ynynQAszt4L5JhuoivIS2vNI1uRE5QARYwYkOMdXuNdHa_DCkxP8-9uWbfh-JM9rka7dQxwD9EWVB82tzkYA1wB3o8wFsOAx0MeAzxTYWRbPx3yATeYVq_eDgWX9vd4dHu9rDgrta302LXfCwaEVhMF6thEEuYnQDge4r1501izytnh6Wg4aGe1sE7TAHvqFr1n4AqB9u6pMwvjnAQS0frF-7vfGSe3j8ex0dNw_Sl4meuAWystxSQ" http://localhost:5556/api/v1/users`
&nbsp;&nbsp;&nbsp;Response: `HTTP/1.1 401 Unauthorized, {"error":"unauthorized","error_description":"The given user and client are not authorized to make this request."}`
&nbsp;&nbsp;&nbsp;Server side error: `ERROR: Error calling user management API: unauthorized: Desc: The given user and client are not authorized to make this request. Internal: <nil>:
INFO: 127.0.0.1 - - [17/Feb/2016:09:07:20 +0200] "GET /api/v1/users HTTP/1.1" 401 113`

So there are actually 2 different cases:

- for /clients call: I see that dex/Godeps/_workspace/src/github.com/coreos/go-oidc/oidc/verification.go runs this check (I didn't debug, just looked for the error message) and I do not understand why. The token actually keeps clientId as aud and userId as sub.
According to what I understand in http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation: aud must contain clientId (and it is), dex returns only clientId as aud and it cannot return more things without setting azp, which is not supported. Sub is actually declared as an identified for end-user, so cannot be a part of aud.
- for /users call: I have nothing special to say, just wondering why admin user is not authorized to list its users. Or the problem is with a client? 
I just go with the provided examples and documentation without messing with something more complex yet. Do I do anything wrong?

What I have in database:
**authd_user**: "d6d83195-30c8-49b3-9ae2-336b37bac234";"my@admin.com";f;"";t;1455636131;f
**client_identity**: "inZX_lvTz_KZi29wBg9-_cOpkOLmEodU2Obw23MJ7e4=@127.0.0.1";<secret>;"{"redirectURLs":["http://127.0.0.1:5555/callback"]}"
**session**: "xPoVinNptVQ=";"EXCHANGED";1455692132;1455735332;"inZX_lvTz_KZi29wBg9-_cOpkOLmEodU2Obw23MJ7e4=@127.0.0.1";"";"http://127.0.0.1:5555/callback";"{"ID":"d6d83195-30c8-49b3-9ae2-336b37bac234","Name":"","Email":"","ExpiresAt":"0001-01-01T00:00:00Z"}";"local";"d6d83195-30c8-49b3-9ae2-336b37bac234";f;"";"openid email profile"

Version:
-	OS: "Ubuntu", "14.04.2 LTS, Trusty Tahr"
-	Go: go version go1.5.2 linux/amd64
-	Dex: "7c8e25f2923e71b9736c14abdf25c9acb69c9984+dirty"
-	Postgres: 9.4.5
I get the same also with docker built using recent go-docker.

**Comment by rsoletob** [comment]
Client's API it's working using `grant_type=client_credentials` to retrieve access token. Is it correct?

**Comment by bobbyrullo** [comment]
@rsoletob yeah, you're supposed to use client credentials here not user ones.

Note: This part of the api (GET and POST to /clients to list and create clients) is going away; instead, these things will be moved to the bootstrap API (in the overlord) see #326

**Comment by boriska70** [comment]
Sorry for the false alarm. It wasn't mentioned in any place that client API is for client credentials flow only and word "client" is not necessarily means this so I assumed it is just a general CRUD. Planned to use it as a kind of dynamic registration/reuse for the system running in cloud where client can restart or move to another host at any time. 
Still I have a question - what's wrong with the User API call I mentioned? I guess this is not related to the wrong Oauth2 flow. I assume that I do something wrong but maybe you can point what exactly is wrong. Having User API can be very useful for the case that I want to do something with user before creation, for example: assign to tenant, add more checks, etc.

**Comment by bobbyrullo** [comment]
Ah, another piece of undocumented dex magic :) 

So, a client needs to be an Admin client and a user needs to be an Admin user. Unfortunately the only way to make an admin client right now is to do some SQL. Yuck. I'll make an issue for this and make sure it gets done soon.

**Comment by bobbyrullo** [comment]
@boriska70 watch https://github.com/coreos/dex/issues/327 for improvements in this space.
