### ISSUE TITLE
Erroneously getting "Please authenticate before registering"

### ISSUE THREAD

**Issue by robszumski** [coreos/dex#324]
Prior to seeing this message, I followed the OAUTH flow so I should have been authenticated. What does this error message mean?

![image](https://cloud.githubusercontent.com/assets/755540/13163198/f209175c-d65f-11e5-8764-4a2bf13271c0.png)

**Comment by ericchiang** [comment]
This indicates you've attempted to register, gone to your identity provider, then come back to the registration endpoint without a valid login. We use some session tokens between those redirects to validate those actions. Is this a persistent problem?

**Comment by robszumski** [comment]
How would I test if its persistent? Sign up a bunch of times?

**Comment by ericchiang** [comment]
I tried it out and got the same thing. Was wondering if there was a
temporary error or some problem with dex's logic. Looks like it's the
latter.

**Comment by akshaybahetii** [comment]
I configured dex to work with ldap. While using the example-app when try to login I get "There's no account for this user" - "Try registering with this first:". I get the same message when I try to register.  

Is this issue the same as reported here ?

**Comment by ericchiang** [comment]
Unfortunately there's not really anyone with time to support this version of dex anymore. Closing for now.
