### ISSUE TITLE
Add dynamic client registration to bootstrapping (admin) API

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#326]
This allows us to provide authentication in front of the dynamic client registration and gets us closer to feature parity through the APIs for #298

**Comment by bobbyrullo** [comment]
Please explain this issue - how does it get us authentication? Also, moving dynamic client registration to the overlord means having to expose the overlord outside of your firewall.

**Comment by ericchiang** [comment]
Sorry. I'd like to add a link to the admin API to allow registration. Not remove it from dex itself.

Currently `dexctl new-client` uses a direct connection to the DB to create that client. We need an alternative API to allow this. I'd like to add an endpoint to the overlord API (protected by the secret token).

**Comment by ericchiang** [comment]
closed in https://github.com/coreos/dex/pull/392
