### ISSUE TITLE
Move ./Godeps to ./vendor

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#328]
With 1.6 the go tool will automatically detect the vendor directory during compilation.

From a developer experience, it would be a lot nicer if `go test github.com/coreos/dex/db` just worked without having to mess with godep. We can keep the build and test scripts setting the GOPATH manually for older versions of Go.

**Comment by bobbyrullo** [comment]
this means, stop supporting go 1.4, and turn on experimental vendor mode.
