### ISSUE TITLE
Users should be able to delete/disable themselves

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#33]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Thursday Jul 02, 2015 at 17:52 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/293_

---

Users should be able to login to AuthD and "delete" their accounts. Once deleted registration with the same email address should be possible.

**Comment by bobbyrullo** [comment]
Need to think more on this one; might be a problem from client (RP) perspective.

**Comment by ericchiang** [comment]
We expose the ability to delete users through the API. A client app should handle this.
