### ISSUE TITLE
regression: Not able to log in with local connector when running dex-worker with --no-db

### ISSUE THREAD

**Issue by fnordahl** [coreos/dex#332]
PR #304 introduces a regression.

With dex-worker running with --no-db it is no longer possible to log in using the local connector with credentials configured in static/fixtures/connectors.json and static/fixtures/users.json.

Adding some Printlns to password.go UnmarshalJSON function shows that the users are created twice, the first time with valid password info, the second time with blank password.
<pre>diff --git a/user/password.go b/user/password.go
index 4b93f34..8fb67cf 100644
--- a/user/password.go
+++ b/user/password.go
@@ -153,6 +153,7 @@ func (u *PasswordInfo) UnmarshalJSON(data []byte) error {
        }
 
        u.UserID = dec.UserID
+       fmt.Println("%v", u.UserID)
 
        u.PasswordExpires = dec.PasswordExpires
 
@@ -169,6 +170,7 @@ func (u *PasswordInfo) UnmarshalJSON(data []byte) error {
                        return err
                }
        }
+       fmt.Println("%v", u.Password)
        return nil
 }
 
</pre>

When running a version of dex prior to the commit of #304 it works as expected
``git checkout 9ca27a20352edfdd335b571bc7a6f61258294cdc``

Unfortunately I am prohibited from chasing this to the root cause at this time. Maybe you know what's going on from this description, @ericchiang ?

**Comment by ericchiang** [comment]
Thanks, will look into this.
