### ISSUE TITLE
token endpoint basic auth uses wrong decoding strategy

### ISSUE THREAD

**Issue by gerson24** [coreos/dex#336]
We're working on the integration of our Play/Scala apps with Dex. I'm having problems when I call `/token`,
because when I build the header "Authorization: Basic Y2xpZW50aWQ6c2xka2ZqYXNsa2Rmago=", the library I'm using it first urlencodes the ClientID, and the Secret, separated, and then a base64 of everything.
Example:

`"Authorization: Basic clientID:Secret" --> This will become "Authorization: Basic " + base64encode(urlencode(clientID) + ':' + urlencode(Secret))`

Dex is decoding the base64, but not the urlencode, because it just doesn't expect it.
After doing some research (https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/129/clientsecretbasic-incorrectly-url-encodes),
we think this Java library we're using is encoding it that way, because is specified on the Oauth2 Spec (http://tools.ietf.org/html/rfc6749#section-2.3.1).

This is where Dex should decode the credentials
```go		
		state := r.PostForm.Get("state")

		user, password, ok := r.BasicAuth()
		if !ok {
			log.Errorf("error parsing basic auth")
			writeTokenError(w, oauth2.NewError(oauth2.ErrorInvalidClient), state)
			return
		}

		creds := oidc.ClientCredentials{ID: user, Secret: password}
```
https://github.com/coreos/dex/blob/v0.2.3/server/http.go#L427-L437

If you agree, we're happy to make a PR.

**Comment by ericchiang** [comment]
Yeah, thanks. It does indeed look like it's wrong. It looks like there's the same bug in our client too: https://github.com/coreos/go-oidc/blob/ec2746d2ccb220e81c41b0b0cb2d4a1cc23f7950/oauth2/oauth2.go#L189

I'd like to evaluate what's using our client code first before pushing a patch. This would be a breaking change (all be it a correction), so I just want to be a little cautious.

**Comment by gerson24** [comment]
great, thanks! Let me know when you want me to make the PR

**Comment by ericchiang** [comment]
@gerson24 we'd like to see a fix that accommodates both the correct encoding and the existing encoding for a little bit.

Also our client needs to be updated to do the same. See coreos/go-oidc#54. You're welcome to take this one too if you'd like.

**Comment by gerson24** [comment]
ok, perfect! I'm working on it.
