### ISSUE TITLE
Ability to register new OIDC clients via overlord API

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#34]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Thursday Jul 02, 2015 at 21:41 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/294_

----

Instead of using authctl with db flag. This will make scripting the bootstrapping easier.

**Comment by ericchiang** [comment]
moved to #326
