### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by TelanJ** [coreos/dex#347]
I tried using kubernetes deployment and I encounter this error. Has anyone encountered this problem?

>NAME                   READY     REASON                                                      RESTARTS   AGE
dex-overlord-flgav     0/1       Image: quay.io/coreos/dex is ready, container is creating   0          18m
dex-postgres-klsgw     1/1       Running                                                     0          53m
k8s-master-127.0.0.1   3/3       Running                                                     6          54m
julio@julio-HP-ENVY-Sleekbook-6-PC:~/dex/contrib/k8s$ kubectl describe pods/dex-overlord-flgav
Name:				dex-overlord-flgav
Image(s):			quay.io/coreos/dex
Node:				127.0.0.1/127.0.0.1
Labels:				app=dex,role=overlord
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	dex-overlord (1/1 replicas created)
Containers:
  dex-overlord:
    Image:		quay.io/coreos/dex
    State:		Waiting
      Reason:		Image: quay.io/coreos/dex is ready, container is creating
    Ready:		False
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	False 
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath	Reason		Message
  Mon, 29 Feb 2016 21:14:17 +0800	Mon, 29 Feb 2016 21:14:17 +0800	1	{scheduler }				scheduled	Successfully assigned dex-overlord-flgav to 127.0.0.1
  Mon, 29 Feb 2016 21:14:17 +0800	Mon, 29 Feb 2016 21:32:48 +0800	112	{kubelet 127.0.0.1}			failedMount	Unable to mount volumes for pod "dex-overlord-flgav_default": exit status 32
  Mon, 29 Feb 2016 21:14:17 +0800	Mon, 29 Feb 2016 21:32:48 +0800	112	{kubelet 127.0.0.1}			failedSync	Error syncing pod, skipping: exit status 32

**Comment by ericchiang** [comment]
Hard to say without seeing the logs. What does `kubectl logs -p {{ POD }}` say?

**Comment by TelanJ** [comment]
This happened when I used that

`$kubectl logs -p dex-overlord-8b6tk
Internal Error: pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"`

**Comment by ericchiang** [comment]
It's unclear that this is indicating a dex specific issue. Closing for now since this issue tracker is for dex. If you find more information from k8s (specifically an error log for the dex pods), feel free to reopen this issue.
