### ISSUE TITLE
refresh tokens

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#35]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Thursday Jul 02, 2015 at 21:43 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/295_

----

For better security we should transition to having shorter-lived JWTs and instead issue refresh tokens to client apps so they can refresh the user's token on their behalf. Adding such a feature would require the ability for a user to revoke access to an app as well.

**Comment by ericchiang** [comment]
Moving to #261
