### ISSUE TITLE
tectonic console: annoying UX if you go to a login page with expired token

### ISSUE THREAD

**Issue by philips** [coreos/dex#355]
1) Go to a tectonic console and click login
2) Wait for an hour
3) Type username and password
4) Get authorization error and don't get a new token

This has happened in the past to me and the only solution is to manually go back to the tectonic console URL and get redirected with a new token.

**Comment by ericchiang** [comment]
Is this an issue with the tectonic console more than dex? cc @joeatwork

**Comment by sym3tri** [comment]
Sounds like it's due to the auth session expiring in dex. Console could handle that, as long as there is a specific auth error code returned to indicate this situation. What error code does dex return in this case?

**Comment by ericchiang** [comment]
Closing this as we haven't seen the issue with dex v2.
