### ISSUE TITLE
Use golang.org/x/net/context for signalling cancellations

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#363]
For example, the current connector interface looks like this.

``` go
type Connector interface {
    Sync() chan struct{}
}
```

The implementer of `Sync` is expected to return a channel that when closed causes `Sync` to cease performing it's long running actions. This has caused some confusion (see #316), and net/context is the established idiom for this kind of stuff.

Change these kind of calls to:

``` go
type Connector interface {
    Sync(ctx context.Context)
}
```

**Comment by tmc** [comment]
@ericchiang does this imply doing the same in go-oidc?

**Comment by ericchiang** [comment]
@tmc yes. Though it's not high priority.

We're considering restructuring go-oidc anyway (see coreos/go-oidc#61) so this would probably be tackled then.

**Comment by ericchiang** [comment]
Merging this into https://github.com/coreos/dex/issues/607
