### ISSUE TITLE
Emailer config for example app

### ISSUE THREAD

**Issue by TelanJ** [coreos/dex#364]
I've tried changing the `~/dex/static/fixtures/emailer.json` for it to send using "SMTP" or "Mailgun". I've followed the instruction for email-configuration and tried to run the dex-worker. When I try to register using local email, 

On "STMP" mode,
`ERROR: error sending email verification email Message not valid: 
ERROR: Failed to send email verification email: Message not valid`
I get this error

On "Mailgun" mode,
`ERROR: error sending email verification email gomail: could not send email 1: mail: no address: 
ERROR: Error sending email verification: gomail: could not send email 1: mail: no address`

These errors are from the console

**Comment by miguelcubillo** [comment]
Hi, Have you tried using the -email-from flag? the error "gomail: could not send email 1: mail: no address" probably means that the From address is empty. If that is the case, it happens because -email-from defaults to "".

**Comment by TelanJ** [comment]
Hi! Thanks for the response, I've done what you said and it worked perfectly!

Cheers,
Julio Telan
