### ISSUE TITLE
Getting started guide refers to non existent DEX_APP_REDIRECTURL 

### ISSUE THREAD

**Issue by TelanJ** [coreos/dex#365]
When I issue the command `eval "$(./bin/dexctl --db-url=$DEX_DB_URL new-client http://127.0.0.1:5555/callback)"` after running the worker node, there is no value in the `$DEX_APP_REDIRECTURL` but the `DEX_APP_CLIENT_ID` and `DEX_APP_CLIENT_SECRET` has.

**Comment by ericchiang** [comment]
dexctl prints out `DEX_APP_REDIRECTURL_0`, `DEX_APP_REDIRECTURL_1`, etc.

Though our getting started guide seems to be referring to and old version. Thanks for reporting!

**Comment by TelanJ** [comment]
@ericchiang Thanks for the quick response! Will keep on helping whenever I can.
