### ISSUE TITLE
Dex doesn't return an error when required response_type param is empty or missing

### ISSUE THREAD

**Issue by rsoletob** [coreos/dex#370]
According to OIDC spec in all flows parameter response_type is required ([Authorization code flow authentication request](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)). Nowadays dex doesn't return any error when this parameter is missing and works as Authorization code flow.

**Comment by rsoletob** [comment]
After a code review about this, I saw request parameters are checked in go-oidc lib. In dex `response_type` param check is [here](https://github.com/coreos/dex/blob/master/server/http.go#L337) but the problem is there isn't [connector_id](https://github.com/coreos/dex/blob/master/server/http.go#L287). Therefore in method [renderLoginPage](https://github.com/coreos/dex/blob/master/server/http.go#L258) dex set `response_type` to value `code` without checking what it was in the first request. [Here](https://github.com/coreos/dex/blob/master/server/http.go#L256-L260) is the code. A possible fix could be:

```go
v := r.URL.Query()
		v.Set("connector_id", idpc.ID())
		v.Set("response_type", q.Get("response_type"))
		link.URL = httpPathAuth + "?" + v.Encode()
		td.Links = append(td.Links, link)
```
On the other hand, I think checks about authorization code request would be in go-oidc lib close to [redirect_uri param check](https://github.com/coreos/go-oidc/blob/master/oauth2/oauth2.go#L368-L382), something like this:

```go
err := func() error {
		if acr.ClientID == "" {
			return NewError(ErrorInvalidRequest)
		}

		redirectURL := q.Get("redirect_uri")
		if redirectURL != "" {
			ru, err := url.Parse(redirectURL)
			if err != nil {
				return NewError(ErrorInvalidRequest)
			}
			acr.RedirectURL = ru
		}
		
		if acr.ResponseType == "" {
			return NewError(ErrorInvalidRequest)
		}

		return nil
	}()
```
What do you think?
If you agree, we're happy to make a PR.

**Comment by ericchiang** [comment]
It looks like this is the only place `oauth2.ParseAuthCodeRequest` and `oauth2.AuthCodeRequest` are being used in all of go-oidc and dex (no other functions even refer to this type). Maybe we can just move this to the dex server code and remove them from go-oidc?

**Comment by ericchiang** [comment]
I've opened up coreos/go-oidc#64 In an overarching way think that covers this.
