### ISSUE TITLE
overlord needs to be horizontally scalable

### ISSUE THREAD

**Issue by colhom** [coreos/dex#372]
In a clustered environment and in the presence of machine failures/network partitions, it is not possible to ensure that a single dex-overlord instance is running. 

With Kubernetes, a network partition between the control plane and a node running dex-overlord would result in the overlord pod being scheduled on another node. At this point, there will be multiple overlord instances talking to the same database- and there is really no way to avoid that.

Dex overlord should implement locking at the database level to ensure that multiple dex overlord instances running concurrently do not cause problems.

**Comment by ericchiang** [comment]
see #302

Currently the overlord does use transactions to accomplish it's rotations and migrations, but we've not tested the consequences of running two.

**Comment by colhom** [comment]
@ericchiang the workers performing leader election would definitely be the most desirable "end" solution. I assume they would do so via the database-- requiring the workers to all discover each other's network addresses would be very cumbersome (especially in a multi-cluster deployment).

Simply verifying that multiple overlords can play nicely with each other would definitely be sufficient for now. Having the overlord separate from the workers does increase deployment overhead, but is manageable assuming we are free to replicate the overlord.

**Comment by ericchiang** [comment]
Overlord is dead. The dex binary is horizontally scalable.
