### ISSUE TITLE
Any plan for rbac implementation in dex?

### ISSUE THREAD

**Issue by waterdudu** [coreos/dex#373]
Is there any rbac implementation in dex?  I searched dex code, but found no role based access control code or issue, which is great needed in authentication & authorization system like dex. Will this be supported in future?

**Comment by ericchiang** [comment]
For the current roadmap, dex's groups implementation (#175) will provide primitives for authz. Please see the discussion in that issue.

The groups proposal should provide the capabilities for users to implement specific authz flavors, such as RBAC, on top of groups.

**Comment by ericchiang** [comment]
Going to close this. We've gone in a different direction and plan to use other services to enforce RBAC.
