### ISSUE TITLE
dex wrongly assumes URIs have http(s) scheme

### ISSUE THREAD

**Issue by johanhenselmans** [coreos/dex#374]
At the moment dex only supports https: and http: as URI schemes. 

So ./bin/dexctl --db-url=$DEX_DB_URL new-client com.example.openid://com.example.apps:/oauthredirect

returns: 
Failed creating new client: uri field redirect_uris scheme is not http or https

In the IOS and Android world that will not suffice. Most of the use cases in this world would be to use a webview to do the authentication, and then point back to the app with a so called custom URI, see for instance README.md at https://github.com/openid/AppAuth-iOS

Authorization Server Support
Both Custom URI Schemes (all supported versions of iOS) and Universal Links (iOS 9+) can be used with the library.

In general, AppAuth can work with any Authorization Server (AS) that supports native apps, either through custom URI scheme redirects, or universal links. AS's that assume all clients are web-based or require clients to maintain confidentiality of the client secrets may not work well.

These Custom URI Schemes are defined in https://tools.ietf.org/html/draft-ietf-oauth-native-apps-00 as:

"custom URI scheme"  A URI scheme (as defined by [RFC3986]) that the
      app creates and registers with the OS (and is not a standard URI
      scheme like "https:" or "tel:").  Requests to such a scheme
      results in the app which registered it being launched by the OS.
      For example, "myapp:", "com.example.myapp:" are both custom URI schemes.

Also see:

https://openid.net/specs/openid-connect-registration-1_0.html

application_type
OPTIONAL. Kind of the application. The default, if omitted, is web. The defined values are native or web. Web Clients using the OAuth Implicit Grant Type MUST only register URLs using the https scheme as redirect_uris; they MUST NOT use localhost as the hostname. Native Clients MUST only register redirect_uris using custom URI schemes or URLs using the http: scheme with localhost as the hostname. Authorization Servers MAY place additional constraints on Native Clients. Authorization Servers MAY reject Redirection URI values using the http scheme, other than the localhost case for Native Clients. The Authorization Server MUST verify that all the registered redirect_uris conform to these constraints. This prevents sharing a Client ID across different types of Clients.

So please make it possible to use custom URI schemes. Otherwise dex will be unusable for authentication for this type of apps.

**Comment by ericchiang** [comment]
Yes I think a better name for this would be "dex wrongly assumes URIs have http(s) scheme" where this is very clearly not true https://www.rfc-editor.org/rfc/rfc3986.txt

**Comment by ericchiang** [comment]
Dex no longer mandates that URLs use `http://` or `https://` as a scheme.
