### ISSUE TITLE
Worker API Auth

### ISSUE THREAD

**Issue by stongo** [coreos/dex#380]
I can't seem to find any documentation on what credentials are expected to make authenticated requests to the worker api.
Trying to figure out how to disable users. Was hoping a user could could disable their own account. But otherwise need to figure out how to make our api do it.

**Comment by ericchiang** [comment]
I will add this to the docs tomorrow but the API looks for the OpenID Connect [ID Token](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse) in the "Authorization" header of the request. 

```
Authorization: Bearer {{ ID Token }}
```

That ID Token must be issued for a admin user through an admin client. So at the moment a user must be an admin to disable another user.

However, we're beginning to add different combinations of admin/non admin client/users in #329. With this more fine grained approach, it'd be easy to allow a non admin user to be able to disable themselves through an admin client.

**Comment by jonnenauha** [comment]
I would like to create/invite new users with the worker API. I've been reading the code and trying to figure our how to do this (as OP said there is no real docs, vague json spec file). The biggest issue I think is that the dex repo does not provide any help in figuring out the JWT authorization header.

You comment helped a bit, if I understand right once the serve has authed you can

```go
// auth server
client, err := oidc.NewClient(combinedConfig)
...
// later generate token for client
client.ClientCredsToken([]string{"????"})
```

That does give you a token, but it does a roundtrip to the server and is hardcoded to use the `grant_type: "client_credentials"`.

So, is creating users with API supported at all from a client (not a signed in user). I want my server that is using dex to be able to ask it to also create/invite new users. Looks like the user.go API privides this, but the admin.go does not. The admin authorization is a lot simpler as it just check the singleton token you pass into dex.

Additionally I suppose it uses `client_identity` tables `dex_admin` boolean, or is that again tied to the user.go API auth?!

This is so confusing. I really hope you can get something up (docs mostly) for the next release :) When is that planned btw?

**Comment by bobbyrullo** [comment]
@jonnenauha this *IS* super confusing, and we apologize for that. Keep an eye on #427, which should address these issues (I just opened it in response to this). I'll be on vacation the latter half of this week, so I won't get to work on it much till then unfortunately.

**Comment by jonnenauha** [comment]
Yeah, np. I know you are at 0.x versions. Cant expect everything to be ready and polished. It it just frustrating to see that there is some kind of API but not being able to use it :)

Please add code examples or provide some sub library for working against the API, that would be ideal. Exposing the structs that are expected as JSON payload and easy way to generate the JWT stuff (afaik the payload actually goes inside the JSON with its claims, but you get my point). As my server is Go, it would be super nice to just use structs and helpers from this repo.

One question that is still on my mind. Is there actually a way to invite/create new users with the admin API. It looks like it is meant for adding new clients, not users. It would be ideal for me if I could use some API to create/invite users with the admin tokens. As the API consumer is my server, i wont have a way to authenticate it with the signin page and get redirects back like human users do. I guess you could have some admin user account the server would use, but it seems really too complicated.

**Comment by ericchiang** [comment]
Dex now uses gRPC with no auth beyond TLS assets. See the documentation[0].

[0] https://github.com/coreos/dex/blob/master/Documentation/api.md
