### ISSUE TITLE
Help on Authentication Process

### ISSUE THREAD

**Issue by TelanJ** [coreos/dex#381]
Hi! I've been trying to develop my own service API to be able to call from the dex example app.

It seems that the `/service` doesn't authenticate using dex cause when i go to `http://127.0.0.1:5555/service`, it still functions whether I'm logged in or not. What can I do about this?

This is my version of the sample app:
https://github.com/TelanJ/service_client

This is my service:
https://github.com/TelanJ/service_server

Thanks in advance for helping!

Julio Telan

**Comment by ericchiang** [comment]
Sorry I'm a little confused about what the question is here. Do you have a specific concern about dex or is this a question about how to use OpenID Connect? I've looking at your app but I'm unsure about what `/service` is attempting to do.

P.S. - I would strongly discourage you depending on anything in dex's `pkg` directory. These are not meant to be a public facing packages and may change unexpectedly.

**Comment by TelanJ** [comment]
Hi eric!

Thanks for the quick response!

`/service` will redirect the user to a basic TCP RPC microservice that the user will only have access if it is authenticated by dex.

That too. How can I use OpenID Connect. 

Cheers,
Julio Telan

**Comment by ericchiang** [comment]
@TelanJ unfortunately this is an issue tracker for dex and isn't best venue for debugging outside code.

If you have questions about how to use OAuth2 or OpenID Connect I'd recommend looking for tutorials on those protocols. If you have specific questions about your own code, stackoverflow might be a better place unless it directly relates to a dex feature (then feel free to bring it up here).

Unfortunately we're light on documents explaining OAuth2 or OpenID Connect. Feel free to open an issue requesting we add some, but at the moment it's not high on our priority.

Closing this issue for now.
