### ISSUE TITLE
Proposal: Add OAuth2 scope for determining if a user is an admin

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#383]
This came up earlier. We'd like to be able for outside apps to determine if a user is a dex "admin" from just looking at the Id Token.

I'd like to propose achieving this through a custom OAuth2 scope:

```
dex:adminstatus
```

If the client chooses to use this scope, when the user logs in they will be presented with the following message.

```
The application has requested access on your behalf to.
* View your email and name.
* View if you're a dex admin.
```

When creating an ID Token, the token would contain:

```
{
    "aud": "foobar",
    "sub": "barfoo",
    "email": "pacman@example.com",
    ...
    "groups": ["dex_admin"]
}
```

If the user is not an admin, the array would be empty.

Why `"groups"`? In the future this _could_ be extended to support other groups (admins are after all just a type of group).

If not, the obvious alternative would be:

```
{
    ...
    "dex_admin": true
}
```

**Comment by TelanJ** [comment]
+1! This would be an awesome addition and a step further to authorization!

**Comment by bobbyrullo** [comment]
"adminstatus" seems too ambiguous to me - how about "dex:is_admin"

And I'd rather not put a stake in the ground right now when it comes to groups, especially making some group name special right now.

Why not just another custom claim eg "http://coreos.com/dex/is_admin"

**Comment by ericchiang** [comment]
Was discussing this with @joeatwork and @kans. This might be a good way to avoid admin clients. E.g. introduce a scope that allows a client to talk to the dex API on behalf of an admin user.

```
The client has requested access on your behalf to the dex API
```

**Comment by bobbyrullo** [comment]
That would work, but it opens up Dex to phishing attacks. I'd personally like to keep it locked down.

**Comment by ericchiang** [comment]
Isn't that true for any scope we tie to a resource?

**Comment by bobbyrullo** [comment]
> Isn't that true for any scope we tie to a resource?

Yes but a couple of things to note:

1. This is not just any resource - this is the keys to the kingdom; you compromise this and it's game over over for every client, not just the one.

1. For prior art, look at the cross domain stuff that google does. This is similar in that you are asking certain applications (eg, one that has a user admin UI) to do stuff on behalf of another (Dex). They lock it down by only allowing it for apps in the same project.

**Comment by ericchiang** [comment]
Fair enough. Yeah, might be better to not let an admin christen any old client with admin abilities.

**Comment by sym3tri** [comment]
> might be better to not let an admin christen any old client with admin abilities.

FWIW I am +1 that we _do not_ do this (at least for now). Users would likely just click through without much thought (b/c they likely won't fully understand the implications).

**Comment by ericchiang** [comment]
Dex no longer has the concept of an "admin user".
