### ISSUE TITLE
Proposal: Custom OAuth2 scopes

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#384]
At the moment, may of our services that authenticate based on ID Tokens attempt
to restrict the clients that interact with the service. Consider the following
two client setup:

```
* client1 - a client we expect to interact on the users behalf with resource1
* client2 - a client that shouldn't interact with resource1
```

To ensure client1 is the only thing interacting with our resource we end up
mandating that IDTokens audience fields matches `client1` on the server side.
However this makes it hard to add new clients and adds additional configuration
overhead.

In reality it should be the end user's choice when determining what client
interacts with a given resource.

Since our needs are often specific, and dex is a general tool, I propose adding
the ability to customize the oauth2 scopes dex accepts at runtime.

Scopes would be associated with a JWT claim, a claim value, and a message for the
user. When the scope is requested, the user is show the message and if they
consent, the claim is inserted into the user's IDToken.

```
[
    {
        "scope": "jenkins:write",
        "claim": "jenkins",
        "value": "write",
        "description": "Allow access to Jenkins on your behalf."
    }
]
```

This would allow the server to differentiate between clients without having to
maintain a whitelist of trusted clients.

It would be the consumer of the ID Token's responsibility to interpret these
scopes.

**Comment by bobbyrullo** [comment]
> propose adding the ability to customize the oauth2 scopes dex accepts at runtime.

I would expect to see details on how this works in the proposal.

Also, it's not clear that the JSON blob in the proposal is.

**Comment by sym3tri** [comment]
So there would be another API for managing what scopes are available?

Also can you link to specifics in the OIDC spec about custom scopes?

**Comment by ericchiang** [comment]
> So there would be another API for managing what scopes are available?

Most likely a similar to the connectors API. "Set all the scope from this json file"

> Also can you link to specifics in the OIDC spec about custom scopes?

This is more is more of an OAuth2 thing. OAuth2 defines the idea of scope, and. OpenID Connect defines some scopes it looks for https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims.

As a concrete example, Google supports custom scopes to request access to different Google resources: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters

**Comment by MalteJ** [comment]
Any news on this?
How does Kubernetes interact with dex? Where is authorization happening?

**Comment by ericchiang** [comment]
Going to close this. Registerable scopes would be very nice but I don't think this is the correct proposal.

@MalteJ it's been a while and sorry for not getting back to you but Kubernetes does authorization as a separate system (see http://kubernetes.io/docs/admin/authorization/). Dex is strictly authentication.
