### ISSUE TITLE
Create Storage Interface to easily get at repos.

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#385]
Abstract away the DbMap:

For example

``` go
type Storage interface {
    GetClientRepo() client.ClientIdentityRepo
    ...
}
```

This would clean up anything that needed access to a repo.

``` go
type AdminAPI struct {
    localConnectorID string
    storage          repo.Storage
}
```

**Comment by ericchiang** [comment]
I tried this earlier in the release cycle and found that this was a huge undertaking due to the mount of refactoring this requires. We might want to move it to the next milestone.

**Comment by ericchiang** [comment]
Storage has been revamped and is now much simpler https://godoc.org/github.com/coreos/dex/storage
