### ISSUE TITLE
dex-worker should get email configuration from db

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#388]
In the same spirit as #382.

In containerized environments, we currently have to mount a file into the container to configure email. Additionally, there's no way to configure all the workers, without bouncing all the workers. This should be read from the DB.

For further speed of startup, I also propose defaulting to `{"type": "fake"}` if a config is not found.

Steps should be.

1. I want to send an email, was a file on disk specified? If so use that. Else...
2. Is there a config in the db? If so use that. Else...
3. Default to `{"type":"fake"}`

Errors should stop this process. Failing to read a file from disk should not result in checking the database, and failing to query the database should not result in using `{"type":"fake"}`

**Comment by sym3tri** [comment]
Before starting on this I think we need to rethink the whole config strategy.

**Comment by ericchiang** [comment]
Yeah I had a chat with @chancez about this. On the whole dex needs a single point of configuration, be it the dexctl revamp or the a config file. E.G. I'd like to be able to configure dex's connectors at the same time as dex's email.

Closing this issue.
