### ISSUE TITLE
reset-password: valid email address but no password for userID

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#39]
<a href="https://github.com/ecnahc515"><img src="https://avatars.githubusercontent.com/u/1400401?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ecnahc515](https://github.com/ecnahc515)**
_Tuesday Jul 21, 2015 at 00:11 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/328_

----

So I tried going through the reset password flow using my google accounts email address and got the following error in the authd logs:

```
ERROR: No Password for userID: "55f79aa1-33dc-4d53-b0e4-0406c9eaab85"
```
It currently tells me it sent an email to my registered email address, but it's not actually sending any emails. After reading https://github.com/coreos-inc/auth/issues/316 it should most likely show the same message regardless, but it should probably send an email with details stating that password resets are handled by the OIDC provider (such as google in this case), with possible instructions on how to reset passwords through the provider.

**Comment by sym3tri** [comment]
This very old and I believe the issue has since been resolved. Please reopen if you can reproduce.
