### ISSUE TITLE
Adding a Facebook Connector

### ISSUE THREAD

**Issue by TelanJ** [coreos/dex#391]
Is it possible to add a facebook connector?

**Comment by ericchiang** [comment]
Facebook doesn't support OpenID Connect so we'd need to add custom logic to dex, though that shouldn't be hard. It'd be very similar to the [bitbucket connector](https://github.com/coreos/dex/blob/eb6dceadfd98ea786bce887502f5a74d8b49a256/connector/connector_bitbucket.go).

Would you be interested in adding this? :)
