### ISSUE TITLE
Configurable token expiry time

### ISSUE THREAD

**Issue by rsoletob** [coreos/dex#394]
In our use case, we need a less token expiry time. Maybe dex could have a config value to set it. What do you think?

**Comment by ericchiang** [comment]
Yeah this sounds totally reasonable. There's been some discussion in #377 about moving away from flags and towards a global config file for dex. So please be aware of that. Will try to follow up on that thread with a concrete plan.

**Comment by ericchiang** [comment]
Note from attempting to configure this. Tokens are minted [here](https://github.com/coreos/dex/blob/c2c7f03f47a20e8bee196ab629c4d7b018ba59bb/server/server.go#L505-L506) and the expiry is specified [here](https://github.com/coreos/dex/blob/c2c7f03f47a20e8bee196ab629c4d7b018ba59bb/session/session.go#L17).

Hard to say what else changing `DefaultSessionValidityWindow` will affect.

**Comment by ericchiang** [comment]
Closed via https://github.com/coreos/dex/pull/665
