### ISSUE TITLE
Administrative page to view clients, connectors, etc

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#4]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Wednesday Nov 19, 2014 at 02:10 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/81_

---

a page to list all the registered clients of an authd instance. so users can be directed to a page with links to initiate a login flow. useful for error scenarios.

requires:
- a new page to list services (or below current error/login page)
- clients need to register entry-point urls
- changes to error handling flow

**Comment by ericchiang** [comment]
This should probably just be an external app.
