### ISSUE TITLE
Error messages aren't very helpful/specific

### ISSUE THREAD

**Issue by chancez** [coreos/dex#400]
Env:
```
DEX_WORKER_CLIENTS=.dexconfig/clients.json
DEX_WORKER_CONNECTORS=.dexconfig/connectors.json
DEX_WORKER_EMAIL_CFG=.dexconfig/emailer.json
DEX_WORKER_USERS=.dexconfig/users.json
DEX_WORKER_EMAIL_TEMPLATES=templates/dex/emails
DEX_WORKER_HTML_ASSETS=templates/dex/html
DEX_WORKER_NO_DB=true
```

Getting errors like this:

```
FATAL: Unable to build Server: failed to create client identity repo: illegal base64 data at input byte 4
```

This really meant "client secrets must be base64 encoded within the `connectors.json`"

```
FATAL: Unable to build Server: remote identity already in use for another user
```

This wasn't too bad, but it probably could have told me what ID it was that caused this.

```
FATAL: Unable to build Server: invalid ID`
```

This was because the format of the `users.json` changed, and the JSON no longer had a key called `users` within the list of users.

Ideally these get validated before passing them to the server, and provide better context on what was wrong, because it isn't clear what configuration was wrong, or what value specifically it was referring to.

**Comment by ericchiang** [comment]
Going to close this as these specific error messages were cleaned up. @chancez please open a new issue with specific errors if there are any else you want to be addressed.
