### ISSUE TITLE
FATAL: Cannot decrypt keys using any of the given key secrets. The key secrets must be changed to include one that can decrypt the existing keys, or the existing keys must be deleted.

### ISSUE THREAD

**Issue by qudenger** [coreos/dex#407]
when i run cmd "./bin/dex-overlord &" to start dex-overlord, i get the follow error, what i should do? i exported the var in container, maybe export DEX_KEY_SECRET ... twice, but these environment variables not set, so i add it to /etc/profile, then run "./bin/dex-overlord &",  but it show the fatal error.

**Comment by ericchiang** [comment]
The error is pretty descriptive. The secrets to decrypt data in the database is incorrect. How are you ensuring that `-key-secrets` flag or the `DEX_KEY_SECRETS` environment variable is set the same on subsequent runs of the overlord?

**Comment by qudenger** [comment]
Thank you @ericchiang, i remove the secrets form database and regenerate, It works.

**Comment by ericchiang** [comment]
Great! Closing this for now.
