### ISSUE TITLE
Update go-oidc to latest

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#418]
There have been a couple attempts to update go-oidc with poor results (#353, #405).

After hacking at this I've faced a couple blockers. A lot of tests do not work well with coreos/go-oidc#56 since they're comparing literal claims type for type. Because claims are always decoded into [`map[string]interface{}`](https://github.com/coreos/go-oidc/blob/4ae1db46ec3e4dc8c30db43924c21e1600ba3400/jose/claims.go#L103-L109), numbers always end up as float64s (looks like the original reason timestamps were type-casted). This results in pretty rough diffs:

```
=== RUN   TestInvitationParseAndVerify
--- FAIL: TestInvitationParseAndVerify (0.09s)
	invitation_test.go:100: case 0: Compare(want, got):  {
		  Claims: {
		           aud:                                       "myclient",
		-          exp:                                       1461035298,
		+          exp:                                       1.461035298e+09,
		           http://coreos.com/email/verificationEmail: "user@example.com",
		           http://coreos.com/invitation/callback:     "http://client.example.com",
		           http://coreos.com/password/old-hash:       "Halloween is the best holiday",
		-          iat:                                       1461024498,
		+          iat:                                       1.461024498e+09,
		           iss:                                       "http://example.com",
		           sub:                                       "1234",
		          },
		 }
```

We have a lot of structs in dex that look like this:

```go
type EmailVerification struct {
       Claims jose.Claims
}
```

Which are accompanied by helper functions like so:

```go
func ParseAndVerifyEmailVerificationToken(...) (EmailVerification, error) {
    // ...
}


func (e EmailVerification) UserID() string {
	return assertStringClaim(e.Claims, "sub")
}

func (e EmailVerification) Email() string {
	return assertStringClaim(e.Claims, ClaimEmailVerificationEmail)
}

func (e EmailVerification) Callback() *url.URL {
	return assertURLClaim(e.Claims, ClaimEmailVerificationCallback)
}
```

To solve this I'd like to defined concrete claims rather than an arbitrary map. We known the claims beforehand, so it'd be totatlly reasonable to start representing types like so.

```go
type EmailVerification struct {
	Issuer   string `json:"iss"`
	UserID   string `json:"sub"`
	Audience string `json:"aud"`
	Email    string `json:"http://coreos.com/email/verificationEmail"`
	Callback string `json:"http://coreos.com/email/verification-callback"`

	Iat      int64  `json:"iat"`
	Exp      int64  `json:"exp"`
}

func (e EmailVerification) IssuedAt() time.Time  { return time.Unix(e.Iat, 0) }
func (e EmailVerification) ExpiresAt() time.Time { return time.Unix(e.Exp, 0) }
```

`ParseAndVerifyEmailVerificationToken` can then parse out the struct from the JWT payload and verify that required fields are present. We then avoid a lot of arbitrary lookups, and interact better with square/go-jose.

**Comment by ericchiang** [comment]
cc @bobbyrullo @sym3tri I'm having trouble thinking of a way to update dex with https://github.com/coreos/go-oidc/pull/56. We now encode times as int64, but always decode numeric claims as float64. The tests are not happy.

Would love some thoughts on this.

**Comment by bobbyrullo** [comment]
@ericchiang I'll catch up with you on this tomorrow

**Comment by ericchiang** [comment]
Link to tests that are failing: https://gist.github.com/ericchiang/5d49573f30730918fe01633f95d78e47

**Comment by fnordahl** [comment]
I have tried to address this myself, at some point I came across this:
https://golang.org/pkg/encoding/json/#Decoder.UseNumber

Would it be possible to make the Dex JSON decoder do this? If we had numbers typed as Number interface instead of float64s we could use the numeric values as we wish later on throughout dex and not being forced to float64s.

**Comment by fnordahl** [comment]
Any thoughts on this @ericchiang @sym3tri @bobbyrullo ? I have identified some places where we could convert from float64 to int64 and make the tests pass, but it is currently not possible given the type used for the iat and exp.

**Comment by ericchiang** [comment]
We would have to construct claims to use json.Number as well during marshaling. Could be doable.

**Comment by fnordahl** [comment]
I believe I found a way to amend the remaining failing tests. Please have a look at #353
