### ISSUE TITLE
API Overview docs

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#427]
As has been pointed out in #380, Dex APIs are confusing, especially when it comes to figuring out what kind of authentication the various endpoints require. Furthermore, some APIs are defined in the JSON files, and others (ones that are defined by OIDC, OAuth2 specs) are not. 

We need a guide to the APIs which deals with all these things and lets people know:
1. Definitive list of APIs/endpoints
2. Links to docs for those endpoints
3. Detailed and authoritative authentication documentation.

**Comment by bobbyrullo** [comment]
Might be helpful for now: 
 
#467

**Comment by ericchiang** [comment]
closed via https://github.com/coreos/dex/pull/652
