### ISSUE TITLE
Dev guide updates

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#428]
Development on dex is getting complicated, with lots of unwritten rules, eg scripts that have to be run when you add DB fields, tables, files that have to be modified, etc. etc. Here's some things that need to be addressed - I'm sure there's more but this is off the top o' my head:
- Schema Updates (update tables, fields)
  - updating gorp models
  - add migrations (pg + sqllite)
  - run functional tests
- API Updates
  - updating JSON
  - running schema/generate
  - running go:update for docs
  - where to put tests
- Manager/Repo/API structure
  - justification (answers the question "This seems overly complicated - why worth it?")
  - responsiblity of manager vs repo
  - what we have vs what we want
- More???

**Comment by ericchiang** [comment]
"dev mode" is no longer a thing.
