### ISSUE TITLE
Add better tests for refresh token endpoints

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#431]
in user_api_test.go, there's one test for all the refresh token endpoints. There should be separate ones for List and Revoke. In addition these only test one instance of the happy path, just with different clients. We need to have tests for cases where the client doesn't exist, where the user doesnt; have a refresh token for the given client, etc, or where the user is trying access someone eles's tokens.

**Comment by ericchiang** [comment]
We now have integration testing for this.
