### ISSUE TITLE
API access token

### ISSUE THREAD

**Issue by chris-rock** [coreos/dex#441]
## Background

Dex as an Open ID Connect/Oauth2 server handles authentication for the user. At the moment, all issued tokens are optimized for UI driven flows. In order to be able to use access token for API consumption  e.g. via CLI, we need long-lived access tokens. Google calls those `API token`, Github `Personal token`
## Data Model

We can use the same access_token datamodel. Instead of issuing access token wir expiry dates, we allow long-lived access tokens as well.
## Data Storage

Long-lived access tokens (tokens without expiry dates) need to be stored in our database to ease the revocation process. The implementation of long-lived tokes would also require a full implementation of access token revocation flow.
## API
- Add new API endpoints that allow any logged-in user to see and generate new long-lived access token 
- Should be part of the admin api and behave similar to client registration
## UI/UX
- API is required
- UI is optional.
## Implementation

```
now := time.Now()
claims := oidc.NewClaims(s.IssuerURL.String(), user.ID, creds.ID, now, nil)
user.AddToClaims(claims)
```

We need to adapt https://github.com/coreos/go-oidc/blob/4ae1db46ec3e4dc8c30db43924c21e1600ba3400/oidc/util.go#L56-L65 to properly handle Claims without any expiry date.
## Security
- We need to ensure that long-lived access tokens cannot be created with simple access tokens via our api
- Admin API access should be required to add new tokens
- Access token revocation is required to revoke leaked tokens
## OIDC/OAUTH2
- [RFC7009 access token revokation](https://tools.ietf.org/html/rfc7009)
- https://dev.twitter.com/oauth/overview/faq
## Risks/Alternatives Considered

We could also use refresh tokens, but this requires backend components to know the OAuth2 exchange process.
## References

This is also related to #261

**Comment by bobbyrullo** [comment]
Hi chris - thanks for the proposal! We are doing similar work right now for supporting long-lived CLI access to Kubernetes clusters (see https://github.com/kubernetes/kubernetes/issues/18549#issuecomment-217308747 )

In your proposal are access tokens JWTs? If so, after they are revoked, how do client's know they have been revoked?

**Comment by bobbyrullo** [comment]
Also, it would be helpful for this proposal to outline the way the data flows - i.e. who requests the long lived token (and how), how do they use it, how is it validated.

**Comment by chris-rock** [comment]
@bobbyrullo Thanks for your quick feedback. I'll add a more detailed description over the next days. Lets continue the discussion once I added the flow.

**Comment by ericchiang** [comment]
Dex now uses a gRPC API with no authn or authz. https://github.com/coreos/dex/blob/master/Documentation/api.md

**Comment by chris-rock** [comment]
Thanks @ericchiang That is awesome

**Comment by pverschuure** [comment]
@chris-rock Did you manage to implement this long-lived API token? If so, what flow did you use? Asking because I am trying to accomplish the same thing.
