### ISSUE TITLE
msg_code not being passed on redirect

### ISSUE THREAD

**Issue by stongo** [coreos/dex#443]
Using latest master, I'm not sure if it's the case of the msg_code not being passed correctly, or there's an unneccesary 302 redirect, but after trying to login with a Google connector before registering, here are the ensuing requests made, with:

```
INFO: 127.0.0.1 - - [16/May/2016:10:03:37 -0400] "GET /auth?client_id=CLIENT_ID&msg_code=register-maybe&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin&register=1&scope=openid+offline_access&show_connectors=google&state=_XXXXXXXXX HTTP/1.1" 302 0
INFO: 127.0.0.1 - - [16/May/2016:10:03:37 -0400] "GET /auth?client_id=CLIENT_ID&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin&state=XXXXXXXXX&scope=openid%20offline_access HTTP/1.1" 200 36217
```

This ends up on the dex "home" screen with no error message.

As a somewhat separate issue, is there a way to disable registration per connector? Say if I wanted Google to not require Registration, but did want Local registration enabled.

**Comment by ericchiang** [comment]
> As a somewhat separate issue, is there a way to disable registration per connector? Say if I wanted Google to not require Registration, but did want Local registration enabled.

There's some discussion of this in #310.

For the actual bug report, which redirect are you talking about? Sorry, there are a lot of them.

What's the actual behavior you expect for the end user beyond HTTP headers not being passed on?

**Comment by stongo** [comment]
I'm not exactly sure why the 302 is happening in this case.
The expected behavior I'm looking for is to end up on the registration page with a message like 
```There's no account for this user.
Try registering with this first:```

**Comment by ericchiang** [comment]
I believe this was caused by https://github.com/coreos/dex/issues/370. Am investigating.

**Comment by stongo** [comment]
did some more debugging. here's what's happening:

1. Click "Login to Google" without registering first and select an account to attempt to login with
1. Google reports to `/auth/google/callback?state=XXX&code=4/XXX&authuser=0&hd=foo.net&session_state=XXX&prompt=none` which returns a 302
1. redirects to `/auth?client_id=XXX&msg_code=register-maybe&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin&register=1&scope=openid+offline_ac cess&show_connectors=google&state=XXX` which returns a 302
1. finally get redirected back to dex callback `http://localhost:5000/login?error=unsupported_response_type&state=XXX`

So the problem seems to be with the last `/auth` call that ends up redirecting back to dex callback with error query

**Comment by stongo** [comment]
It just so happened my callback would redirect right back to Dex on that error, so why I missed it

**Comment by ericchiang** [comment]
@stongo yeah I've got a half fix on a dex branch https://github.com/coreos/dex/tree/fix_remote_registration

There's an explanation of what's happening in an inline comment.

That gets us to "you don't have an account, try registering" but the registration button still doesn't work.

**Comment by stongo** [comment]
the registration button isn't working because `response_type` query is empty. looking at it now

**Comment by bobbyrullo** [comment]
@stongo I think the thing to do is revert #375, and reintroduce the desired changes from it without the confusing refactoring, which I am in the process of doing as we speak.

**Comment by stongo** [comment]
So this fixes the first issue that @ericchiang already fixed, but still does not allow subsequent registration after trying to login. 
Still get `ERROR: Invalid auth request: no response_type provided` 
This issue can probably still be re-opened, and I'll work on a fix from master now

**Comment by bobbyrullo** [comment]
Hmph. You're working from master right stongo?

**Comment by bobbyrullo** [comment]
I can't reproduce @stongo  - could you tell me the exact flow?

**Comment by stongo** [comment]
@bobbyrullo:
1. attempt to login to google connector without registering first
1. get redirected back to `/auth` and receive message `There's no account for this user. Try registering with this first:` and then click `Use Google` button
1. get redirected back to my API with error

Dex Logs:
```
INFO: 127.0.0.1 - - [17/May/2016:18:57:18 -0400] "GET /auth?client_id=XXXXX&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin&state=XXXXXX&scope=openid%20offline_access HTTP/1.1" 200 36217
INFO: Session jbGGjIchCZw= created: clientID=XXXXXXX clientState=XXXXXX
INFO: 127.0.0.1 - - [17/May/2016:18:57:21 -0400] "GET /auth?client_id=XXXXX&connector_id=google&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin&response_type=code&scope=openid+offline_access&state=XXXXXX HTTP/1.1" 302 0
INFO: Session jbGGjIchCZw= remote identity attached: clientID=XXXXXXX identity=oidc.Identity{ID:"XXXXXXXX", Name:"", Email:"stongo@gmail.com", ExpiresAt:time.Time{sec:63599126244, nsec:0, loc:(*time.Location)(0x4b13c00)}}
INFO: 127.0.0.1 - - [17/May/2016:18:57:24 -0400] "GET /auth/google/callback?state=XXXXXXX&code=4/XXXXXXX&authuser=0&hd=gmail.com&session_state=XXXXXXX&prompt=none HTTP/1.1" 302 0
INFO: 127.0.0.1 - - [17/May/2016:18:57:24 -0400] "GET /auth?client_id=XXXXX&msg_code=register-maybe&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin&register=1&scope=openid+offline_access&show_connectors=google&state=XXXXXX HTTP/1.1" 200 35385
ERROR: Invalid auth request: no response_type provided
INFO: 127.0.0.1 - - [17/May/2016:18:57:27 -0400] "GET /auth?client_id=XXXXX&connector_id=google&msg_code=register-maybe&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin&register=1&response_type=&scope=openid+offline_access&show_connectors=google&state=XXXXXX HTTP/1.1" 302 0
```

API log:
```
 get /login {"error":"unsupported_response_type","state":"XXXXXX"}
```

**Comment by stongo** [comment]
@bobbyrullo derp, you were right, master does work. I had fubared my fork master today, hence not working. Thanks for fixing and sorry for wasting your time at the end there :)

**Comment by bobbyrullo** [comment]
Phew! No worries, glad it works!
