### ISSUE TITLE
Release images on quay are manually tagged

### ISSUE THREAD

**Issue by chancez** [coreos/dex#452]
https://quay.io/repository/coreos/dex?tab=tags

This release was put out last month and I'm not seeing a semver tagged release in quay though. It does seem that ea4c04fde83bd6c48f4d43862c406deb4ea9dba2 (the commit v0.4 is at) exists though.

**Comment by ericchiang** [comment]
I've gone ahead and added the tag.

Going to keep this issue open. We either need to add a comment to the release guide or have some job trigger (probably travis) when we publish a release.
