### ISSUE TITLE
Verify link invalid/expired bad UI experience

### ISSUE THREAD

**Issue by jonnenauha** [coreos/dex#456]
I think we are getting into issues that people create our dex account, then receive the verification link to their email. If they come few days later to click that link and want to proceed to use our site, they get this.

![image](https://cloud.githubusercontent.com/assets/157519/15855931/2b9616b2-2cbb-11e6-9dfa-b42a310f8b46.png)

I think this page should give a common sense error and provide a link where you can request a new verification link to your email. I'm not sure if there even exists such a page at the moment? If not it should be created. Easy to access page that my service can redirect to or you can use internally like `/verify/resend`. Just a simple page with a field to input your email and a send button. After send is clicked, some text should appear `Link sent, please check your inbox at <given email>`

The above screenshot page could look something like this instead of obscure "hard to read" technical error. As this page is user facing, not developer facing.

```
This verification link is not valid or has expired.

<a href="/verify/resend">Click here to send a new verify link</a>
```

**Comment by ericchiang** [comment]
Dex no longer uses SMTP settings to send mail. This should be handled by an external app.
