### ISSUE TITLE
Public Clients

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#469]
Proposal
===

## Background

Sometimes authentication needs to be initiated from an application that cannot be trusted to keep the client_id/client_secret pair secret - Mobile phone applications and command line tools are two examples. 

To support this usage we will introduce a new type of client called "public client". A public client is just like a "normal" client with a couple of restrictions:

1. The only valid redirect URLs are urn:ietf:wg:oauth:2.0:oob or localhost:XXXX. We expect and plan to use public clients in conjunction with cross-client authentication; eg. a public client could be a trusted peer of some web app, allowing it to mint tokens for that app. Without this restriction, the trusting peer would be vulnerable to bad actors using these credentials to create phishing sites to get credentials for the trusting peer.

1. The `/token` endpoint will not grant a client credentials JWT for native clients - since the client id and client secret are public, it doesn't make sense for an IdP to mint a token asserting the authenticity of the client.

## Data Model

A new field `public bool` will be added to the `Client` struct.

## Data Storage

A corresponding field will be added to the backend DB.

## API

We need to modify `Server.CodeToken()` to disallow `ClientCredentials` grant type.

We need to modify the bootstrap client creation API to accommodate creating public clients.

## UI/UX

None.

## Implementation

In addition the above data model, data storage and API changes, we need to add the OOB authentication option, for when there's not a server on localhost.

## Security

The biggest security risk I can imagine is some unforeseen interaction with public clients and some other dex API that uses client credentials somehow. This is why [certain APIs were recently removed](https://github.com/coreos/dex/issues/467), and why we are disallowing minting of client credential JWTs for public clients.

## OIDC/OAUTH2

Not exactly.

## Risks/Alternatives Considered

The downside is mainly the complexity and giving users yet another way to shoot themselves in the foot; I'm worried for instance that someone will use cross-client auth on an installed app and *not* use this feature.

## References

Inspired by https://developers.google.com/identity/protocols/OAuth2InstalledApp

**Comment by ericchiang** [comment]
Yep, this works for me.
