### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#473]
There are a bunch of logging statements that make no sense and need to be removed or clarified. For example:

```
ERROR: IDENTITY: err: <nil>
```

**Comment by sym3tri** [comment]
Another problem that has arisen is not enough log statements when things are not working as expected, making dex hard to troubleshoot.

Logging need to be cleaned up in general. We've been using logrus in other projects and are happy with it so far. https://github.com/Sirupsen/logrus

**Comment by ericchiang** [comment]
Okay. Going to bump the priority and assign to the next milestone.

**Comment by ericchiang** [comment]
This has largely been address. Though we don't use logrus, we do log a lot more meaningful errors.
