### ISSUE TITLE
Cannot set emailVerified via admin API when creating user

### ISSUE THREAD

**Issue by chancez** [coreos/dex#498]
When using the admin API to create a new it isn't currently possible to manually set the emailVerified state. Since the user isn't being created via a normal invite, it would be useful to set this value in the API call. 

There might be cases where we want this set and unset when creating users, so it would be ideal if we could specify the value.

**Comment by ericchiang** [comment]
Would it be reasonable to default this field to true? If you're going through the bootstrapping API I don't see a reason this wouldn't be the case. You'd just send an email invite otherwise.

**Comment by chancez** [comment]
I don't necessarily think that's the case. You might want to create the user via the admin API because you want to control what the password is set to, but still invite them, but do the invite out of band from Dex.

**Comment by ericchiang** [comment]
I think the only way to do the invite is for that call to create the user. So that flow may not work.

**Comment by chancez** [comment]
@ericchiang which is why i said out of band invitation (and in the future we should support inviting users who are already created).

**Comment by ericchiang** [comment]
Right, but for now would it unblock you to default this field to "true"?

**Comment by sym3tri** [comment]
If an admin can set the flag to true then the email is not actually
verified. I could see this causing a lot of confusion. If you really need a
workaround I would prefer another explicit field "bypassEmailVerification"
or something. But I don't fully understand why you need this.

**Comment by chancez** [comment]
@sym3tri The case is when we're creating the initial admin user in Tectonic. Today if you login to the console it shows the user as "invited" because their email isn't verified, since the create user via the admin API uses the same plumbing as the invite user endpoint in the worker API. In this particular case, we're an admin creating our own admin account, so we know the email is verified.

**Comment by sym3tri** [comment]
I see. I understand the need to bypass email verification for an initial user, but a field named `email_verified` indicates that the process of email verification took place and was completed successfully (via a challenge email being sent). This is distinct from "i dont care about email verification". These are different pieces of information so IMO they should be tracked separately.

So I still think this makes sense as a new field. Maybe `bypass_email_verification` and it defaults to false unless explicitly enabled when users are created via the admin API.

**Comment by ericchiang** [comment]
Emails are now assumed to be valid if they're local. It's up to an outside process to validate them.
