### ISSUE TITLE
Skip local login page if already logged in

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#5]
<a href="https://github.com/bcwaldon"><img src="https://avatars.githubusercontent.com/u/548759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcwaldon](https://github.com/bcwaldon)**
_Wednesday Nov 26, 2014 at 23:42 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/106_

----

The local IDPC always requires you to login regardless of the current state of the user. Ideally, a user would be identified as already logged in and could be redirected either back to their third-party app or to an authd landing page.

**Comment by ericchiang** [comment]
going to move this issue to #5
