### ISSUE TITLE
Users with unverified emails are never cleaned up

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#50]
<a href="https://github.com/sym3tri"><img src="https://avatars.githubusercontent.com/u/224222?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sym3tri](https://github.com/sym3tri)**
_Monday Aug 03, 2015 at 23:21 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/352_
---

Consider this case:

1) Some joker named Mr. Bar tries to register with `foo@foo.com`. He is not the rightful owner of the email address so he can't verify it. Mr. Foo (the rightful owner of `foo@foo.com`) ignores the email.

2) Some time later Mr. Foo tries to register with foo@foo.com, but cannot register b/c that email is already registered. The email will stay in the unregistered state forever. Mr. Foo is sad b/c he cannot register.

Currently there is a workaround which Mr. Foo may not know about:
1) click "login" instead of "register"
2) click "forgot password"
3) send reset password link
4) click link & reset password
5) hopefully the client app prompts him to verify his email before continuing, if not his email will never be verified.

**Comment by ericchiang** [comment]
Also might be nice for users to only be created once the email verification link has been visited.

**Comment by ericchiang** [comment]
There's no registration for the current dex. This would be handled by an app talking to the gRPC API,
