### ISSUE TITLE
Send an email using https server fail

### ISSUE THREAD

**Issue by rsoletob** [coreos/dex#503]
When we create an user or resend a invitation dex show this error, but request finishes with 200 code:

ERROR: error sending password reset email x509: failed to load system roots and no roots provided:

We are using this docker image:
```
FROM quay.io/coreos/dex:latest
ENV DEX_PREFIX /opt/dex

ADD emailer.json $DEX_PREFIX/static/fixtures/emailer.json

ADD dexPub.pem $DEX_PREFIX/tls-setup/certs/dexPub.pem
ADD dexPriv.pem $DEX_PREFIX/tls-setup/certs/dexPriv.pem

ADD env.txt $DEX_PREFIX/static/fixtures/env.txt

ADD worker_secret.dat $DEX_PREFIX/worker_secret.dat
ADD admin_api_secret.dat $DEX_PREFIX/admin_api_secret.dat

ADD entrypoint.sh $DEX_PREFIX/entrypoint.sh
RUN chmod +x $DEX_PREFIX/entrypoint.sh
RUN chmod 600 $DEX_PREFIX/admin_api_secret.dat
RUN chmod 600 $DEX_PREFIX/worker_secret.dat

EXPOSE 5556 5557

ENTRYPOINT ["/opt/dex/entrypoint.sh"]
```
This happen because the container doesn't have the root certificates. To fix it we add this lines to docker image:

```
ADD certs /etc/ssl/certs
ADD certs /system/etc/security/cacerts
```

However, we believe this is not the ideal solution, since we're manually copying the ca-certificates on our host machine, to the docker image.

We think it's better using Alpine hub base image alpine:3.3 or latest, instead of quay.io/..../corebox, because you could download ca certificates with `apk add ca-certificates`.

**Comment by sym3tri** [comment]
The recommended approach here would be to mount in `/etc/ssl/certs` into the container as a volume when you run it. I don't think we want to take on the burden of keeping certs up-to-date inside the dex containers we ship.

**Comment by sym3tri** [comment]
Are you using the mailgun emailer or SMTP?

**Comment by rsoletob** [comment]
We use SMTP. Thanks for your response. We will use your suggestion.

**Comment by ericchiang** [comment]
It's been discussed to switch to the Alpine image on Docker hub. So we may still do this.
