### ISSUE TITLE
Strange flow when using back-arrow button on browser and session_key has been alredy validated

### ISSUE THREAD

**Issue by mariopolo2805** [coreos/dex#505]
I will describe the flow to reproduce this scenario:
- Start a local client and local worker
- Go to **Login** page with email (`connector_id=local`)
- Click on **Restore Password** and go back with browser arrow-back
- At this momment, the _session_key_ has been alredy validated, so if you click whatever option (login or restore), respond will be like:

> {"error":"invalid_request","error_description":"missing required parameters"}

It would be a good idea to generate an **Error Page** to handle this situation.

_Note: In this other [issue](https://github.com/coreos/dex/issues/355) could be happening a similar behavior_

**Comment by blingwang** [comment]
Is there any reason why dex uses auth session to store the user data instead of passing them in the urls(login, register, forgot password)? Users cannot reuse those urls once the session key is validated and session is killed. This feels strange for end users.

**Comment by ericchiang** [comment]
@blingwang I believe it's used to track some information about what stage of the flow you're in. But yeah we should probably just move some of these values to the URLs.

**Comment by ericchiang** [comment]
This has largely been fixed in dex v2. Closing for now.
