### ISSUE TITLE
LDAP Connector ERROR: handling identity, but example app auth succeeds

### ISSUE THREAD

**Issue by rudyzhou2** [coreos/dex#506]
Hi dex dev,

I am currently testing out dex and encountered this issue while using the example app with LDAP connector. I was able to log in and obtain token from the fake email handler but worker debug log shows the following error. Is there anyway to get even more debug out to figure out why exactly I am encountering this error output?
 
```
INFO: 127.0.0.1 - - [06/Jul/2016:16:01:03 -0700] "GET /auth/ldap/callback/login?prompt=&session_key=05W7UWD9DpM%3D HTTP/1.1" 200 25382
ERROR: handling identity
INFO: Session ITMHm4wDaps= remote identity attached: clientID=hVXygBRxN5YgNo0-Gbs3iaGAksmTu_YeTS4pG8tftf4=@127.0.0.1 identity=oidc.Identity{ID:"uid=tuser,ou=users,dc=dex,dc=ca", Name:"Test User", Email:"test@xxxx.ca", ExpiresAt:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}
INFO: Session ITMHm4wDaps= user identified: clientID=hVXygBRxN5YgNo0-Gbs3iaGAksmTu_YeTS4pG8tftf4=@127.0.0.1 user=user.User{ID:"8730c7d1-8560-4565-87ce-35a9c6076876", DisplayName:"", Email:"test@xxxx.ca", EmailVerified:true, Admin:false, Disabled:false, CreatedAt:time.Time{sec:63603428663, nsec:0, loc:(*time.Location)(0xfd84c0)}}
INFO: 127.0.0.1 - - [06/Jul/2016:16:01:07 -0700] "POST /auth/ldap/callback/login?prompt=&session_key=05W7UWD9DpM%3D HTTP/1.1" 302 0
```

**Comment by ericchiang** [comment]
@rudyzhou2 sorry for the delayed response. I've been out of the office for a week.

Can you provide the connector config JSON? Also what version (or checkout) of dex are you using?

**Comment by rudyzhou2** [comment]
Hi @ericchiang,

No problem!

`[
    {
        "type": "ldap",
        "id": "ldap",
        "host": "172.17.0.9:389",
	"useTLS": false,
	"useSSL": false,
        "baseDN": "ou=users,dc=dex,dc=ca",

        "searchBeforeAuth": true,
        "searchFilter": "(&(objectClass=posixAccount)(uid=%u))",
        "searchScope": "sub",

        "searchBindDN": "cn=readonly,dc=dex,dc=ca",
        "searchBindPw": "readonly"
    }
]`

`
dex version 0.5.1
go version 1.5.3
`

**Comment by rudyzhou2** [comment]
And here is the commit

```
commit f816cfb1876f9228483c38d1a1e05e7c31aac801
Merge: 84f36b1 e22829c
Author: Eric Chiang <eric.chiang.m@gmail.com>
Date:   Thu Jun 30 15:48:26 2016 -0700

    Merge pull request #499 from samueldg/fix_docs_typos
    
    docs: fix various typos & Markdown lint issues
```

**Comment by ericchiang** [comment]
This looks like an erroneous logging statement[0]

To be clear you're not actually experiencing errors, you're only seeing that logging statement?

[0] https://github.com/coreos/dex/blob/f816cfb1876f9228483c38d1a1e05e7c31aac801/connector/connector_ldap.go#L443

**Comment by rudyzhou2** [comment]
Hi Eric,

Yes it seems like the I am only seeing the logging statement with no issues on auth. I will try the new commit and report back asap!

Thanks!

Cheers,

Rudy
