### ISSUE TITLE
Config: Support YAML so we can provide examples with inline comments

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#516]
Big confutation files like the LDAP connectors are hard to navigate and it's annoying that we can't put comments in the actual config files. Would be really nice if we could provide inline comments.

**Comment by roidelapluie** [comment]
Please not that JSON is a subset of Yaml, so enabling only yaml should be json compatible

**Comment by jostyee** [comment]
IMO [toml](https://github.com/toml-lang/toml) is a better choice, which is insensitive to indentation.

**Comment by ericchiang** [comment]
YAML was proposed because it's backward compatible with JSON. I don't think we can adopt TOML for master because of backward compatibility issues, but will consider it for v2.

**Comment by ericchiang** [comment]
This is now supported.
