### ISSUE TITLE
Error running the example application 

### ISSUE THREAD

**Issue by l0n3r4n83r** [coreos/dex#525]
Hi I am following the getting started guide using the standup-db.sh script. But I see the following error when I try to run the example application.

INFO: 127.0.0.1 - - [28/Jul/2016:14:09:38 -0700] "GET /.well-known/openid-configuration HTTP/1.1" 404 19
ERROR: Failed fetching provider config, trying again in 3s: json: cannot unmarshal number into Go value of type oidc.encodableProviderConfig

**Comment by ericchiang** [comment]
Sorry, #521 broke this. The discovery URL here[0] needs to be `http://127.0.0.1:5556/dex`.

[0] https://github.com/coreos/dex/blob/d1bb106f94e65860fe46efcaddd3da32c6340ce1/contrib/standup-db.sh#L82

**Comment by l0n3r4n83r** [comment]
Thanks for the quick response may be we can merge this

https://github.com/coreos/dex/pull/526
https://github.com/coreos/dex/pull/526/commits/b42398d3ab1db30f7957cc9db4344c5dc71c415e

**Comment by ericchiang** [comment]
Closing now that #526 is in
