### ISSUE TITLE
Allow admin clients to create users

### ISSUE THREAD

**Issue by adrianlop** [coreos/dex#528]
Hi,

This is the discussion on google group:
https://groups.google.com/forum/#!topic/dex-dev/KWmif8CiCYE

**Comment by ericchiang** [comment]
Going to post my comment from that thread here

> However, the current API requires both an admin client and admin user, and client_credentials only proves the admin client part so I don't know if it's an appropriate replacement.

If you want to add this, it's got to be feature flagged.

**Comment by adrianlop** [comment]
ok, thanks! I added the flag in the PR
