### ISSUE TITLE
Add support for federating to Cloud Foundry UAA

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#538]
Add a connector for logging in with Cloud Foundry UAA. Will probably look something like the current bitbucket connector[0] since we've been told that UAA supports some flavor of OAuth2.

cc @jbowen93 @whitlockjc

[0] https://github.com/coreos/dex/blob/master/connector/connector_bitbucket.go

**Comment by whitlockjc** [comment]
I'll get cracking on this.
