### ISSUE TITLE
Update roadmap for 0.5+ release cycle

### ISSUE THREAD

**Issue by glerchundi** [coreos/dex#539]
If it's possible I would like to know which are the short, mid and long term features you guys have planned to include in `dex`.

By the way is there any blocker features that made impossible to finally cut a stable and production-ready release?

Thanks!

**Comment by ericchiang** [comment]
We're currently working on some POCs to resolve some long standing architectural issues. The two binary deployments, storage interface complexity, etc, and hope to open source that work some time next week to accompany a demo in the [Kubernetes weekly community meeting](https://github.com/kubernetes/community/blob/master/community/README.md).  Those are the main blockers for us committing to a stable, long term release.

**Comment by glerchundi** [comment]
Cool, thanks! :)

**Comment by ericchiang** [comment]
We've now moved to milestones.
