### ISSUE TITLE
Immediate redirect to login form if certain conditions are met

### ISSUE THREAD

**Issue by roidelapluie** [coreos/dex#547]
If all of the following conditions are met:
- There is only one provider
- The login with that provider is fully managed by DEX  (local, LDAP)

Then:
- The welcome page should be skipped and the user should directly arrive to the provider's login page

**Comment by ericchiang** [comment]
Agree with the statement. Can you expand what you mean by "fully managed by DEX"?

**Comment by roidelapluie** [comment]
fully managed by DEX means "dex has a login form for that". In other words, it should transparently redirect you to the login form directly.

When there is no login form, I do not think that Dex should redirect you to another website without your consent.

**Comment by ericchiang** [comment]
okay cool. thanks for clarifying.

**Comment by ericchiang** [comment]
Dex now implements this behavior.
