### ISSUE TITLE
Ask user consent

### ISSUE THREAD

**Issue by roidelapluie** [coreos/dex#550]
When an app asks for claims like: groups, I expect DEX to provide the user the list of the claims and the user to have to "agree" with that list.

Also, I expect the email to be a claim that needs to explicitely be asked by the client and that the user can allow or deny access to that claim.

We could have a claims.json:

```
{
"groups": "Get access to your groups",
}
```

**Comment by ericchiang** [comment]
We really don't want to add more config files to dex, but yeah a consent screen is something we should add.

**Comment by roidelapluie** [comment]
The config is optional ; it is just for a better ui.

**Comment by ericchiang** [comment]
This has been added to newer versions of dex.
