### ISSUE TITLE
Registration handler doesn't take full issuer URL into account

### ISSUE THREAD

**Issue by pborzenkov** [coreos/dex#553]
Here is the problem in handleAuthFunc() function:

```
if register {
	_, ok := idpc.(*connector.LocalConnector)
	if ok {
		q := url.Values{}
		q.Set("code", key)
		ru := httpPathRegister + "?" + q.Encode()
		w.Header().Set("Location", ru)
		w.WriteHeader(http.StatusFound)
		return
	}
}
```

It always redirects to httpPathRegister ("/register") w/o using issuerURL. So it's impossible to register a new user if dex is listening on a non-root path.

**Comment by ericchiang** [comment]
Thanks for reporting. There were a ton of these small bugs found since putting in the effort to move away from root paths.
