### ISSUE TITLE
migrate from semaphore to jenkins

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#57]
<a href="https://github.com/bcwaldon"><img src="https://avatars.githubusercontent.com/u/548759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcwaldon](https://github.com/bcwaldon)**
_Thursday Aug 06, 2015 at 22:25 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/359_

----

**Comment by heckj** [comment]
@bcwaldon out of curiosity, why switch from semaphore to jenkins?

**Comment by bcwaldon** [comment]
@heckj Hi, Joe!

We have had a lot of issues with all hosted CI systems, not just semaphore, when it comes to automating docker builds. We haven't found something that provides a good experience around the multi-step build/test/publish process, where multiple calls to a docker daemon are required.

Semaphore, for example, doesn't actually have a public docker environment. One of our developers has been blessed with some special power to create projects with a "beta" docker environment. We're also still stuck writing a bash script, which is what I'm used to with Jenkins, but now I have *no* idea what I can trust to be on the build slave and I have no real power to debug and fix it when I run into issues (docker running hosts out of space, for example).

We are more than capable of running Jenkins, we just haven't had the time to get it properly configured. We have it running dex functional tests in our private instance, but ideally this is visible to the public.

**Comment by JasonGiedymin** [comment]
Here here. I've resorted to the same with my projects of which build dockers in composition (+ release triggers).

**Comment by heckj** [comment]
@bcwaldon Hey Brian! Thanks - makes sense. 

I still haven't shifted to building docker (or other container) images for anything I'm building directly yet. Are the relevant scripts in this repo? I'm kind of curious to see what you're doing and how you're doing it, just to keep up a bit. Or can you point me at a sample GIST or somethat that has the rough script?

**Comment by bobbyrullo** [comment]
@heckj :This is the Jenkins build script gist - all sub-scripts mentioned are in the root level of the repo:

https://gist.github.com/bobbyrullo/84cd5f0f24f68b1f3175

**Comment by ericchiang** [comment]
we're using travis for the foreseeable future.
