### ISSUE TITLE
Support of expires_in field in Token endpoint

### ISSUE THREAD

**Issue by summerwind** [coreos/dex#574]
dex does not return a *expires_in* field from Token endpoint. The spec of OpenID Connect allowed to use *expires_in* fields in a response of Token Endpoint. 
http://openid.net/specs/openid-connect-core-1_0.html#TokenResponse

ReuseTokenSource of `golang.org/x/oauth2` supports *expires_in* field to enable refreshing token automaticaly. 
https://github.com/golang/oauth2/blob/master/internal/token.go#L194

I'd like to add the support of *expires_in* field. Thought?
(I already wrote a patch!)

**Comment by ericchiang** [comment]
Surprised we don't do this already. Yes please, do send in that patch.

**Comment by summerwind** [comment]
@ericchiang Thank you for the quick response!
I sent my patch in #575.

**Comment by summerwind** [comment]
Landed in 9a78dca137c48a1e1fb64de2b59488b476ffdb3d. Thank you for the support!

**Comment by ericchiang** [comment]
Thanks for the work! Think it'll be reasonable to do a release later this week. This seems big enough to warrant one with some other work that's gone in.

**Comment by summerwind** [comment]
Great to hear that!
