### ISSUE TITLE
server: limit the number of (refresh) tokens for each user-client pair

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#60]
<a href="https://github.com/yifan-gu"><img src="https://avatars.githubusercontent.com/u/3278588?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yifan-gu](https://github.com/yifan-gu)**
_Monday Aug 17, 2015 at 18:19 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/365_

---

For example, google has a limit of 25 for per user https://developers.google.com/identity/protocols/OAuth2#expiration

**Comment by ericchiang** [comment]
I think this should be configurable. I'd like to see an implementation where we only allow a single refresh token per client/user/scopes tuple.

**Comment by ericchiang** [comment]
@rithujohn191 closed, right?

**Comment by rithujohn191** [comment]
yes closed by #793
