### ISSUE TITLE
connector/github: config should take API endpoints

### ISSUE THREAD

**Issue by moserke** [coreos/dex#622]
In order to support github enterprise, the github connector should take the API endpoints as optional parameters.  This would allow enterprise users to use their internal github to do oAuth

**Comment by ericchiang** [comment]
What are the OAuth2 token and auth endpoints for GitHub enterprise? The public ones are:

```
https://api.github.com
https://github.com/login/oauth/access_token
https://github.com/login/oauth/authorize
```

Can enterprise ones similarly be derived given a hostname?

**Comment by moserke** [comment]
It is the same api: https://developer.github.com/enterprise/2.7/v3/oauth/.  That's for 2.7 which is the version we are running.  2.8 is the current.

I believe it's simply as simple as just changing out the protocol/hostname.
