### ISSUE TITLE
random blocks in contrib/standup-db.sh

### ISSUE THREAD

**Issue by dholth** [coreos/dex#643]
The method used to generate a random key was blocking in my VM. Python can be used instead:

`DEX_KEY_SECRET=$(python -c "import os; print(os.urandom(32).encode('base64').replace('\n', ''))")`
`DEX_OVERLOAD_ADMIN_API_SECRET=$(python -c "import os; print(os.urandom(128).encode('base64').replace('\n', ''))")`

**Comment by ericchiang** [comment]
Any idea why the bash command wasn't working? What OS?

Feel free to send a patch but it'll have to work with python3 as well.

**Comment by dholth** [comment]
Looks like the 2+3 version would be

`import os, codecs; print(codecs.encode(os.urandom(128), 'base64').decode('utf8').replace('\n', ''))`

**Comment by dholth** [comment]
/dev/random can block if the kernel thinks it does not have enough random bits. This is a bigger problem on virtual machines. Another solution would be to read from /dev/urandom

**Comment by ericchiang** [comment]
> Another solution would be to read from /dev/urandom

Let's do that. Go even uses `/dev/urandom`[0] so it doesn't seem like we're sacrificing cryptographic integrity. 

[0] https://github.com/golang/go/blob/go1.7.3/src/crypto/rand/rand_unix.go#L23

**Comment by ericchiang** [comment]
With v2, this script is no longer part of master. Closing for now.
