### ISSUE TITLE
Cannot login with test-openldap docker image

### ISSUE THREAD

**Issue by ozanichkovsky** [coreos/dex#644]
I've tried to use https://github.com/rroemhild/docker-test-openldap as a LDAP server for testing whether dex allows to login using LDAP.

This is my connectors.json file.

`[
  {
    "type": "ldap",
    "id": "ldap",
    "host": "ldap:389",
    "useTLS": false,
    "useSSL": false,
    "skipCertVerification": false,
    "baseDN": "ou=people,dc=planetexpress,dc=com",
    "nameAttribute": "cn",
    "emailAttribute": "mail",
    "searchBeforeAuth": true,
    "searchFilter": "(mail=%u)",
    "searchScope": "sub",
    "searchBindDN": "cn=admin,dc=planetexpress,dc=com",
    "searchBindPw": "GoodNewsEveryone",
    "bindTemplate": "uid=%u,%b"
  }
]`

But I just get "Invalid login" message when I try to login as any of the users provided in the image.

Am I doing something wrong?

**Comment by ericchiang** [comment]
Can you provide the logs for your dex worker?

**Comment by ozanichkovsky** [comment]
INFO: Debug logging enabled.
DEBUG: Debug logging enabled.
WARN: Running with no limit on: database idle connections
WARN: Running with no limit on: database open connections
ERROR: No connectors, will wait. Retrying in 1s.
WARN: bindTemplate not used when searchBeforeAuth specified.
INFO: Loaded IdP connector: id=ldap type=ldap
INFO: Binding to 0.0.0.0:5556...
INFO: 172.18.0.6 - - [29/Oct/2016:16:09:13 +0000] "GET /dex/.well-known/openid-configuration HTTP/1.1" 200 446
INFO: 172.18.0.6 - - [29/Oct/2016:16:09:13 +0000] "GET /dex/.well-known/openid-configuration HTTP/1.1" 200 446
INFO: 10.0.2.2 - - [29/Oct/2016:16:13:42 +0000] "GET /dex/auth?client_id=R6UHHLy68BxbOqoOBcYGFfsdYTXDFMLssVdowRev1Nc%3D%40127.0.0.1&redirect_uri=http%3A%2F%2F127.0.0.1%3A5555%2Fcallback&response_type=code&scope=openid+email+profile+offline_access&state= HTTP/1.1" 200 25246
INFO: 10.0.2.2 - - [29/Oct/2016:16:13:43 +0000] "GET /favicon.ico HTTP/1.1" 404 19
INFO: 10.0.2.2 - - [29/Oct/2016:16:13:43 +0000] "GET /favicon.ico HTTP/1.1" 404 19
INFO: Session J_K4Tek2Un0= created: clientID=R6UHHLy68BxbOqoOBcYGFfsdYTXDFMLssVdowRev1Nc=@127.0.0.1 clientState=
INFO: 10.0.2.2 - - [29/Oct/2016:16:13:44 +0000] "GET /dex/auth?client_id=R6UHHLy68BxbOqoOBcYGFfsdYTXDFMLssVdowRev1Nc%3D%40127.0.0.1&connector_id=ldap&redirect_uri=http%3A%2F%2F127.0.0.1%3A5555%2Fcallback&response_type=code&scope=openid+email+profile+offline_access&state= HTTP/1.1" 302 0
INFO: 10.0.2.2 - - [29/Oct/2016:16:13:44 +0000] "GET /dex/auth/ldap/callback/login?prompt=&session_key=iVWH2MzkNRA%3D HTTP/1.1" 200 25390
INFO: Session J_K4Tek2Un0= remote identity attached: clientID=R6UHHLy68BxbOqoOBcYGFfsdYTXDFMLssVdowRev1Nc=@127.0.0.1 identity=oidc.Identity{ID:"cn=Philip J. Fry,ou=people,dc=planetexpress,dc=com", Name:"Philip J. Fry", Email:"fry@planetexpress.com", ExpiresAt:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}
INFO: 10.0.2.2 - - [29/Oct/2016:16:13:54 +0000] "POST /dex/auth/ldap/callback/login?prompt=&session_key=iVWH2MzkNRA%3D HTTP/1.1" 302 0
INFO: 10.0.2.2 - - [29/Oct/2016:16:13:55 +0000] "GET /dex/auth?client_id=R6UHHLy68BxbOqoOBcYGFfsdYTXDFMLssVdowRev1Nc%3D%40127.0.0.1&msg_code=register-maybe&redirect_uri=http%3A%2F%2F127.0.0.1%3A5555%2Fcallback&register=1&scope=openid+email+profile+offline_access&show_connectors=ldap&state= HTTP/1.1" 200 25470

![capture](https://cloud.githubusercontent.com/assets/634781/19831189/971f9288-9e0c-11e6-9f86-739c4f57d9bf.PNG)

I tried to login as fry@planetexpress.com with 'fry' password'.

**Comment by ozanichkovsky** [comment]
Ah, I found out what I was doing wrong. I forgot about registering user with LDAP first.
