### ISSUE TITLE
The right way to add users with registration disabled.

### ISSUE THREAD

**Issue by ozanichkovsky** [coreos/dex#653]
I have a question.

What is the right way to add users (LDAP for example) without registering them first?

Should the be added to some table in postgres DB?

Thank you,
Oleksandr

**Comment by ericchiang** [comment]
Is `--enable-automatic-registration` what you're looking for?

**Comment by ozanichkovsky** [comment]
Thanks, I'll try it.

31 жовт. 2016 р. 18:58 "Eric Chiang" <notifications@github.com> пише:

**Comment by ericchiang** [comment]
Okay. Closing for now. Please ping if you have further issues.
