### ISSUE TITLE
server: error HTML templates

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#657]
Right now they're just plain text.

**Comment by rithujohn191** [comment]
TODO: Provide more meaningful error description messages.

**Comment by robszumski** [comment]
![pasted image at 2016_12_14 10_14 am](https://cloud.githubusercontent.com/assets/755540/21194911/8d57c5f6-c1e6-11e6-8a2a-ec1b8d513ab5.png)

**Comment by ericchiang** [comment]
"Back to login form" might not be possible. There are states in dex's login flow that don't transition backwards very well if the current step fails. For example if the user comes back from google with a state token that's expired we have no way of mapping that info back to the login session.

We're aiming at cleaning up a bit of the logic. See discussion in https://github.com/coreos/dex/issues/646 and https://github.com/coreos/dex/issues/549. I think it's definitely a good aim but step 1 is providing a rendered page an a good message like "Failed to connect to database." Step 2 is trying to work out how to provide a link to a useful page.

**Comment by robszumski** [comment]
Thats fine. We should strive to get folks back to the form if we can. Won't it always be safe to punt you back out to the provider picker?

**Comment by ericchiang** [comment]
> Won't it always be safe to punt you back out to the provider picker?

No. For example, you can't navigate to the provider picker screen directly, you need all the OAuth2 metadata generated by the client's initial redirect (state, redirect_uri, etc). If we loose that information because of an error, or determine that that info is invalid we can't recreate those parameters.

**Comment by ericchiang** [comment]
The safer thing might be to redirect back to the client with an error.

**Comment by robszumski** [comment]
We can't just kick you to the root URL, as if you had never interacted with dex before?

**Comment by ericchiang** [comment]
> We can't just kick you to the root URL, as if you had never interacted with dex before if you click the button?

No. Dex only works when clients initialize the OAuth2 flow. If you just show up at the root URL we don't know which client to redirect you after.
