### ISSUE TITLE
Documentation: connector documentation

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#678]
We need to add documentation on the LDAP, GitHub, and OpenID Connect connectors. LDAP is the highest priority.

**Comment by ericchiang** [comment]
some examples here https://github.com/coreos/dex/blob/v1/Documentation/connectors-configuration.md

**Comment by rithujohn191** [comment]
closed by #690

**Comment by ericchiang** [comment]
@rithujohn191 probably still need GitHub and OpenID Connect documentation :)

**Comment by rithujohn191** [comment]
Opps. My bad.

**Comment by ericchiang** [comment]
largely done, closing
