### ISSUE TITLE
examples/k8s: no way to query healthz endpoint if dex is running on a custom CA

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#682]
Kubernetes doesn't support HTTPS queries and our container doesn't have any SSL software installed so wget just breaks. We either need to split out the debug endpoint or install openssl into the container.

**Comment by ericchiang** [comment]
This is largely done because of #685 but I'm going to wait until we've updated the kubernetes examples.

**Comment by rithujohn191** [comment]
#753 is the correct way of addressing this. Closing this out for now.
