### ISSUE TITLE
Multi-IDPC: mark individual IDPC as "disabled"

### ISSUE THREAD

**Issue by bobbyrullo** [coreos/dex#7]
<a href="https://github.com/bcwaldon"><img src="https://avatars.githubusercontent.com/u/548759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcwaldon](https://github.com/bcwaldon)**
_Monday Dec 01, 2014 at 22:46 GMT_
_Originally opened as https://github.com/coreos-inc/auth/issues/114_

----

**Comment by ericchiang** [comment]
For now we're only going to support removing connectors from the configuration without a specific "disable" user experience.
