### ISSUE TITLE
How to make a first request to REST API (v0.6.1)

### ISSUE THREAD

**Issue by vymarkov** [coreos/dex#705]
I am little confused about using the dex worker REST API -- what need to do in order to make a first request to REST API. Currently, repo contains a worker schema for dex worker API but does not includes the description about how to make an authorized request, how to retrieve the needed credentials, or similar. 

For example, i want to retrieve a list of users:

`$ http -v GET http://localhost:5556/api/v1/users `

but got the Unauthorized http status. 

What kind of credentials i need to use in this case?

**Comment by ericchiang** [comment]
That API is kinda hard. Both OAuth2 clients and users have the concept of being an "admin". The OAuth2 access token returned by a login flow allows you to hit the API with certain restrictions based on the combination of "admin" users and clients.

I'd recommend switching your worker to use the `--api-use-client-credentials` then use an "admin" client client credentials to access the API. I believe that uses two-legged OAuth to authenticate[0]. Give me a few minutes and I can verify.

[0] https://godoc.org/golang.org/x/oauth2/clientcredentials

**Comment by ericchiang** [comment]
Yep that works

Make one of the static clients an `admin` for testing.

```
$ git diff .
diff --git a/static/fixtures/clients.json.sample b/static/fixtures/clients.json.sample
index 50d9d64..22f4c13 100644
--- a/static/fixtures/clients.json.sample
+++ b/static/fixtures/clients.json.sample
@@ -8,6 +8,7 @@
   {
     "id": "example-app",
     "secret": "ZXhhbXBsZS1hcHAtc2VjcmV0",
+    "admin": true,
     "redirectURLs": ["http://127.0.0.1:5555/callback"]
   },
   {
$ ./bin/dex-worker --no-db --api-use-client-credentials
WARN: Running in-process without external database or key rotation
INFO: Loaded IdP connector: id=local type=local
INFO: Loaded IdP connector: id=google type=oidc
INFO: Loaded IdP connector: id=github type=github
INFO: Loaded IdP connector: id=bitbucket type=bitbucket
WARN: bindTemplate not used when searchBeforeAuth specified.
INFO: Loaded IdP connector: id=ldap type=ldap
INFO: Binding to 127.0.0.1:5556...
```

Then use the following program to request client credentials to talk to the API.

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http/httputil"

	"golang.org/x/oauth2/clientcredentials"

	oidc "github.com/coreos/go-oidc"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	p, err := oidc.NewProvider(ctx, "http://127.0.0.1:5556/dex")
	if err != nil {
		log.Fatal(err)
	}
	c := clientcredentials.Config{
		ClientID:     "example-app",
		ClientSecret: "ZXhhbXBsZS1hcHAtc2VjcmV0",
		TokenURL:     p.Endpoint().TokenURL,
		Scopes:       []string{"openid"},
	}

	client := c.Client(ctx)

	resp, err := client.Get("http://127.0.0.1:5556/dex/api/v1/users")
	if err != nil {
		log.Fatal(err)
	}
	dump, err := httputil.DumpResponse(resp, true)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s\n", dump)
}
```

This results in:

```
$ go run client.go 
HTTP/1.1 200 OK
Content-Length: 122
Content-Type: application/json
Date: Tue, 22 Nov 2016 18:23:38 GMT

{"users":[{"createdAt":"0001-01-01T00:00:00Z","displayName":"Elroy Jonez","email":"elroy77@example.com","id":"elroy-id"}]}
```
