### ISSUE TITLE
connector/ldap: log as much meaningful information as possible when connecting

### ISSUE THREAD

**Issue by sym3tri** [coreos/dex#719]
To help users debug bad LDAP configurations Dex should log as much info as possible.

**Comment by ericchiang** [comment]
Yes definitely, but to a certain degree, I don't see us being able to provide more information without providing the option for leveled logging (https://github.com/coreos/dex/issues/677). Log as much meaningful information as possible is pretty much the definition of a "debug" flag.

**Comment by sym3tri** [comment]
definitely makes sense to block this on #677
