### ISSUE TITLE
storage/sql: postgres doesn't perist timezone

### ISSUE THREAD

**Issue by jwmaag** [coreos/dex#745]
Using the latest build and fresh postgres database as the storage backend, I was unable to login. 

```
Authorization request period has expired.
```

Digging a bit deeper I noticed that the table was using the __timestamp__ column type (w/o timezone). So it seemed to me that dex was losing some precision between the insert and the select. 

Also telling was the frequent key rotations
```
2016/12/13 14:43:36 keys expired, rotating
2016/12/13 14:43:36 keys rotated, next rotation: 2016-12-13 20:43:36.554887954 -0600 CST
2016/12/13 14:43:36 listening (http) on 0.0.0.0:5556
2016/12/13 14:44:06 keys expired, rotating
2016/12/13 14:44:06 keys rotated, next rotation: 2016-12-13 20:44:06.965425402 -0600 CST
2016/12/13 14:44:36 keys expired, rotating
2016/12/13 14:44:37 keys rotated, next rotation: 2016-12-13 20:44:37.116072981 -0600 CST
2016/12/13 14:45:07 keys expired, rotating
2016/12/13 14:45:07 keys rotated, next rotation: 2016-12-13 20:45:07.321215505 -0600 CST
2016/12/13 14:45:37 keys expired, rotating
2016/12/13 14:45:37 keys rotated, next rotation: 2016-12-13 20:45:37.567846803 -0600 CST
2016/12/13 14:46:07 keys expired, rotating
2016/12/13 14:46:07 keys rotated, next rotation: 2016-12-13 20:46:07.875356915 -0600 CST
2016/12/13 14:46:37 keys expired, rotating
2016/12/13 14:46:38 keys rotated, next rotation: 2016-12-13 20:46:38.063993965 -0600 CST
2016/12/13 14:47:08 keys expired, rotating
2016/12/13 14:47:08 keys rotated, next rotation: 2016-12-13 20:47:08.349067898 -0600 CST
2016/12/13 14:47:38 keys expired, rotating
2016/12/13 14:47:38 keys rotated, next rotation: 2016-12-13 20:47:38.889484596 -0600 CST
2016/12/13 14:48:08 keys expired, rotating
2016/12/13 14:48:09 keys rotated, next rotation: 2016-12-13 20:48:09.681262225 -0600 CST
```

Not sure if i missed something, but my resolution was to wrap the default server.now function with one that returns UTC.

**Comment by ericchiang** [comment]
Thanks will look into this. If we're using the wrong datatype that might be hard to resolve in a non-backward compatible way (though we'll try). But if you're right than our postgres driver has never worked. Funny.

**Comment by ericchiang** [comment]
Moving some comments from https://github.com/coreos/dex/pull/746

> It'd be quicker to switch everything over to UTC, but I'd rather the server not be dependent on us never using timezones. E.g. it's weird for logs to spit out timestamps in two different timezones (one for the logging metadata, another for the printed time). I think it should be a quick enough fix.
>
> In terms of migrations I don't even know if this one is safe. If the server's been storing timestamps in one format then suddenly switches a few hours ahead or behind that's going to have some really bad consequences. I think the fix for this might have to be breaking.

@rithujohn191 has volunteered to fix this. Going to bump priority to p0 since it completely breaks postgres.

**Comment by ericchiang** [comment]
Some updates from @rithujohn191's investigations. SQLite3 doesn't do timezones, and the client just ignores the timezone rather than converting it to UTC. Even if we switch Postgres to using `datetimetz`, our client may still have to standardize to deal with SQLite3.

@jwmaag #746 is looking more likely to become a part of the solution we go with.

**Comment by ericchiang** [comment]
So we can either add a "supportsTimezones" flag to SQL flavors and force times going into SQLite3 to always convert to UTC, oR switch dex to use UTC everywhere. Going to ask around CoreOS and see if there's a preference.

**Comment by jwmaag** [comment]
Well I guess I'll reopen the PR 😄 , but that's interesting I didn't know that about sqlite3.

fwiw, adding "supportsTimezones" kind of feels like it would be a one-off... Personally, I like the idea of all the backends being the same format-wise... though, it would be if it wasn't for sqlite3 being a one-off.

I see the dilemma.

**Comment by ericchiang** [comment]
> fwiw, adding "supportsTimezones" kind of feels like it would be a one-off... Personally, I like the idea of all the backends being the same format-wise... though, it would be if it wasn't for sqlite3 being a one-off.

Basically all SQL flavors are one-offs. Not a huge deal.

I think we should both make SQL more resilient to timezones and switch everything in dex to use UTC (including the logger). The former solves our correctness issues, the latter keeps us consistent. @rithujohn191 what do you think?

**Comment by rithujohn191** [comment]
Sounds good. Once sqlite3 actually supports times zones we can probably make this cleaner.
