### ISSUE TITLE
Response type for implicit flow

### ISSUE THREAD

**Issue by xeonx** [coreos/dex#761]
Hello,
I'm trying to use a js openid connect client (https://github.com/IdentityModel/oidc-client-js) and I'm facing issue with the response types for the implicit flow.
According to the oidc spec (http://openid.net/specs/openid-connect-core-1_0.html#Authentication) the response types that should trigger the implicit flow are:
- id_token
- id_token token

It seems to me that dex only supports the "token" response type in order to trigger this implicit flow.
I may be misreading both oidc specs and dex code, thus please correct me if I'm wrong.
Otherwise I will try to fix this behavior in order to allow the 2 above mentioned response_type values

Thanks,
Simon

**Comment by davecoates** [comment]
I have come across the same thing. Specifying 'token' as the response_type actually returns an id_token but according to https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest it doesn't sound like it should: 

```
NOTE: While OAuth 2.0 also defines the token Response Type value for the Implicit Flow, OpenID Connect does not use this Response Type, since no ID Token would be returned.
```

Is dex treating token like id_token and should just be accepting id_token or have I misunderstood? This would make using existing frontend libraries like oidc-client-js with dex easier

**Comment by ericchiang** [comment]
> According to the oidc spec (http://openid.net/specs/openid-connect-core-1_0.html#Authentication) the response types that should trigger the implicit flow are:

looks like you're write. I can send a patch at some point or someone else can take this.

**Comment by ericchiang** [comment]
If you get `oidc-client-js` working it'd be great to add it to the README btw https://github.com/coreos/dex#documentation
