### ISSUE TITLE
google authenticator support?

### ISSUE THREAD

**Issue by sokoow** [coreos/dex#763]
Hey All, first of all well done for this brilliant piece of software - took less than a day to get it working. Do you ever plan for google authenticator support ?

**Comment by rithujohn191** [comment]
Google authenticator support is definitely a great feature to have, but it's not on the immediate roadmap. pull requests are accepted if you'd like to contribute. 

For now a workaround is to use the dex OIDC connector (https://github.com/coreos/dex/tree/master/connector/oidc) and use Google as the provider.

**Comment by ericchiang** [comment]
Do you mean two factor auth?

https://en.wikipedia.org/wiki/Google_Authenticator

**Comment by sokoow** [comment]
Yes, exactly :)

**Comment by ericchiang** [comment]
Might be something that can be implemented out of scope of dex. E.g. user logs into app through dex, then when they try to do something sensitive the app itself triggers a second factor.

When to trigger a second factor is hard to express in a general way.

**Comment by sokoow** [comment]
I use this a bit, also great piece of software: https://github.com/gravitational/teleport , they implemented google auth very nicely there: 

https://github.com/gravitational/teleport/blob/6b85b01b465ceee168f341eb6ffb4949bdf112e6/vendor/github.com/gokyle/hotp/hotp.go
https://github.com/gravitational/teleport/blob/a8533fde6694f40eb8ff237bdff6f5a3f34fae06/web/src/app/components/login.jsx

**Comment by ericchiang** [comment]
> I use this a bit, also great piece of software:

Sure, that's not what I'm asking. I'm suggesting that this might be better implemented by apps that use dex, not dex itself.

**Comment by ericchiang** [comment]
Going to close as a dup of #352
