### ISSUE TITLE
Grant types [Question]

### ISSUE THREAD

**Issue by jainh** [coreos/dex#764]
Hi,

What are the different grant types supported by dex ? does it support resource owner password grant type and client credential ?

**Comment by jainh** [comment]
@rithujohn191 Thank you for the reply, I thought dex is also supporting implicit mode ? Any idea on bringing other grant_types in near future ?

**Comment by rithujohn191** [comment]
Yes we do support implicit mode as well. Adding the client credential grant type is not on the immediate roadmap for Dex v2.

**Comment by ericchiang** [comment]
The only other grant types I can think of are `client_credentials` and `password`. I don't think we want to support `password` (has been discussed in the past) and `client_credentials` doesn't make much sense because our `access_token` does actually do anything.

Is there one you're looking for?

**Comment by glerchundi** [comment]
@rithujohn191 @ericchiang why not password grant type? can you point us to the issues where the discussion about password grant type took place?

Thanks!

**Comment by ericchiang** [comment]
hi @glerchundi this thread has some background https://groups.google.com/forum/#!searchin/dex-dev/password%7Csort:relevance/dex-dev/KoY0JegNcr4/1sbzKkMABQAJ

Basically allowing password grants wouldn't work with a lot of backing implementations (like Google), and it also acts as a way to bypass a lot of our security efforts.

In addition I'd rather not have people using dex as a password database. Those are easy enough to build yourself, or you could even just use an LDAP server.

**Comment by ericchiang** [comment]
Mind if I close this? We don't use the issue tracker for questions.

**Comment by jainh** [comment]
Yes please. Thank you.

**Comment by glerchundi** [comment]
@ericchiang just one question, so in case someone wants to migrate their legacy username/password databases to dex, which are the options? get rid of ad-hoc users from the database, migrate them to a LDAP server and then connect dex to it?

Thanks.

**Comment by ericchiang** [comment]
@glerchundi That seems to be tangential to having a password grant type. Dex can store username/password combinations locally (see the API[0]), but you'll still want to manage your users somewhere.

[0] https://github.com/coreos/dex/blob/master/api/api.proto

**Comment by glerchundi** [comment]
> @glerchundi That seems to be tangential to having a password grant type.

Yes it is.

> Dex can store username/password combinations locally (see the API[0]), but you'll still want to manage your users somewhere.

Ok, that gets me to the next and final question (probably it's out of this issues scope by anyway), is it possible to validate the `access_token` (remotely?) and then obtain the user information by extracting the token locally (that would requires to be protobuf formatted message or a JWT-like one and not a random string as it is now) or retrieving that information by contacting dex remotely?

IMO in order to be as decoupled as possible in this microservices dominated world, the `access_token` should be conformed following a predefined format with user related information like uid+roles/groups, more or less like you already proposed in #376.

Thanks for your patience

**Comment by ericchiang** [comment]
@glerchundi it sounds like `id_token` is exactly what you're looking for. This is the primary extension that dex provides as part of the token response. A signed token with email, groups, username, etc. in it.

Dex's `access_token` should always be treated as opaque. You shouldn't every try do decode them. #376 is only referring to implementing the UserInfo endpoint[1].

[0] https://openid.net/specs/openid-connect-core-1_0.html#IDToken
[1] https://openid.net/specs/openid-connect-core-1_0.html#UserInfo

**Comment by glerchundi** [comment]
@ericchiang sorry for the confusion, i thought `id_token` was for the client side and not for the  resource server. Perhaps I should reconsider what client means in this context, I got confused with this thread: https://github.com/IdentityServer/IdentityServer3/issues/2015

Correct me if i'm wrong, should I send something like `Authentication: Bearer access_token` and then another `X-ID-Token: id_token` (just consider them pseudo header :))  in case I wanted to be both authenticated & identified in the backend server then?

Thanks for your time this is being really helpful.

**Comment by testinfected** [comment]
> The only other grant types I can think of are `client_credentials` and `password`. I don't think we want to support `password` (has been discussed in the past) and `client_credentials` doesn't make much sense because our `access_token` does actually do anything.
> 
> Is there one you're looking for?

Hi @ericchiang could you explain why `client_credentials` does not make sense. I happened to [need it for integrating with Flyte](https://github.com/dexidp/dex/issues/4429). Looking at the code it seems all the pieces are there to implement it. 

Thanks in advance
