### ISSUE TITLE
Bug: Using Kubernetes storage, always gets "Bad Request - Invalid client_id"

### ISSUE THREAD

**Issue by alon-argus** [coreos/dex#798]
`kubectl get oauth2clients -o yaml -n auth`:
```
apiVersion: v1
items:
- apiVersion: oidc.coreos.com/v1
  clientID: stag
  clientSecret: <censored>
  kind: OAuth2Client
  metadata:
    creationTimestamp: 2017-02-06T17:30:30Z
    name: stag
    namespace: auth
    resourceVersion: "56746098"
    selfLink: /apis/oidc.coreos.com/v1/namespaces/auth/oauth2clients/stag
    uid: <censored>
  redirectURIs:
  - <censored>/redirect_uri
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```

Client redirects to here:
```
https://<dex_address>/auth?scope=openid%20email%20profile&client_id=stag&state=<censored>&nonce=<censored>&redirect_uri=<censored>%2Fredirect_uri&response_type=code
```

No matter what client ID I tried using, response is always:
```
Bad Request

Invalid client_id ("stag").
```
(or any other client ID I've tried, of course.

BTW, with when I set it through staticClients, it does work.

Dex version: 2.1.0
Kubernetes version: 1.5.2

Many thanks guys.

**Comment by ericchiang** [comment]
Clients should be set through the dex API[0] not by editing the Kubernetes third party resources directly. We compute a hash for the "name", it's not 1-to-1.

Sorry, we should really add warning to the Kubernetes docs that users shouldn't edit the third party resources manually.

[0] https://github.com/coreos/dex/blob/master/Documentation/api.md

**Comment by alon-argus** [comment]
Oh, I got it. Thanks a lot!
I was following the directions here, BTW -
https://github.com/coreos/dex/blob/master/Documentation/storage.md

**Comment by ericchiang** [comment]
@alon-argus yep I opened #799 to update that doc (feel free to comment). Going to keep this open until we get that merged.
