### ISSUE TITLE
Documentation: deployment guide

### ISSUE THREAD

**Issue by philips** [coreos/dex#81]
- [ ] systemd unit files for worker and overlord
- [ ] pods, services, etc for k8s deployment

**Comment by mreynolds** [comment]
https://github.com/coreos/dex/blob/master/Documentation/getting-started.md still refers to the missing "deployment guide", FYI.  Might be worth either adding a stub or not having the reference in the docs?  Let me know and I can drop a PR.

**Comment by ericchiang** [comment]
k8s deployment stuff is in[0]. I don't think we're going to do systemd units.

[0] https://github.com/coreos/dex/tree/master/examples/k8s
