### ISSUE TITLE
 error resources: ID already exists.

### ISSUE THREAD

**Issue by yawboateng** [coreos/dex#822]
Im running dex v2.2.2 on kubernetes, after a pod restarts, i see multiple lines of failed creating third party resources: ID already exists.

should this be an error? should it log it once and maybe as info? or is it standard that I go in after each restart and update the client-id?

**Comment by ericchiang** [comment]
@yawboateng I think https://github.com/coreos/dex/pull/815 is causing this. I don't think it's actually going to cause bad behavior, but yeah we should correct the if condition.

**Comment by ericchiang** [comment]
Sending a fix now. We'll backport and release a 2.2.3 today.
