### ISSUE TITLE
Refresh tokens getting overridden

### ISSUE THREAD

**Issue by Calpicow** [coreos/dex#847]
Using dex v2.2.4, Postgres as backing store.

Steps to reproduce, with `refresh_token` dump:
1. Log in using example-app, redeem refresh token for good measure

| id | client_id | token |
|-|-|-|
| u3npmgopunb7qh3e6cgd4ciqii | example-app | md2j4rvut5yaz42esbchs3ovrq |

2. Log in using another app (in this case: k8s with oob--not sure if this matters), so far so good

| id | client_id | token |
|-|-|-|
| u3npmgopunb7qh3e6cgd4ciqii | example-app | md2j4rvut5yaz42esbchs3ovrq |
| 63uk46yzu3qasdhlizwv5463bu	| k8s | klhtpxlm4vroe6c47jxkrelszy |

3. Log in using example-app again, redeem refresh token

| id | client_id | token |
|-|-|-|
| 63uk46yzu3qasdhlizwv5463bu	| example-app | rpxfmluuwe34ocj7pob5hzr2xu |
| 2xvuxgabi5wk33ncm6t2g2azvq	| example-app | rpxfmluuwe34ocj7pob5hzr2xu |

My k8s refresh token has disappeared. Going by the ids, it appears that it is getting overridden by example-app.

**Comment by ericchiang** [comment]
Uh oh, that's really bad. Investigating.

**Comment by Calpicow** [comment]
Looks like it's missing a WHERE clause: https://github.com/coreos/dex/blob/master/storage/sql/crud.go#L302

**Comment by ericchiang** [comment]
@Calpicow thanks for catching that. Will submit a fix ASAP.

**Comment by ericchiang** [comment]
@Calpicow we've released with v2.2.5 with a patch https://github.com/coreos/dex/releases/tag/v2.2.5
