### ISSUE TITLE
Can't redeem refresh tokens with self-signed cert

### ISSUE THREAD

**Issue by andrewrynhard** [coreos/dex#874]
I have a Dex/LDAP setup, and using the example-app as a client. I am using self signed certs. So far I am able to  login and get the token and refresh token. However, when I click "Redeem refresh token" I get the following error:
```
failed to get token: Post https://DEX/token: x509: certificate signed by unknown authority
```
but I am specifiying the issuer root CA:
```
./bin/example-app --issuer https://DEX/ --issuer-root-ca ~/ca.pem --client-id=kubernetes --redirect-uri http://SOMEWHERE:5555/callback
```

/cc @ericchiang

**Comment by ericchiang** [comment]
Ah this does look like a bug in the example app.
