### ISSUE TITLE
Expand envvars on static client config section

### ISSUE THREAD

**Issue by drywheat** [coreos/dex#889]
As of version **v2.3.0**, only the [storage](https://github.com/coreos/dex/blob/v2.3.0/cmd/dex/config.go#L152-L154) and [connection](https://github.com/coreos/dex/blob/v2.3.0/cmd/dex/config.go#L209-L211) sections of the dex config can leverage envvar expansion. This make sense since users will possibly need to provide dynamic credentials at runtime.

Adding a static client config in dex requires providing a sensitive OAuth secret, and since hardcoding values into a file stored in a VCS is insecure, does it not make sense to evaluate envvars here as well?

**Comment by rithujohn191** [comment]
This does seem to be a useful feature to add. However, currently you can use the gRPC API calls to create a client (https://github.com/coreos/dex/blob/master/Documentation/api.md).

**Comment by drywheat** [comment]
I believe I see what your saying:

1. Right now, I can make an RPC call to dex in order to create a client config w/o having to hardcode a password inside `dex.config`.
2. Variable expansion for the `staticClients` section would also be useful.

I'll look at the code and see if there's an easy PR I can create.

**Comment by rithujohn191** [comment]
Would be more than happy to review the PR once its ready

**Comment by jungziege** [comment]
@rithujohn191 do you have suggestions for best practices around creating clients with the gRPC API? We have it in config now, and are happy to move it to gRPC but can't really figure out how to do it exactly once without doing it manually.

**Comment by AlexanderMann** [comment]
👍 on this functionality or a clear denotation that this issue is to be closed and we should only use gRPC

**Comment by gugahoi** [comment]
What is happening with this issue? I would rather not have hardcoded secrets in my VCS and this seems like a big oversight at the moment. Alternatively could we have detailed documentation on how to achieve the same with gRPC?

**Comment by pjmichael** [comment]
I agree @gugahoi. It would be very useful feature to avoid static secrets in source control and read them in from env vars

**Comment by SongGithub** [comment]
I agree with @gugahoi.  To use Dex in production, we must not hard-code any sensitive information in text file. Please approve the PR! Much appreciated.

**Comment by rithujohn191** [comment]
@gugahoi if documentation is what you are looking for please check out these [docs](https://github.com/coreos/dex/tree/master/examples/grpc-client)

**Comment by gugahoi** [comment]
@rithujohn191 That's a good start but I cannot see why someone would go to the trouble of all of that instead of having the variables being interpolated. The instructions seem clear on `how` to do it but not on `why` would I want to go through that process. Forgive my ignorance as I am not familiar with gRPC but I still dont understand the advantage of this process.

**Comment by ericchiang** [comment]
I think that a more explicit approach to this would be _way_ better than arbitrary byte slice substitution. e.g.

```
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secretFromEnv: CLIENT_SECRET
  secretFromFile: /etc/foo/client-secret
```

I don't want to continue to add more environment expansions. It makes the config format impossible to parse, for instance, because it's environment dependent.

**Comment by ericchiang** [comment]
Closing in favor of https://github.com/coreos/dex/issues/1099
