### ISSUE TITLE
deploy dex using examples/k8s to a namespace containers stay in "CreatingContainer" status

### ISSUE THREAD

**Issue by jmspring** [coreos/dex#914]
There are no relevant logs. 

Repro:

- create namespace
- deploy kubectl create -n <namespace> dex.yaml

Nothing.

Default namespace is fine.

**Comment by ericchiang** [comment]
Sorry, do you have some logs or can you run kubectl describe on the resources that are stalled?

**Comment by ericchiang** [comment]
Closing since there's not enough info here to act on. Please feel free to follow up if you can get us some logs or kubectl output.
