### ISSUE TITLE
Does the LDAP connector's bindPW have any character restrictions?

### ISSUE THREAD

**Issue by tedstirm** [coreos/dex#930]
Are there character restrictions for the LDAP connector's service account(bindPW) password? 

Reason I ask is because when working through the example I ran into an issue where the LDAP connector was removing a $ from my service account's(bindPW) password when transmitting the password to the LDAP server. This of course resulted in me getting invalid credentials from the LDAP server. I was able to capture this via wireshark.

**Comment by jwmaag** [comment]
i'm sure others may no better but iirc dex runs the configuration through some os.ExpandEnv which looks at the '$' and tries to apply an environment variable to replace it with, in the case that it cannot find one it will put an empty string.

A possible solution would be to put your ldap pw in the environment for example making a rundex.sh and putting it in there.

```sh
export LDAP_PW=foobar$
./dex serve config.yaml
```

in your config you would have bindPW as $LDAP_PW

**Comment by tedstirm** [comment]
@jwmaag Ahhh okay, that make sense. I just ended up changing my service account password and everything worked fine from that point on. However, I just wanted to make others aware of the possible issue.

**Comment by rithujohn191** [comment]
Thanks for pointing out the issue @tedstirm . As @jwmaag pointed out we do make use of os.ExpandEnv which will see a '$' and try to apply an environment variable.

I will create an issue to add this to our documentation.
