### ISSUE TITLE
Docker tag latest is outdated

### ISSUE THREAD

**Issue by bkleef** [coreos/dex#932]
Please check https://quay.io/repository/coreos/dex?tag=latest&tab=tags. It's 6 months old.
I expect it to be pinned on v2.4.1.

**Comment by rithujohn191** [comment]
Hi @bkleef,

Thank you for pointing out this issue. We have decided to no longer support the latest tag in the quay.io dex repository since this can be confusing for users who do not want to use the latest version of dex.

The latest tag has now been deleted from the repo.

**cc** @sym3tri
