### ISSUE TITLE
Add additional claims to id token

### ISSUE THREAD

**Issue by waterdudu** [coreos/dex#938]
Is there a way to add [additional claims](http://openid.net/specs/openid-connect-core-1_0.html#AdditionalClaims) to id token?

**Comment by YanshuoH** [comment]
+1

**Comment by rithujohn191** [comment]
We do not support this feature yet and is currently not on the immediate road-map for dex. You are more than welcome to open up a PR to add this functionality.

**Comment by ericchiang** [comment]
Sure, but what should those claim values hold? Should they be static and the same across all users? Should those values be grabbed from the upstream IdP?

Please open a specific issue like https://github.com/coreos/dex/issues/552 for this. We already include custom claims, such as the "groups" claim. We need to understand _which_ claims with _what_ value you want to add.
