### ISSUE TITLE
Auth request error when using postgres and ldap

### ISSUE THREAD

**Issue by zhuguihua** [coreos/dex#944]
The dex config:

```issuer: http://10.132.47.121:5556
storage:
  type: postgres
  config:
    database: dex_db
    user: admin
    password: "123456"
    host: 10.142.21.122:5432
    ssl:
      mode: disable
web:
  http: 0.0.0.0:5556
connectors:
- type: ldap
  id: ldap
  name: LDAP
  config:
    host: 10.142.21.152:32036
    insecureNoSSL: true
    bindDN: cn=admin,dc=cmss,dc=com
    bindPW: "123456"
    userSearch:
      baseDN: ou=users,dc=cmss,dc=com
      filter: "(objectClass=inetOrgPerson)"
      username: cn
      idAttr: cn
      emailAttr: mail
      nameAttr: cn
    groupSearch:
      baseDN: ou=groups,dc=cmss,dc=com
      filter: "(objectClass=groupOfNames)"
      userAttr: DN
      groupAttr: member
      nameAttr: cn

staticClients:
- id: dex-app
  redirectURIs:
  - 'http://10.132.47.121:5556/callback'
  name: 'Dex App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

auth2:
  skipApprovalScreen: true

logger:
  level: "debug"
  format: "text"

enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAue`S7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
```
After booting dex and dex-app, I logged in, but I received some errors:
time="2017-05-11T09:02:54Z" level=error msg="Invalid 'state' parameter provided: not found"

Requested resource does not exist.

Anyone has good ideas?

**Comment by rithujohn191** [comment]
The error is due to this line: https://github.com/coreos/dex/blob/9514bf9afe23640964a008bc7f4d7e8ccbbc3413/server/handlers.go#L340

Basically it tries to query the back-end storage to retrieve the AuthRequest for a particular authID. The error means that an AuthRequest for that particular authID does not exist in the storage.

I will try to replicate the issue on my end. But in the mean time could you please verify that its not an internal DB issue? and ensure that https://github.com/coreos/dex/blob/9514bf9afe23640964a008bc7f4d7e8ccbbc3413/server/handlers.go#L164 succeeds.

**Comment by zhuguihua** [comment]
Thanks for you response.
1.CreateAuthRequest() did succeed.
2. I read the code, and foud that the authID passed to GetAuthRequest was state 'I wish to wash my irish wristwatch'.   But in this line https://github.com/coreos/dex/blob/master/storage/sql/crud.go#L178 , you can find authID must be req id.

**Comment by zhuguihua** [comment]
@rithujohn191 Also you can find, before excuting GetAuthRequest() in function handleConnectorCallback(), DeleteAuthRequest() will be called in function sendCodeResponse(). 
And in this line https://github.com/coreos/dex/blob/master/server/handlers.go#L358, the type of ldapConnector is not CallbackConnector or SAMLConnector, the default case will be excuted.

**Comment by rithujohn191** [comment]
Could you plz confirm which version of Dex you are using?

**Comment by zhuguihua** [comment]
I build the dex from codes of mater branch.

**Comment by rithujohn191** [comment]
@zhuguihua the state and the authID are two separate fields. If you look at the source code for our example app https://github.com/coreos/dex/blob/master/cmd/example-app/main.go#L26 you will see that "I wish to wash my irish wristwatch" is an example state that we use to verify the condition https://github.com/coreos/dex/blob/master/cmd/example-app/main.go#L275. More info on the state parameter: https://tools.ietf.org/html/rfc6749#section-10.12. 

Please try running again with our example-app by changing the `staticClients` value to the following:
```
staticClients:
- id: dex-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Dex App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

```

**Comment by rithujohn191** [comment]
Closing out this issue for now. Please feel free to re-open if you have more concerns.

**Comment by tuwid** [comment]
@rithujohn191 having the same issue with Azure AD, any ideas ?
