### ISSUE TITLE
Unable to get started. Please help

### ISSUE THREAD

**Issue by davidiamyou** [coreos/dex#945]
Hi All,

I followed the documentation `Get Started` to run dex. However, I can getting process killed every time.

```
[1]    6753 killed     ./bin/dex --debug serve examples/config-dev.yaml
```

When I tried to run `cmd/dex/main.go` directly from IDE. I am getting these errors.

```
# command-line-arguments
cmd/dex/main.go:18: undefined: commandServe
cmd/dex/main.go:19: undefined: commandVersion
```

Environment is `Go1.7` and `MacOS Sierra 10.12.4`. Any help and advice is appreciated.

**Comment by jwmaag** [comment]
I think I ran into this a while back, probably related to https://github.com/golang/go/issues/11887

try adding -s to the LD_FLAGS environment in the Makefile

```
 LD_FLAGS="-w -s -X $(REPO_PATH)/version.Version=$(VERSION)"
```

**Comment by davidiamyou** [comment]
tried out. it works thx!
