### ISSUE TITLE
Add session management support

### ISSUE THREAD

**Issue by liubog2008** [coreos/dex#963]
[https://openid.net/specs/openid-connect-session-1_0.html](https://openid.net/specs/openid-connect-session-1_0.html)

Does dex plan to support it?

**Comment by rithujohn191** [comment]
Hi @liubog2008 ,

This sure will be a useful addition, but it is currently not on our immediate roadmap.

**Comment by liubog2008** [comment]
Hi @rithujohn191 ,
So how can I log out from dex?

**Comment by rithujohn191** [comment]
@liubog2008 ,

When an end-user is authenticated in Dex, they login via a connector (GitHub, LDAP, etc). Users are never "logged into dex" and thus Dex can get away with not handling the session management. Every time the user hits the logout button, they always have to re-login using the same process. As of now we don't have a mechanism in place to "remember the user" after they login. We have an open issue for it here https://github.com/coreos/dex/issues/32.

**Comment by rithujohn191** [comment]
@liubog2008 if you are satisfied with this answer do you mind if I close out this issue?

**Comment by liubog2008** [comment]
Sorry for late reply @rithujohn191 

> Every time the user hits the logout button, they always have to re-login using the same process.
I can't understand it well enough. 

I have read #32 . Maybe you misunderstood me. In fact, what I hope to know is how to invalidate an IDToken (logout), not SSO.

**Comment by ericchiang** [comment]
@liubog2008 I don't get the motivation for implementing that spec. It seems to be "check to see if the end user for this ID token is still logged in." Dex doesn't implement any session management or track that information, so users are never really "logged into" dex. E.g. there's no way for a user to logout.

If you want this kind of behavior, set the ID token expiry to something extremely short (5min), then use refresh tokens for long term login. Refresh tokens are revocable, so you'd be able to cut off someone's access that way.

As stated, I think that spec is only relevant if we enable some sort of session management in dex. Without it, it doesn't seem to apply.

**Comment by liubog2008** [comment]
OK，thanks for your reply @ericchiang
