### ISSUE TITLE
All tags on quay.io have vulnerabilities

### ISSUE THREAD

**Issue by dolanor** [coreos/dex#966]
Hello,

on the tag page, all tags have vulnerabilities. I guess we need a full rebuild of all the tags to avoid that.
https://quay.io/repository/coreos/dex?tab=tags

**Comment by ericchiang** [comment]
Hi @dolanor 

All the vulnerabilities reported by Quay are zlib bugs, which dex doesn't compile against. None of these actually impact dex.

We should update our base image for good measure, but "All tags on quay.io have vulnerabilities" is going a bit far.

**Comment by ericchiang** [comment]
Fixed by https://github.com/coreos/dex/pull/994
