### ISSUE TITLE
Question about azp

### ISSUE THREAD

**Issue by liubog2008** [coreos/dex#984]
I find it that dex support `azp` in OIDC. However, if I use this feature, I could not validate my IDToken because `aud`  doesn't contains `client_id`.

I have read spec of `azp`. 

> azp
OPTIONAL. Authorized party - the party to which the ID Token was issued. If present, it MUST contain the OAuth 2.0 Client ID of this party. This Claim is only needed when the ID Token has a single audience value and that audience is different than the authorized party. It MAY be included even when the authorized party is the same as the sole audience. The azp value is a case sensitive string containing a StringOrURI value.

> 3. The Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer identified by the iss (issuer) Claim as an audience. The aud (audience) Claim MAY contain an array with more than one element. The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience, or if it contains additional audiences not trusted by the Client.
> 4. If the ID Token contains multiple audiences, the Client SHOULD verify that an azp Claim is present.
> 5. If an azp (authorized party) Claim is present, the Client SHOULD verify that its client_id is the Claim Value.

Does it means that `aud` needs to append `client_id` even if `azp` is present.
For example

```
"aud": ["cli-app", "web-app"],
"azp": "web-app"
```

However, ```This Claim is only needed when the ID Token has a single audience value and that audience is different than the authorized party. It MAY be included even when the authorized party is the same as the sole audience.``` is confused me.

By the way, it seems that `go-oidc` can't verify dex IDToken if enable `azp`? And kubernetes also can't validate these IDTokens which use `go-oidc`

**Comment by liubog2008** [comment]
@ericchiang @rithujohn191

**Comment by ericchiang** [comment]
So I think the question is "should aud always contain the azp"? We don't automatically do that today, e.g. if you login to a web app and ask for a id token issued for a client it's possible to get claims like.

```
"aud": "cli-app",
"azp": "web-app"
```

Automatically including the `azp` seems like reasonable behavior, but the current behavior also seems valid. Take a look at google docs for a similar feature https://developers.google.com/identity/protocols/CrossClientAuth#accessTokens

For what it's worth, when specifying cross client scopes, you can request your own client to have it included in the audience.

**Comment by ericchiang** [comment]
Going to close this out since there's not really a proposed change.
