### ISSUE TITLE
Authentication issue when user is a member of a large number of GitHub Teams

### ISSUE THREAD

**Issue by sir-rob** [coreos/dex#988]
This issue appears to be related to #958 except instead of LDAP groups, we are seeing this for GitHub teams.

I ran into this issue while working with a customer's cluster. They have many GitHub teams mapped to Roles via RoleBindings, and everyone was able to login fine. They mapped a new GitHub team and 2 of the new users are unable to login but 1 of the users in the new GitHub team is able to login. Unsuccessful users are members of 41 teams, and successful user is a member of only 4 teams.

The tectonic console log showed:
`2017/07/10 14:21:20 server: no token found: token cookie not found in request: http: named cookie not present`

**Comment by sir-rob** [comment]
@rithujohn191 fyi

**Comment by ericchiang** [comment]
Can we close as a dup of https://github.com/coreos/dex/issues/958 ?

**Comment by lypht** [comment]
Thanks for filing this, @sir-rob When we have users in more than 4 teams, authentication against Github fails.  We are manually creating users to address this blocker for our CI team, who are members of all products across the org.  Each of the CI team members is in at least 41 teams, significantly lower than the team total in the LDAP-referenced issue.  Feel free to close as a dup from our end, but it's important to note that when pagination occurs, the authentication method is successful, but the user is dumped to the same loop seen when an email isn't made public.

**Comment by ericchiang** [comment]
@lypht thanks. Noted in #958 that we should error out if the number of groups is too large. Currently we expect the client to know that the ID token is too big to shove in anHTTP cookie, but console doesn't do that check. Probably safer to just throw an error on our end.

Closing in favor of #958, the older issue. Please track progress there.
