### ISSUE TITLE
Redirect URI with # character breaks parsing

### ISSUE THREAD

**Issue by tylercloke** [coreos/dex#991]
```
./bin/example-app --redirect-uri "http://127.0.0.1:5555/callback/#/more_url"
```

Also add `http://127.0.0.1:5555/callback/#/more_url` to the config. It will properly validate it, but on redirect, it will redirect to:

```
http://127.0.0.1:5555/callback?code=xznhxzcjqbwg3jjavth5tk7s7&state=I+wish+to+wash+my+irish+wristwatch#/more_url
```

Note that `#/more_url` has been placed at the end of the redirect url for no reason. This breaks trying to redirect to angular2 endpoints.

**Comment by ericchiang** [comment]
This actually looks like the correct behavior, with the query not appended to the URL fragment. If the query was just appended to the fragment, it would be part of the fragment, not the query.

Can you explain why this breaks Angular2 endpoints? Can you even provide a redirect URL with a fragment to other OAuth2 providers like Google?

**Comment by tylercloke** [comment]
Oops sorry. Posted wrong. Updated my description. Url should be `http://127.0.0.1:5555/callback/#/more_url`. Was missing some `/`.

**Comment by ericchiang** [comment]
@tylercloke I sitll don't understand the context. Why are you using a fragment in the URL? What is the expected redirect with a state query parameter vs. what you're actually getting from dex? What do other providers do?

**Comment by tylercloke** [comment]
I'd expect the redirect URL to look like:

```
http://127.0.0.1:5555/callback/#/more_url?code=xznhxzcjqbwg3jjavth5tk7s7&state=I+wish+to+wash+my+irish+wristwatch
```

Instead of 

```
http://127.0.0.1:5555/callback?code=xznhxzcjqbwg3jjavth5tk7s7&state=I+wish+to+wash+my+irish+wristwatch#/more_url
```

**Comment by tylercloke** [comment]
For more context, angular added the `#` to its routes.

**Comment by ericchiang** [comment]
Per the OAuth2 spec:

>   If the resource owner grants the access request, the authorization
   server issues an authorization code and delivers it to the client by
   adding the following parameters to the __query component of the
   redirection URI__ using the "application/x-www-form-urlencoded" format,
   per Appendix B:

(emphasis my own)

https://tools.ietf.org/html/rfc6749#section-4.1.2

While a fragment is defined as:

> A fragment identifier component is indicated by the presence of a
   number sign ("#") character and terminated by the end of the URI.

https://tools.ietf.org/html/rfc3986#section-3.5

So appending the query to the end of the URL would be placing it in the fragment, not the query component. Based on my interpretation of the RFCs, the following is an invalid OAuth2 response:

```
http://127.0.0.1:5555/callback/#/more_url?code=xznhxzcjqbwg3jjavth5tk7s7&state=I+wish+to+wash+my+irish+wristwatch
```

**Comment by tylercloke** [comment]
Ah ok, I'll work around it. Thanks for your detailed response :)
