### ISSUE TITLE
http: TLS handshake error from x.x.x.x: EOF

### ISSUE THREAD

**Issue by alexandrst88** [coreos/dex#992]
Hi, this is my first issue in this project, if I missed to add information, please let me know.
I'm getting this error in dex logs:
```2017/07/14 12:01:55 http: TLS handshake error from 100.83.203.192:33584: EOF
2017/07/14 12:02:01 http: TLS handshake error from 100.71.36.0:50261: EOF
2017/07/14 12:02:01 http: TLS handshake error from 100.110.213.130:25122: EOF
2017/07/14 12:02:01 http: TLS handshake error from 100.74.197.192:6610: EOF
```
**Dex Version**: quay.io/coreos/dex:v2.4.1
**Kubernetes Version**: 1.6.2
Also, I see the same error in kube-api logs.
```
I0714 11:59:02.545732       5 logs.go:41] http: TLS handshake error from 172.22.95.22:30431: EOF
I0714 11:59:02.839669       5 logs.go:41] http: TLS handshake error from 172.23.95.214:1508: EOF
```

Also, I'm using LDAP connector.

**Comment by ericchiang** [comment]
Something is probably sending an HTTP request to a port that dex is expecting an HTTPS request at. Maybe a health check?

There's not enough information here for us to know what's going on. What were you expecting to happen? What actually happened?

**Comment by ericchiang** [comment]
Closing for lack of info. Please open another issue if you think you've hit a dex bug.

**Comment by alexandrst88** [comment]
Sorry, indeed it was going from elb health check.

**Comment by yawboateng** [comment]
@alexandrst88 how did you fix this? im also seeing the same in my logs. not sure what is sending this http req

**Comment by alexandrst88** [comment]
In my case it was LB, that was trying to reach https.

**Comment by yawboateng** [comment]
gotcha. i manually updated in aws from TCP to SSL. k8s seems to only use TCP for the elb

FYI: https://github.com/kubernetes/kubernetes/issues/45746
