### ISSUE TITLE
Migrate from TPRs to CRDs

### ISSUE THREAD

**Issue by alonl** [coreos/dex#993]
Hi guys, and thanks for the great work.

Are there any plans for supporting Kubernetes version 1.7 and above?

In Kubernetes 1.7 ThirdPartyResource API (which, AFAIK, Dex uses) has become deprecated, and in Kubernetes version 1.8 it'll be removed ([see Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#action-required)), so Dex must migrate to CustomResourceDefinition. [Documentation here](https://kubernetes.io/docs/tasks/access-kubernetes-api/migrate-third-party-resource/).

I couldn't find any issue on this topic...

**Comment by ericchiang** [comment]
Hey @alonl we've been planning this migration internally, but haven't migrated it to the open source repo yet. So yes there are plans. Thanks for opening!

**Comment by roffe** [comment]
Any progress with this @ericchiang this is a blocker for me evaluating the software in our new business platform

**Comment by rithujohn191** [comment]
i'm working on this now. Should have a PR up by the end of the week :)

**Comment by ericchiang** [comment]
(PR here https://github.com/coreos/dex/pull/1062)
