### ISSUE TITLE
Quesiton: Dex + RBAC

### ISSUE THREAD

**Issue by alexandrst88** [coreos/dex#996]
Is there is possibility to create RBAC kubernetes group and bind it to some role(readonly for example), and then to authenticate user and grant him the same right as created group?

```I0718 15:25:48.360002       5 rbac.go:87] RBAC DENY: user "user@ldapr.com" groups [system:authenticated] cannot "list" resource "pods" cluster-wide```  

This user is authenticate via app + dex -> kubernetes, but instead of create each user and bind it to role, I would like to create a group in Kubernetes which will match the group of ldap of user?

**Comment by ericchiang** [comment]
The oidc-groups-claim is what you want on the kubernetes side https://kubernetes.io/docs/admin/authentication/#configuring-the-api-server

The groups scope is what you want on the dex side https://github.com/coreos/dex/blob/master/Documentation/custom-scopes-claims-clients.md#scopes

**Comment by alexandrst88** [comment]
How can I pass custom claims?
```
{
"issuer": "https://dex.com",
"authorization_endpoint": "https://dex.com/auth",
"token_endpoint": "https://dex.com/token",
"jwks_uri": "https://dex.com/keys",
"response_types_supported": [
"code"
],
"subject_types_supported": [
"public"
],
"id_token_signing_alg_values_supported": [
"RS256"
],
"scopes_supported": [
"openid",
"email",
"groups",
"profile",
"offline_access"
],
"token_endpoint_auth_methods_supported": [
"client_secret_basic"
],
"claims_supported": [
"aud",
"email",
"email_verified",
"exp",
"iat",
"iss",
"locale",
"name",
"sub"
]
}
```

**Comment by alexandrst88** [comment]
thanks, I need to pass `groups` when go to dex. It can be closed
